### ISSUE TITLE
'StoredAccountInfo' object has no attribute 'authorize_automatically'

### ISSUE THREAD

**Issue by jcalonso** [Backblaze/B2_Command_Line_Tool#100]
I'm having this error on b2 cli tool version: `0.4.8`

I imagine i need some sort of `authorize_automatically` key in my `~/.b2_account_info` config file?

```
b2 sync my_folder b2:my_bucket/my_folder
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.4.8', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 759, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 245, in run_command
    return self.sync(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 675, in sync
    recursive=True
  File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 114, in ls
    response = session.list_file_names(self.id_, start_file_name, fetch_count)
  File "/usr/local/lib/python2.7/dist-packages/b2/session.py", line 40, in wrapper
    reauthorization_success = self.account_info.authorize_automatically()
AttributeError: 'StoredAccountInfo' object has no attribute 'authorize_automatically'
```

Reauthorizing manually with: `b2 authorize_account` fixes it temporarily.

Any ideas?

**Comment by ppolewicz** [comment]
It looks like a bug in my code. I will look into it tonight.

**Comment by alanfranz** [comment]
Hello, do you think you're doing a release for this or I'd better clone the repository and use the tool from git?

**Comment by ppolewicz** [comment]
We have releases on Thursdays

**Comment by ppolewicz** [comment]
Release was done, you can now update from pip
