### ISSUE TITLE
File uploads failing with "ERROR: More than one concurrent upload using auth token <token>"

### ISSUE THREAD

**Issue by ianthetechie** [Backblaze/B2_Command_Line_Tool#1045]
We are using the b2 CLI to upload files like so:

```
b2 file upload <bucket> <path> <path>
```

Over the past few days, we have been unable to upload a file due to this error in the middle of the transfer:

```
ERROR: More than one concurrent upload using auth token <token>
```

I do not understand why this is happening. To my knowledge, the claim isn't even true. And even if it were, why is it suddenly killing established transfers which have already uploaded tens of gigabytes?

We observed this using the b2 CLI versions 4.0.1 and 4.1.0. Both were binaries downloaded from GitHub release artifacts.

**Comment by ppolewicz** [comment]
It's the server returning this error, not the client. If you try again, the file upload should continue from where it left off (to an extent), but generally in order to investigate it, we'll need logs, which you can get by adding `--debugLogs` which will create a `b2_cli.log` file which will then, hopefully, allow us to find out what happened.

What I guess is happening is the client breaks off the connection (on tcp level?) and tries again, but the server still sees the old connection as alive and returns an error. Logs will tell us if it's connected to a retry. It shouldn't generally happen and it's been years since we've had these issues, but one time it happened in the last few months.

Alternatively you can use `--verbose` to return logs to the terminal (then you can redirect it to a file, but best to disable the progress reported in such case as otherwise it'll flood the log file).

**Comment by ianthetechie** [comment]
It did eventually resolve itself after multiple attempts (5?). It did not however resume where it left off, which was strange.

I'll follow the debug logging instructions if I run into this again. Thanks! Feel free to close this issue if needed as it's not currently actionable I guess.

**Comment by ppolewicz** [comment]
I'm pretty sure in the case I mentioned earlier, we should assume that the token was bad and we should get a new one, but maybe if it's a simple connection error we don't reset the tokens and that's where the issue is coming from?

It's very hard to say without logs.

If someone one day catches it with a log, please help us debug it - once we know what the problem is, it should be easy to fix.

**Comment by ianthetechie** [comment]
Sorry to necro an old thread here, but I've done that thing where I go searching on the internet and come back to.... my old issue :P 

This problem has not gone away for us (it reoccurred today such that it took 3 retries to get the upload to succeed with the b2 CLI). We still experience it *fairly* regularly. We are not uploading from random home internet connections, but servers in datacenters. The files are usually pretty large (tens of gigabytes, but not hundreds).

Is `--debugLogs` still the best way to debug this? I can't find a single mention of this in the [docs](https://b2-command-line-tool.readthedocs.io/en/master/), though verbose shows up in the `sync` docs 🤔 It'd probably be easier for us to dump this to stdout as this runs in a CI pipeline, assuming verbose doesn't produce megabytes worth of output. Would the following structure work: `b2 file upload --threads 24 --no-progress --verbose bucket-name "/path/to/local" "/path/to/remote"`?

**Comment by ppolewicz** [comment]
The command looks good.

Perhaps the local IO gets stuck? We've seen a case where there were a lot of threads and a very throttled io instance couldn't get enough reads to fill a buffer enough to send something over the network and an idle connection was closed by the server after a minute or two.

**Comment by tanji** [comment]
I can confirm I get this error on a daily basis, I use either `b2 sync` or `b2 file upload` using b2 version 4.4.2 to upload hourly backups usually consisting of thousands of files to our b2 buckets.

Latest exception from this morning:

```
b2_upload(/tmp/sqldump/db-pf/2025-12/09/1930/version.00000.sql.zst, db-platform/2025-12/09/1930/backend-1.version.00000.sql.zst, 1765309040952): UploadTokenUsedConcurrently() More than one concurrent upload using auth token REDACTED
ERROR:b2sdk._internal.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/sync/action.py", line 56, in run
    self.do_action(bucket, reporter)
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/sync/action.py", line 163, in do_action
    bucket.concatenate(
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/bucket.py", line 1238, in concatenate
    return self.create_file(
           ^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/bucket.py", line 1011, in create_file
    return self._create_file(
           ^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/bucket.py", line 1158, in _create_file
    return emerger_method(
           ^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/emerge/emerger.py", line 174, in emerge
    return self._emerge(
           ^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/emerge/emerger.py", line 116, in _emerge
    return self.emerge_executor.execute_emerge_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/emerge/executor.py", line 82, in execute_emerge_plan
    return execution.execute_plan(emerge_plan)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/emerge/executor.py", line 231, in execute_plan
    part_sha1_array = [f.result()['contentSha1'] for f in part_futures]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/emerge/executor.py", line 231, in <listcomp>
    part_sha1_array = [f.result()['contentSha1'] for f in part_futures]
                       ^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/transfer/outbound/upload_manager.py", line 170, in _upload_part
    response = self.services.session.upload_part(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/session.py", line 399, in upload_part
    return self._wrap_token(
           ^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/session.py", line 473, in _wrap_token
    return self._execute_with_auth_retry(partial_callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/session.py", line 486, in _execute_with_auth_retry
    return callback()
           ^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/session.py", line 573, in _upload_part
    response = f(upload_url, upload_auth_token, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/raw_api.py", line 1100, in upload_part
    return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/b2http.py", line 359, in post_content_return_json
    return self.request_content_return_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/b2http.py", line 314, in request_content_return_json
    response = self.request(
               ^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/b2http.py", line 284, in request
    return self._translate_and_retry(do_request, try_count, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/b2http.py", line 597, in _translate_and_retry
    return cls._translate_errors(fcn, post_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/rundeck/.local/pipx/venvs/b2/lib/python3.11/site-packages/b2sdk/_internal/b2http.py", line 525, in _translate_errors
    raise interpret_b2_error(
b2sdk._internal.exception.UploadTokenUsedConcurrently: More than one concurrent upload using auth token REDACTED
```
`--threads=1` _appears_ to make the issue go away, but it makes the uploads awfully slow.

**Comment by ppolewicz** [comment]
@tanji We couldn't reproduce it reliably so far, so this is great news! In order to investigate it, we'll need logs, which you can get by adding `--debugLogs` which will create a `b2_cli.log` file which will then, hopefully, allow us to find out what happened.

**Comment by ppolewicz** [comment]
This is a very rare issue, it's over a year since it was reported and we didn't ever catch the logs of it.

S3 cli is very, very slow compared to b2 cli.

**Comment by j-palindrome** [comment]
I can report this is also an issue for me, using a home Internet connection. It happens every single time I call `b2 sync`.

**Comment by tanji** [comment]
The logs have been sent to your email

**Comment by olzhasar-reef** [comment]
@tanji Could you kindly upgrade the CLI to v4.6.0 and let us know if the problem is gone, whenever you have a chance?

**Comment by tanji** [comment]
> @tanji Could you kindly upgrade the CLI to v4.6.0 and let us know if the problem is gone, whenever you have a chance?

I've upgraded the CLI but it might take some time as we had to switch our scripts back to AWS CLI to avoid all the errors. I'll let you know if the issues show up again.
