### ISSUE TITLE
Broken symlink break sync

### ISSUE THREAD

**Issue by jcalonso** [Backblaze/B2_Command_Line_Tool#149]
I had this issue where one of my sysmlinks was broken and b2 tool broke, this is the stack trace:

```
Traceback (most recent call last):                                                
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.5.4', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 861, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 789, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 609, in run
    max_workers=max_workers
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 877, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 777, in make_folder_sync_actions
    for (source_file, dest_file) in zip_folders(source_folder, dest_folder):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 646, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 620, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 499, in all_files
    yield self._make_file(relative_path)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync.py", line 553, in _make_file
    mod_time = int(round(os.path.getmtime(full_path) * 1000))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/media/2a9074d0-4788-45ab-bfae-fc46427c69fa/PersonalData/some-broken-symlink'

```

**Comment by bwbeach** [comment]
What should sync do with symlinks?  

Right now it's following the symlink.  Which seems reasonable to me.  What should it do with a broken symlink?  Would a nice error message solve the problem?

**Comment by simongreen-net** [comment]
I'd prefer a  --no-sync-symlink option (or something similar), but a warn option is good enough.

I use encfs before sending data offsite, so some symlinks don't exist.

**Comment by Telofy** [comment]
Permission denied errors have similar effects, i.e., also break off the sync. Something like this would be really cool:

    diff --git a/b2/sync/folder.py b/b2/sync/folder.py
    index 52af481..cb25e34 100644
    --- a/b2/sync/folder.py
    +++ b/b2/sync/folder.py
    @@ -122,7 +122,7 @@ class LocalFolder(AbstractFolder):
                 full_path = os.path.join(dir_path, name)
                 relative_path = full_path[prefix_len:]
                 # Skip broken symlinks or other inaccessible files
    -            if not os.path.exists(full_path):
    +            if not os.path.exists(full_path) or not os.access(full_path, os.R_OK):
                     if reporter is not None:
                         reporter.local_access_error(full_path)
                 else:

**Comment by ppolewicz** [comment]
Reporter should be extended to handle permission errors. Thanks for the suggestion.

**Comment by Telofy** [comment]
Wow, thank you!

**Comment by ppolewicz** [comment]
My pleasure!
