### ISSUE TITLE
b2 command line from doc

### ISSUE THREAD

**Issue by sentabi** [Backblaze/B2_Command_Line_Tool#15]
Maybe you need to change link to b2 tools from https://www.backblaze.com/b2/docs/quick_command_line.html maybe to github? because link from doc not working

```
$ b2 authorize_account ae2424115563411111111 001eba671154b1ab4f85cb846af9c4aea
Traceback (most recent call last):
  File "/home/tommy/src/b2", line 949, in <module>
    main()
  File "/home/tommy/src/b2", line 912, in main
    authorize_account(args)
  File "/home/tommy/src/b2", line 355, in authorize_account
    url = auth_urls[option]
KeyError: '--production'
````
I tried b2 from this git repo and it just works.

**Comment by bwbeach** [comment]
That's been fixed.  Thanks for the report.
