### ISSUE TITLE
Errors while installing/updating (OS X 10.11.5)

### ISSUE THREAD

**Issue by JayBrown** [Backblaze/B2_Command_Line_Tool#176]
Wanted to update b2 cli from 0.4.4 to the latest version and got this:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/requests'
```

Tried with the `--ignore-installed` option, didn't work. Tried running `sudo chflags -R norestricted /System/Library/Frameworks/Python.framework` beforehand, didn't work.

**Comment by ppolewicz** [comment]
What was the command that you executed in order to perform the package upgrade?

**Comment by JayBrown** [comment]
`pip install b2`
`pip install --ignore-installed b2`
Both didn't work.

**Comment by ppolewicz** [comment]
It would seem that you are not using virtualenv and you are not a superuser, so it doesn't work. `sudo pip install --upgrade b2` ?

**Comment by JayBrown** [comment]
Oh damn, just noticed that I installed b2 as part of the b2-tools with homebrew. When running brew upgrade, it thinks that 0.4.4 is the latest version. Did you drop homebrew support?

**Comment by JayBrown** [comment]
uninstalling the brewed b2-tools and re-installing with sudo pip did the trick. ty.
