### ISSUE TITLE
Error on interrupt

### ISSUE THREAD

**Issue by dwisehart** [Backblaze/B2_Command_Line_Tool#201]
At the end of sync'g a large drive through he CLI on MacOS 10.11.6, the CLI will often hang. After the program sits all night or longer I use ^C to interrupt the program. On the first interrupt--which does not stop the program--I always see the same error:

```
Interrupted. Shutting down...
Traceback (most recent call last):
File "/usr/local/bin/b2", line 9, in <module>
load_entry_point('b2==0.5.6', 'console_scripts', 'b2')()
File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 880, in main
os._exit(exit_status)
TypeError: an integer is required

```
The CLI is still running (hung) at this point. It takes a second ^C to get the program to exit, which it does with this traceback:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 39, in _python_exit
t.join(sys.maxint)
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 951, in join
self.__block.wait(delay)
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
_sleep(delay)
File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 49, in keyboard_interrupt_handler
raise KeyboardInterrupt()
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
func(*targs, **kargs)
File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 39, in _python_exit
t.join(sys.maxint)
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 951, in join
self.__block.wait(delay)
File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
_sleep(delay)
File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 49, in keyboard_interrupt_handler
raise KeyboardInterrupt()
KeyboardInterrupt

```

**Comment by svonohr** [comment]
Please update to the newest b2 version. I already [fixed](https://github.com/Backblaze/B2_Command_Line_Tool/commit/afdf1a174f03dd3ec92bb4db56b1f5c33f060a26) this 2 months ago. The fix is available since v.0.6.0.

**Comment by dwisehart** [comment]
Thanks, that fixed the interrupt problem I was seeing.

I reported the sync hanging problem separately.  It will be a few hours before I know if that problem is still there.
