### ISSUE TITLE
AssertionError: non-ascii character in str returned by os.listdir

### ISSUE THREAD

**Issue by eby** [Backblaze/B2_Command_Line_Tool#204]
This might not be worth fixing but thought I'd pass it along. When doing a `b2 sync` command on a large directory of files with questionable names (1M+ files) I get the error below. Unfortunately due to the number of files it is difficult for me to locate which file is causing the issue.

This is on linux w/ 3.2.12 kernel and a JFS filesystem.

I did some searching and it looks like Python2 has some issues with undecodable bytes and unicode but python3 fixes the implementation. I uninstalled b2 from 2.7 packages and installed it for just 3.4.x python and I'm not getting the error anymore.

Just passing on in case there should be a catch for the exception.

```
Traceback (most recent call last):
  File "/usr/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.2', 'console_scripts', 'b2')()
  File "/usr/lib64/python2.7/site-packages/b2/console_tool.py", line 879, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/lib64/python2.7/site-packages/b2/console_tool.py", line 806, in run_command
    return command.run(args)
  File "/usr/lib64/python2.7/site-packages/b2/console_tool.py", line 623, in run
    max_workers=max_workers
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 951, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 848, in make_folder_sync_actions
    for (source_file, dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions):
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 686, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 656, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 674, in <genexpr>
    f for f in folder_a.all_files(reporter) if not any(ex.match(f.name) for ex in exclusions)
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 509, in all_files
    for relative_path in self._walk_relative_paths(prefix_len, self.root, reporter):
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 580, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 580, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 580, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "/usr/lib64/python2.7/site-packages/b2/sync.py", line 551, in _walk_relative_paths
    ord(c)
AssertionError: non-ascii character in str returned by os.listdir: 195
```

**Comment by ppolewicz** [comment]
Do you consider the 1M+ filenames a secret? If we could replicate your environment, even when there are so many files, it would make it possible to reproduce the problem.

Also please see [this](https://github.com/Backblaze/B2_Command_Line_Tool/issues/190#issuecomment-236682462) comment for a possible workaround

**Comment by eby** [comment]
No they shouldn't be. I'll see if I can generate a file with them. 

And LANG wasn't set so I'll get it a whirl in python2.7 with it set to utf8 first.

**Comment by eby** [comment]
I can confirm that setting the lang to utf8 fixes the issue with python2.7 

listing of filenames is attached but I'd consider this closed since python handles it correctly if the environment is setup correctly

[storage-filenames.txt.gz](https://github.com/Backblaze/B2_Command_Line_Tool/files/405634/storage-filenames.txt.gz)
