### ISSUE TITLE
sync --keepDays cannot handle out-of-order versions

### ISSUE THREAD

**Issue by peff** [Backblaze/B2_Command_Line_Tool#216]
When using `--keepDays`, commit 0cdddf67ef57c19d8e25e59e0970198e55ca87aa iterates over the existing versions with this assertion:

```
        # We assume that the versions are ordered by time, newest first.
        assert prev_age_days is None or prev_age_days <= age_days
```

However, that assertion may not be true if the previous versions were created with `--replaceNewer`; the timestamps may be in any order. You can see this with, for example:

```
# one version in the bucket
echo one >file
b2 sync ./ $bucket

# now the newer version has an older timestamp
echo two >file
touch -d 20160701 file
b2 sync --keepDays 180 --replaceNewer ./ $bucket
```

If you try to sync again, we hit the assertion:

```
$ b2 sync --keepDays 180 --replaceNewer ./ $bucket
Traceback (most recent call last):                                 
  File "/home/peff/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.5', 'console_scripts', 'b2')()
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 879, in main
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 806, in run_command
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 623, in run
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 179, in sync_folders
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 120, in make_folder_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 85, in make_file_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 99, in get_all_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 167, in _get_hide_delete_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 227, in make_b2_keep_days_actions
AssertionError
```

I don't see a quick fix here. The strategy used in `make_b2_keep_days_actions` does depend on traversing in reverse-version order, so sorting the list before the loop is out. I think it actually needs go back to handling the selective deletion of arbitrary versions from the list.

/cc @bwbeach

**Comment by ppolewicz** [comment]
Nice analysis and a well written report, thanks!

Since you have analyzed the relevant part of the code, would you like to try to implement a fix and submit a pull request? We have static code analysis, a pre-commit script which includes automatic code formatting and unit tests that run on 14 versions of python (including osx and jython).

If I understand correctly, the selective deletion of arbitrary versions from the list only needs to be done when `--replaceNewer` flag is used, so if it is not, we can keep the current (more efficient?) behavior.

**Comment by bwbeach** [comment]
The question is: What is the right behavior?

I think it needs to act like the versions are sorted in the order of last-modified-time.  It needs to keep all versions newer than the keepDays, plus the most recent version that is older than keepDays.

You could do this by iterating through the list, with a variable holding the most recent (non-hidden) version older than keepDays.  If it finds a more recent version, it can delete the one it had, and set the variable to the new one.

Are you interested, @peff, in fixing the code?  It will be a few days before I can get to it.

**Comment by peff** [comment]
I wasn't quite comfortable producing a patch because I'm not sure I understand all of the details of how versioning and hiding work in b2 (which I'm quite new to in general).

The behavior described by @bwbeach (to keep one version older than `--keepDays`) makes sense (to keep a snapshot as of that moment). But I'm not clear on how hiding works. Is it basically just a placeholder for "there is no version of the file in the current version, but there are older versions?" I.e., sort of a "no data here" sentinel?

Specifically, I was wondering if we can have hidden entries further back in the version chain. I.e., can we have:

```
(content=X, time=10)
(<hidden>, time=20)
(content=Y, time=30)
```

If we want to preserve the state back at time=25, then the file was `<hidden>` then. We don't need the first entry with content `X`, because it was already gone by then.

**Comment by peff** [comment]
> Specifically, I was wondering if we can have hidden entries further back in the version chain.

Hmm, yeah, the example at https://www.backblaze.com/b2/docs/file_versions.html makes it clear that this can happen.  So if the goal is to retain the state, whatever it was, at some time `t` (that is `--keepDays` old), then we don't have to care about hidden versus not. We just delete everything older than `--keepDays` _except_ the most recent thing, whether hidden or not, because that represents the state at that time.

Does that make sense?

**Comment by bwbeach** [comment]
Yes.  That makes complete sense.  Thanks for thinking through the details.

**Comment by ppolewicz** [comment]
@peff: I think that is correct, but there is a special case where if all versions older than keepDays except the last one are being deleted and the last one is a hidden marker, then we should delete the marker as well.

**Comment by ppolewicz** [comment]
So @peff, will you now try to create a patch?

**Comment by peff** [comment]
I just opened #219, which does seem to fix my problematic case. However, I have some misgivings about the whole approach. We are effectively ordering things by the `mod_time` of each version, but the `mod_time` does not necessarily reflect the order of the updates (which _is_ reflected in the iteration order of the versions).

So what I'd really like `keepDays` to do is to preserve whatever I uploaded `N` days ago. But because it's trusting these possibly out-of-order `mod_time`s, you can get weird cases. For example, imagine you had these versions (which were posted in this order):

```
(1) id=A, mod_time=100
(2) <hidden>, mod_time=300
(3) id=B, mod_time=200
```

and you set `keepDays` to cut off at `time=400`. Strictly following the chain in order, the most recent thing we saw was `B`. But we won't keep that. We'll bump the hide-marker to the "front" of the chain of deletions, drop everything else, and then drop the hide-marker as worthless (since it has nothing behind it).

But would the user be happier if we _kept_ `B`? Clearly something funny is happening with the `mod_time` on the original client that pushed these up (out of order clocks, or perhaps step 3 was correcting an old mistake by restoring the file from a version with an older `mtime`).

So I actually wonder if @bwbeach's original is doing the right thing: walk backwards and find the most recent version (by chain order!) that needs deleting, and skip deleting that to keep it as the sentinel value. But then as we walk back from there, either delete (or don't, if it has an out of order time within `keepDays`) each version, but always keep that tip value regardless (and if the tip is a `hide`, then we would actually retain it, but only if there is stuff behind it).

I dunno. I guess it depends on whether you trust `mod_time` to be a sensible measurement for `--keepDays` or not. It is when `--replaceNewer` is in effect, but it's not necessarily otherwise. I don't know very much about b2, but it seems like all we have (I'd think ideally we would want "time of upload", not the file mtime).

**Comment by ppolewicz** [comment]
We've seen enough time-desynched servers ruining everything (not in this project yet, but still).

I suggest that we request a new, simple, unauthenticated, remote resource, `/getCurrentTime`, which would return time accurate to one second. Then we will use that time to put metadata in the params dict which will say what the _server time_ was when the file was synched/uploaded. Then a `sync` with `--keepDays` would again use the _server time_ to compute which files should be deleted and which should not be. The unit tests will be run with a time set to 1970-01-01 (using [freezegun](https://github.com/spulec/freezegun) or alike) to make sure we don't rely on a (possibly very bad) time on the server.

On another note, if `sync` with `--keepDays` is started with a time difference between the system clock and the Backblaze clock which exceeds one day, then we will fail immediately unless a special flag is provided. This is to make sure that we don't delete too much data due to a failing system clock on an existing system which has its clock set to a long time ago.

What do you think about such approach? @bwbeach, @peff, @svonohr

**Comment by svonohr** [comment]
Doesn't the b2 file info already store the upload time of the b2 servers?
So we don't need to put it into the metadata again. This seems like an
additional feature which would stop a client with an out of sync clock from
potentially deleting everything.

Am 26.08.2016 13:08 schrieb "Paweł Polewicz" <notifications@github.com>:

**Comment by bwbeach** [comment]
Yes.  Each file has an upload timestamp, which is the time on the server at the point where the upload started:

```
{
      "action": "hide",
      "contentLength": 0,
      "fileId": "4_z27c88f1d182b150646ff0b16_f100920ddab886247_d20150809_m232323_c100_v0009990_t0005",
      "fileName": "files/world.txt",
      "size": 0,
      "uploadTimestamp": 1439162603000
}
```

**Comment by bwbeach** [comment]
I agree with @ppolewicz that adding a clock check before syncing would be a good idea.

Do we need an API from Backblaze?  Or is there an existing service to check the clock against?

**Comment by svonohr** [comment]
Maybe we can get the server time from the HTTP response?

Am 26.08.2016 18:56 schrieb "Brian Beach" <notifications@github.com>:

**Comment by ppolewicz** [comment]
@peff does having a reliable "time of upload" straighten up all of design issues you discussed in your last comment? Ideally, relying on a `modTime` which the client has, would be only used as a "maybe" hint to check whether the file was modified or not, and then we would compare the checksum and be sure. This way a client which has issues with the clock that won't make the sync fail immediately, will, in the worst case, do a checksum but upload nothing (so it'd be just a performance issue). Does that make sense?

**Comment by peff** [comment]
@ppolewicz Yeah, if `keepDays` used "time of upload" instead, that would be perfect. I agree on using the `mtime` as a "did it change" optimization (in git, we use several fields from `stat` (like inode, device, etc) and err on the side of re-checking the sha1, but I think you may be limited here to what BackBlaze stores and returns, since you don't keep a local stat-cache).

And then I think that would make my fix in #219 obsolete, because we really _would_ see the chains in reverse-chronological order. Assuming that BackBlaze doesn't have clock skew itself on the server side.

I haven't looked, but in theory the fix there is literally just something like `s/modTime/uploadTime/`.

**Comment by bwbeach** [comment]
That makes sense.  And if it's always the case that `modTime <= uploadTime`, then you'll aways have at least `keepDays` of history counting by `modTime`.

Then, if we also add a check to make sure that the modTimes are not ahead of the server's clock, things should be good.

**Comment by ppolewicz** [comment]
We still need a way to get the current server time, right? In case there is not a single file which is being uploaded (because in such case we could get the upload time of that file) (although such approach trades number of requests for increased code complexity to an extend with which I am not very comfortable with).

**Comment by bwbeach** [comment]
The server returns a standard Date header in all responses:

    Date: Sat, 27 Aug 2016 01:15:58 GMT

We could capture it from the first `list_file_versions` request that sync makes.

**Comment by ppolewicz** [comment]
Ok. Who implements which part of it?

**Comment by ppolewicz** [comment]
breaking down the implementation into subissues: #237, #238

@bwbeach wrote
> Then, if we also add a check to make sure that the modTimes are not ahead of the server's clock, things should be good

what should we do when the check fails?

**Comment by RX14** [comment]
This issue is preventing me from backing up to b2. I nearly lost some data, but I can't blame anyone but myself for not checking the return code of `b2`. Is there a workaround?

**Comment by ppolewicz** [comment]
@RX14 what was the scenario?

**Comment by RX14** [comment]
@ppolewicz I'm not entirely sure, I had `backblaze-b2 sync --keepDays 365 --replaceNewer /foo b2://foo/` in a cronjob every 30 mins and at some point it stopped working.

**Comment by ppolewicz** [comment]
Could you please add `--debugLogs` and share the log file?

**Comment by RX14** [comment]
Here you go: https://aww.moe/2scwk0.log

Not sure it's going to tell you any more than you already know.

**Comment by RX14** [comment]
Please, please can you fix this bug. Or at the very least provide a workaround. It ends up affecting all my syncs eventually. I love b2 and have over 600gb of backups stored in it, but this bug going ignored means I just can't rely on the sync tool.

**Comment by svonohr** [comment]
Note that this assertion that caused your sync to fail was removed a few weeks ago. The new 0.7.2 version already contains the change. See #331 for a similar issue. For the new behaviour see this comment in the code: https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/b2/sync/policy.py#L259
