### ISSUE TITLE
b2 0.6.4 - AttributeError: 'NoneType' object has no attribute 'versions'

### ISSUE THREAD

**Issue by jcalonso** [Backblaze/B2_Command_Line_Tool#220]
Hi, Today I upgrade the b2 cli and now I'm getting the following error:

```shell
b2 version
b2 command line tool, version 0.6.4
root@myserver:/media/storage/data# b2 sync --delete --replaceNewer myFolder b2:myBucket/myFolder
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.4', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 879, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 806, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 623, in run
    max_workers=max_workers
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 179, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 120, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 85, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/policy.py", line 99, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/policy.py", line 152, in _get_hide_delete_actions
    self._source_file, self._dest_file, self._dest_folder, self._transferred
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/policy.py", line 194, in make_b2_delete_actions
    for version_index, version in enumerate(dest_file.versions):
AttributeError: 'NoneType' object has no attribute 'versions'
```

Any ideas?

**Comment by jcalonso** [comment]
Just noticed that this is a possible dup of https://github.com/Backblaze/B2_Command_Line_Tool/issues/218

**Comment by renebouwmeester** [comment]
Same here. Plain sync works OK. With --keepDays:

```
rene@linuc:~$ b2 sync --keepDays 30 --replaceNewer /path/folder/ b2:bucket
Traceback (most recent call last):                                     
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.5', 'console_scripts', 'b2')()
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 879, in main
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 806, in run_command
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 623, in run
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 179, in sync_folders
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 120, in make_folder_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 85, in make_file_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 99, in get_all_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 167, in _get_hide_delete_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 222, in make_b2_keep_days_actions
AttributeError: 'NoneType' object has no attribute 'versions'
```

After starting (and aborting) a regular sync:

rene@linuc:~$ b2 sync --keepDays 30 --replaceNewer /path/folder/ b2:bucket
Traceback (most recent call last):                                     
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.5', 'console_scripts', 'b2')()
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 879, in main
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 806, in run_command
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 623, in run
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 179, in sync_folders
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 120, in make_folder_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 85, in make_file_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 99, in get_all_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 167, in _get_hide_delete_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 227, in make_b2_keep_days_actions
AssertionError

**Comment by reversesh3ll** [comment]
Issue is present in 0.6.5 as well.

**Comment by ppolewicz** [comment]
I have read through the code that hits the error, but have not spotted a culprit yet. Could you please describe what you are doing? Is it some rare case like `--keepDays 0` or something like that? Meanwhile I am working on logging (so that we can debug faster in the future).

**Comment by reversesh3ll** [comment]
Nothing special. Using b2 version 0.6.5 and python 2.7.12.

`b2 sync --keepDays 30 --replaceNewer /data/ b2://bucket/data/`

Its actually running in a docket container but i wouldn't think that should affect it.
I currently have version 0.6.2 working without issues.

**Comment by reversesh3ll** [comment]
Here is the error that I get on version 0.6.5.
```
#b2 sync --keepDays 30 --replaceNewer /data/ b2://bucket/data/
Traceback (most recent call last):
  File "/usr/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.5', 'console_scripts', 'b2')()
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 879, in main
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 806, in run_command
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 623, in run
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 179, in sync_folders
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 120, in make_folder_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 85, in make_file_sync_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 99, in get_all_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 167, in _get_hide_delete_actions
  File "build/bdist.linux-x86_64/egg/b2/sync/policy.py", line 222, in make_b2_keep_days_actions
AttributeError: 'NoneType' object has no attribute 'versions
```
`
Seems like it might be related to subfolder creation in the bucket.
If I try to sync to a folder that doesnt already exist in the bucket, it creates the folder then throws the error but if i run the command a second time, it completes without error. (when subfolder already exists)

**Comment by ppolewicz** [comment]
This is really helpful, thanks!
