### ISSUE TITLE
urlopen error [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by perlporter** [Backblaze/B2_Command_Line_Tool#230]
uname -r
10.3-RELEASE-p3

Size of file:
ls -lh BACKUPMENSAL_01-08-2016.tar.gz
-rw-r--r--  1 root  wheel   6.6G Aug  1 00:38 BACKUPMENSAL_01-08-2016.tar.gz

 b2 upload_file d4643a2120ae3c415518041e BACKUPMENSAL_01-08-2016.tar.gz BACKUPMENSAL_01-08-2016.tar.gz application/x-gzip
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 939, in <module>
    main()
  File "/usr/local/bin/b2", line 932, in main
    upload_file(args)
  File "/usr/local/bin/b2", line 686, in upload_file
    response = post_file(url, headers, local_file)
  File "/usr/local/bin/b2", line 309, in post_file
    with OpenUrl(url, data_file, encoded_headers) as response_file:
  File "/usr/local/bin/b2", line 267, in __enter__
    self.file = urllib2.urlopen(request)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 32] Broken pipe>

**Comment by ppolewicz** [comment]
@perlporter you are using an old version of b2 command line tool. Please use `pip install --upgrade b2_command_line_tool` to upgrade it.
