### ISSUE TITLE
Fails to upload file

### ISSUE THREAD

**Issue by mohmad-null** [Backblaze/B2_Command_Line_Tool#248]
I'm trying to use the utility on Windows and it's failing.

First error:
Command run:
`C:\Python27\Scripts>b2 upload_file regular-backups "c:\myfile.zip" "myfile.zip"`

When it crashed out after a few minutes:

> c:\myfile.zip: 51%|#### | 655M/1.29G [19:46<1:46:33, 99.8KB/s]
> ERROR: FAILED to upload after 5 tries. Encountered exceptions:
> Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
> Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
> Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
> Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
> Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

I then tried to run the original command again, and immediately got the below error:

> c:\myfile.zip:    0%| | 0.00/1.29G [00:00<?, ?B/s]
> ERROR: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v1/b2_list_unfinished_large_files
> (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003473358>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by mohmad-null** [comment]
This is using a new install of the B2 CLI on Python 2.7. My first attempt to upload a file using this tool.

**Comment by ppolewicz** [comment]
Please add a `--threads 1` parameter right after `upload_file`. Your file is very big and your connection is very slow, so threading does not help, so to speak.

**Comment by mohmad-null** [comment]
That does work, but I get a constant speed of 80kB/s. My line is capable of 1.3MB/S (11Mb/s).

If I set it to --threads 5, I get a throughput of just under 400kB/s.
Any higher than that and the speed fluctuates wildly (though no higher than about 500kB/s).


I'm in the UK on what passes for "superfast broadband" in this country. I'm seeing ping times to the IP address it's uploading to on the order of 190ms.

Any thoughts on how to use my line's full capacity? At this rate any uploads will take probably 3 times longer than they should.

**Comment by ppolewicz** [comment]
That one is really interesting.

threads | average speed | other info
------------ | ------------- | -------------
1 | 0.64 Mb/s | steady
5 | ~3.2 Mb/s | highest non-fluctuating value
10 | ~0.8 Mb/s **average** | speed fluctuations, **timeout**

What about your source device and CPU? Can you check in your... task manager "performance" tab what is the average response time of the drive and could you check if one of the CPU cores is not overloaded?

I suspect this was a temporary network problem between your device and a B2 server. Actual number of threads necessary to saturate the link in your case seems to be about 18 (I'd say 20-22 just in case), but the file which you are uploading is only `1.29GB`, so when it is cut to 100MB pieces, only 13 of them can be processed in parallel (with default settings, that is). This should output a little over 8 Mbps.

I do not know why the single thread speed is only 640Kbps in your case. Maximum throughput with a TCP window of 64 KB and RTT of 190 ms is 2.76 Mbps. Maybe it is because of packet loss?

**Comment by mohmad-null** [comment]
Even with 5 threads I'm still getting the original error before the file has finished:
Connection error: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

**Comment by ppolewicz** [comment]
How long did the upload attempt last this time?

**Comment by mohmad-null** [comment]
It got to about 75%, continuing from 43%. So about 30% in 23 mins. About the same as 10 threads.

1 Thread has just completed it (from 75%), albeit at a speed of 80kB/s, and taking over an hour.

For reference, my normal backup solution is a Python SFTP script which, while it doesn't max out my upload speed (due to a limitation/bug in the SFTP library), has never timed out to the best of my knowledge. File sizes are similar.

**Comment by ppolewicz** [comment]
It can either be a b2 server-side timeout being a little too aggressive or a really weird network issue on the client side. The former is being investigated. We could push it further and prove which one is it, but since the server is in control of Backblaze and they are pretty responsive with this kind of matters, then lets wait a moment and see what they can find.

**Comment by mohmad-null** [comment]
The good news is, the original issue seems to be solved - files now upload without crashing out.

The bad news is that the maximum speed seems to be 100kB/s for any given thread.

I've done some extensive testing over the last few days with one file and these are the results. (Running from an SSD on a machine with low CPU usage on any given core the entire time).

FileSize:	1293259966	bytes
Linespeed:	1330	Kilo Bytes / s

Threads   |Time (HH:MM:SS) 		|AvgSpeed (kB/s) |% Line Capacity|Speed/thread
         |2       |01:43:01          |204.33        |15.36%      |102.16
         |3       |01:12:59          |288.41        |21.68%       |96.14
         |4       |00:51:31          |408.59        |30.72%      |102.15
         |5       |01:10:14          |299.7        |22.53%       |59.94
         |6       |00:35:11          |598.27        |44.98%       |99.71
         |6       |00:34:15          |614.57        |46.21%      |102.43
         |7       |00:34:36          |608.36        |45.74%       |86.91
         |8       |00:45:32          |462.28        |34.76%       |57.79
         |8       |00:36:37          |574.85        |43.22%       |71.86
         |9       |00:38:24          |548.16        |41.21%       |60.91
        |10       |00:32:08          |655.06        |49.25%       |65.51
        |11       |00:35:39          |590.44        |44.39%       |53.68
        |12       |00:18:58          |1109.8        |83.44%       |92.48
        |10       |00:36:42          |573.55        |43.12%       |57.35
        |12       |00:20:33          |1024.29        |77.01%       |85.36
        |13       |00:17:55          |1174.84        |88.33%       |90.37
        |13       |00:24:11          |870.4        |65.44%       |66.95
        |13       |00:17:40          |1191.46        |89.58%       |91.65
        |14       |00:18:36          |1131.67        |85.09%       |80.83

**Comment by ppolewicz** [comment]
Can you upload faster with a single thread to a target with similar latency as b2?

**Comment by mohmad-null** [comment]
I've done some more testing.
B2 has a latency of about 150ms.

* Uploading a file to B2 using Cyberduck - one thread - maxes out at 140KB/s.
* Uploading a file via SFTP, one-thread to a server with 100ms timeout - 1.3MB/s.

So the latency doesn't appear to be the problem; backblaze is just very slow for uploads on a per-thread basis, irrespective of the technology used.

**Comment by ppolewicz** [comment]
@bwbeach / @nilayp is 140KB/s an expected speed at 150ms latency?

@mohmad-null Does SFTP use one TCP connection?
Can you try uploading from ramdisk? If it will not be faster, are you willing to collect raw network traces (using tcpdump) and share them with me so that I can perform further analysis? (I know it is encrypted, still I'd like to take a look)

My max network speed is somewhere between 4 Mbps and 6 Mbps, but I was able to upload with about 644KB/s using a single thread:
```
$ time b2 upload_file --threads 1 test234 ./random.dat random.dat
./random.dat: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 105M/105M [02:27<00:00, 708KB/s]
URL by file name: https://f001.backblazeb2.com/file/test234/random.dat
URL by fileId: https://f001.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=4_z547a2a395826655d561f0010_f1085103a084de6f3_d20160929_m230348_c001_v0001015_t0041
{
  "action": "upload", 
  "fileId": "4_z547a2a395826655d561f0010_f1085103a084de6f3_d20160929_m230348_c001_v0001015_t0041", 
  "fileName": "random.dat", 
  "size": 104857600, 
  "uploadTimestamp": 1475190228000
}

real	2m29.447s
user	0m0.876s
sys	0m0.212s
```
so your issue seems not to be b2 specific?

**Comment by mohmad-null** [comment]
@ppolewicz - SFTP is indeed using one and only one TCP connection (Confirmed using Process Explorer's "TCP/IP" tab).

I'm uploading from an SSD.

I'm afraid I don't know about tcpdump or how to use it.

Today I'm seeing speeds on the order of 100kB/s for a single thread upload to B2. Upload to SFTP remains 1.3MB/s


I'm wondering if it's related to the absurd tracert I'm seeing:

>   5    17 ms    17 ms    16 ms  ae13-600-xcr1.ltw.cw.net [195.2.23.77]
>   6    17 ms    17 ms    32 ms  ae32-xcr1.lns.cw.net [195.2.24.126]
>   7    18 ms    18 ms    19 ms  as174-gw-xcr1.lns.cw.net [195.2.22.22]
>   8    17 ms    17 ms    17 ms  be2871.ccr42.lon13.atlas.cogentco.com [154.54.58.185]
>   9    86 ms    85 ms    85 ms  be2983.ccr22.bos01.atlas.cogentco.com [154.54.1.178]
>  10    86 ms    87 ms    86 ms  be2302.ccr22.alb02.atlas.cogentco.com [154.54.43.14]
>  11    96 ms    96 ms    96 ms  be2879.ccr22.cle04.atlas.cogentco.com [154.54.29.173]
>  12   103 ms   103 ms   103 ms  be2718.ccr42.ord01.atlas.cogentco.com [154.54.7.129]
>  13   116 ms   115 ms   115 ms  be2832.ccr22.mci01.atlas.cogentco.com [154.54.44.169]
>  14   152 ms   152 ms   152 ms  be3036.ccr22.den01.atlas.cogentco.com [154.54.31.89]
>  15   154 ms   154 ms   154 ms  be3038.ccr21.slc01.atlas.cogentco.com [154.54.42.97]
>  16   157 ms   156 ms   157 ms  be2041.rcr21.smf01.atlas.cogentco.com [154.54.6.142]
>  17   155 ms   155 ms   155 ms  be2860.rcr13.smf03.atlas.cogentco.com [154.24.51.46]
>  18   175 ms   157 ms   158 ms  38.88.228.26
>  19   149 ms   149 ms   149 ms  162.244.57.11.rdns.backblaze.com [162.244.57.11]

9 hops just to cross the atlantic and then to the US west coast seems excessive- I seem to be bouncing around the US via every other router on the continent!
Telia can do the same trip (all the way to the west coast) in just 4 but doesn't seem to be the preferred peer for getting to backblaze from where I am. Although the Telia latency is actually aout 10% *higher* despite fewer apparent hops.

**Comment by ppolewicz** [comment]
I might be able to see something from a tcpdump. To collect it, you need a program like Wireshark. Then you should disable every program that can communicate via network, start the collection, upload a file to b2 (20MB should be enough), stop collection and share the file with us. I am not sure if it will help, but there is not much else we can do to debug it.

**Comment by mohmad-null** [comment]
A simple test tat should have occured to me sooner.
I uploaded a largeish file using the web interface. Upload speed (single thread TCP/IP) - about 700kB/s.

Therefore the problem is 100% with Python.

I am also seeing slower speeds with uploading to SFTP using Python as compared to using FileZilla. I wonder if it's whatever underlying library you're using?

(I've now upgraded to using Python 3.5)

**Comment by kazsulec** [comment]
Similar behaviour, possibly.

This command and error

tom@tombuntu-HP-G70:/media/tom/FreeAgent Drive/Images/100 Images/Canon Elph100HS$ b2 upload_file --debugLogs CanonElph100HS 7z/2014.7z.012 7z/2014.7z.012
7z/2014.7z.012:  23%|██████████████████▋                                                             | 245M/1.05G [07:32<24:47, 540KB/s]
ERROR: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v1/b2_get_upload_part_url (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f09cc18a910>: Failed to establish a new connection: [Errno 110] Connection timed out',))
tom@tombuntu-HP-G70:/media/tom/FreeAgent Drive/Images/100 Images/Canon Elph100HS$ 

left this in the log file

2016-12-08 22:46:02,617	4378	139680131815168	b2.console_tool	INFO	// ========================================  0.6.9   ======================================== \\
2016-12-08 22:46:02,617	4378	139680131815168	b2.console_tool	DEBUG	platform is Linux-4.4.0-51-generic-x86_64-with-Ubuntu-16.04-xenial
2016-12-08 22:46:02,618	4378	139680131815168	b2.console_tool	DEBUG	Python version is CPython 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
2016-12-08 22:46:02,618	4378	139680131815168	b2.console_tool	DEBUG	locale is ('en_CA', 'UTF-8')
2016-12-08 22:46:02,619	4378	139680131815168	b2.console_tool	DEBUG	filesystem encoding is UTF-8
2016-12-08 22:46:02,619	4378	139680131815168	b2.console_tool	INFO	starting command [b2.console_tool.UploadFile] with arguments: [u'/usr/local/bin/b2', u'upload_file', u'--debugLogs', u'CanonElph100HS', u'7z/2014.7z.012', u'7z/2014.7z.012']
2016-12-08 22:46:02,620	4378	139680131815168	b2.api	DEBUG	calling set_thread_pool_size(self=<b2.api.B2Api object at 0x7f09cd33b150>, max_workers=10)
2016-12-08 22:46:02,621	4378	139680131815168	b2.api	DEBUG	calling list_buckets(self=<b2.api.B2Api object at 0x7f09cd33b150>)
2016-12-08 22:46:03,095	4378	139680131815168	b2.account_info.sqlite_account_info	DEBUG	calling refresh_entire_bucket_name_cache(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>) (hidden args: name_id_iterable)
2016-12-08 22:46:03,103	4378	139680131815168	b2.bucket	DEBUG	calling upload_local_file(self=Bucket<ddc6cd824cd8536b5b860e11,CanonElph100HS,allPrivate>, local_file=u'7z/2014.7z.012', file_name=u'7z/2014.7z.012', content_type=None, file_infos={}, sha1_sum=None, min_part_size=None, progress_listener=<b2.progress.TqdmProgressListener object at 0x7f09cd353690>)
2016-12-08 22:46:03,104	4378	139680131815168	b2.bucket	DEBUG	calling upload(self=Bucket<ddc6cd824cd8536b5b860e11,CanonElph100HS,allPrivate>, upload_source=<b2.upload_source.UploadSourceLocalFile object at 0x7f09cd33bb50>, file_name=u'7z/2014.7z.012', content_type=None, file_info={}, min_part_size=None, progress_listener=<b2.progress.TqdmProgressListener object at 0x7f09cd353690>)
2016-12-08 22:46:03,107	4378	139680131815168	b2.bucket	DEBUG	calling list_unfinished_large_files(self=Bucket<ddc6cd824cd8536b5b860e11,CanonElph100HS,allPrivate>, start_file_id=None, batch_size=None)
2016-12-08 22:46:03,230	4378	139680131815168	b2.bucket	DEBUG	calling list_parts(self=Bucket<ddc6cd824cd8536b5b860e11,CanonElph100HS,allPrivate>, file_id=u'4_zddc6cd824cd8536b5b860e11_f20164f96481f05a5_d20161208_m224500_c001_v0001036_t0027', start_part_number=None, batch_size=None)
2016-12-08 22:46:03,232	4378	139680131815168	b2.api	DEBUG	calling list_parts(self=<b2.api.B2Api object at 0x7f09cd33b150>, file_id=u'4_zddc6cd824cd8536b5b860e11_f20164f96481f05a5_d20161208_m224500_c001_v0001036_t0027', start_part_number=None, batch_size=None)
2016-12-08 22:46:03,332	4378	139680131815168	b2.bucket	DEBUG	calling start_large_file(self=Bucket<ddc6cd824cd8536b5b860e11,CanonElph100HS,allPrivate>, file_name=u'7z/2014.7z.012', content_type='b2/x-auto', file_info={})
2016-12-08 22:46:41,696	4378	139679936517888	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:41,761	4378	139679961696000	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:41,827	4378	139679986874112	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,030	4378	139679441610496	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,083	4378	139679944910592	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,166	4378	139679953303296	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,245	4378	139679978481408	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,245	4378	139679970088704	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,253	4378	139679450003200	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:46:42,323	4378	139679433217792	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:51:23,564	4378	139679986874112	b2.bucket	ERROR	error when uploading, upload_url was https://pod-000-1026-14.backblaze.com/b2api/v1/b2_upload_part/4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006/0025
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 515, in _upload_part
    input_stream
  File "build/bdist.linux-x86_64/egg/b2/raw_api.py", line 409, in upload_part
    return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 175, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 102, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 75, in _translate_errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: ('Connection aborted.', error(104, 'Connection reset by peer'))
2016-12-08 22:51:23,570	4378	139679986874112	b2.account_info.upload_url_pool	DEBUG	calling clear_bucket_upload_data(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, bucket_id=u'ddc6cd824cd8536b5b860e11')
2016-12-08 22:51:23,571	4378	139679986874112	b2.account_info.upload_url_pool	DEBUG	calling take_large_file_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f09ce79fed0>, file_id=u'4_zddc6cd824cd8536b5b860e11_f202847f5820a189d_d20161208_m224603_c001_v0001026_t0006')
2016-12-08 22:53:35,850	4378	139680131815168	b2.console_tool	ERROR	ConsoleTool command error
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 896, in run_command
    return command.run(args)
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 823, in run
    progress_listener=progress_listener
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 297, in upload_local_file
    progress_listener=progress_listener
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 348, in upload
    upload_source, file_name, content_type, file_info, progress_listener
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 426, in _upload_large_file
    part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
  File "build/bdist.linux-x86_64/egg/b2/utils.py", line 60, in interruptible_get_result
    return future.result(timeout=1.0)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 501, in _upload_part
    upload_url, upload_auth_token = self._get_upload_part_data(file_id)
  File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 556, in _get_upload_part_data
    response = self.api.session.get_upload_part_url(file_id)
  File "build/bdist.linux-x86_64/egg/b2/session.py", line 38, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/b2/raw_api.py", line 283, in get_upload_part_url
    api_url, 'b2_get_upload_part_url', account_auth_token, fileId=file_id
  File "build/bdist.linux-x86_64/egg/b2/raw_api.py", line 122, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 202, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 175, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 102, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "build/bdist.linux-x86_64/egg/b2/b2http.py", line 75, in _translate_errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: HTTPSConnectionPool(host='api001.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v1/b2_get_upload_part_url (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f09cc18a910>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2016-12-08 22:53:35,869	4378	139680131815168	b2.console_tool	INFO	\\ ========================================  exit=1  ======================================== //
tom@tombuntu-HP-G70:/media/tom/FreeAgent Drive/Images/100 Images/Canon Elph100HS$

**Comment by ppolewicz** [comment]
@kazsulec this looks very much like a connectivity loss between your system and b2 api.

Issue #248 is about slow upload speed with yet unexplained reason.

**Comment by mjurbanski-reef** [comment]
If still occurring with the current version, please reopen this issue.
