### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by clintinthecode** [Backblaze/B2_Command_Line_Tool#260]
Hi,

I had a previous issue on FreeBSD in the past which was discussed over in this issue:
https://github.com/Backblaze/B2_Command_Line_Tool/issues/204

I am now setting up a backup script on Windows and again have had issues with non ascii characters in filenames. if a filename includes a character such as ø it fails with the following output:

```
ERROR:b2.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 40, in run
    self.do_action(bucket, reporter)
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 77, in do_action
    reporter.print_completion('upload ' + self.relative_name)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 81, in print_completion
    self._print_line(message, True)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 130, in _print_line
    self.stdout.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 28: ordinal not in range(128)
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 887, in run_command
    return command.run(args)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 691, in run
    max_workers=max_workers
  File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 221, in sync_folders
    raise CommandError('sync is incomplete')
CommandError: sync is incomplete
ERROR: sync is incomplete
```

**Comment by ppolewicz** [comment]
Ok I am starting to think that graceful handling of failures which come from outputting filenames on the terminal should become a requirement. User should be informed about what happened, but the sync should finish successfully. @bwbeach please confirm that this is the correct approach.

**Comment by bwbeach** [comment]
I agree that the command-line tool needs to have a workaround for this problem.  It's affecting too many people.

**Comment by mjurbanski-reef** [comment]
Fixed in the month following the original report.
