### ISSUE TITLE
Errors only fail once on Windows

### ISSUE THREAD

**Issue by clintinthecode** [Backblaze/B2_Command_Line_Tool#261]
Hi,

Im experiencing an issue where the backup fails, its detailed over in this other issue with url below. The second issue im having, is that the error only happens once when I believe it should happen every single time, and that I think is a bug.

https://github.com/Backblaze/B2_Command_Line_Tool/issues/260

Steps to reproduce:
1. sync a folder on the desktop in windows.
2. put a file in the folder that contains a non ascii character such as ø
3. do a sync, it will fail.
4. do a second sync, it won't fail or give any errors

It should fail every time but it only fails the first time, it technically doesnt succeed either, the files are not synced, but it just doesnt give any errors or fail at all.

To make it fail again i need to rename the file with the ascii character, just add one more character to the filename and run the sync again and it will then fail once until i rename the file.

Shouldn't it be failing every time, as it hasnt yet succeeded and uploaded the file.

**Comment by ppolewicz** [comment]
Please [enable logs](https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/README.md#detailed-logs) and share the resulting file

**Comment by clintinthecode** [comment]
Backup 1, i renamed all 3 test files prior to running this backup

`2016-10-20 08:49:36,213	6288	15532	b2.console_tool	INFO	// ========================================  0.6.8   ======================================== \\
2016-10-20 08:49:36,213	6288	15532	b2.console_tool	DEBUG	platform is Windows-7-6.1.7601-SP1
2016-10-20 08:49:36,213	6288	15532	b2.console_tool	DEBUG	Python version is CPython 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
2016-10-20 08:49:36,213	6288	15532	b2.console_tool	DEBUG	locale is ('en_AU', 'cp1252')
2016-10-20 08:49:36,213	6288	15532	b2.console_tool	DEBUG	filesystem encoding is mbcs
2016-10-20 08:49:36,213	6288	15532	b2.console_tool	INFO	starting command [b2.console_tool.Sync] with arguments: [u'C:\\Python27\\Scripts\\b2-script.py', u'sync', u'--replaceNewer', u'--debugLogs', u'C:\\Users\\Clint\\Desktop\\BRiN', u'b2://jeffreys-computer']
2016-10-20 08:49:36,213	6288	15532	b2.api	DEBUG	calling set_thread_pool_size(self=<b2.api.B2Api object at 0x01C0E190>, max_workers=10)
2016-10-20 08:49:36,213	6288	15532	b2.api	DEBUG	calling list_buckets(self=<b2.api.B2Api object at 0x01C0E190>)
2016-10-20 08:49:37,869	6288	15532	b2.account_info.sqlite_account_info	DEBUG	calling refresh_entire_bucket_name_cache(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>) (hidden args: name_id_iterable)
2016-10-20 08:49:37,885	6288	15532	b2.sync.sync	DEBUG	calling sync_folders(source_folder=LocalFolder(C:\Users\Clint\Desktop\BRiN), dest_folder=<b2.sync.folder.B2Folder object at 0x0270FDB0>, args=Arguments({'compareVersions': None, 'debugLogs': True, 'delete': False, 'destination': u'b2://jeffreys-computer', 'excludeRegex': [], 'includeRegex': [], 'keepDays': None, 'logConfig': None, 'noProgress': False, 'replaceNewer': True, 'skipNewer': False, 'source': u'C:\\Users\\Clint\\Desktop\\BRiN', 'threads': None}), now_millis=1476917377886L, stdout=<open file '<stdout>', mode 'w' at 0x0128D078>, no_progress=False, max_workers=10)
2016-10-20 08:49:37,885	6288	15532	b2.bucket	DEBUG	calling ls(self=Bucket<66e2b44b5258d0be507d041a,jeffreys-computer,allPrivate>, folder_to_list='', show_versions=True, recursive=True, fetch_count=1000, max_entries=None)
2016-10-20 08:49:38,338	6288	16356	b2.bucket	DEBUG	calling upload(self=Bucket<66e2b44b5258d0be507d041a,jeffreys-computer,allPrivate>, upload_source=<b2.upload_source.UploadSourceLocalFile object at 0x0273BA10>, file_name=u'@echo fs2dhkggfffgoff \xf8.txt', file_info={'src_last_modified_millis': '1476856353061'}, progress_listener=<b2.sync.report.SyncFileReporter object at 0x0273BB50>, content_type=None, min_part_size=None)
2016-10-20 08:49:38,354	6288	16364	b2.bucket	DEBUG	calling upload(self=Bucket<66e2b44b5258d0be507d041a,jeffreys-computer,allPrivate>, upload_source=<b2.upload_source.UploadSourceLocalFile object at 0x02893450>, file_name=u'@echo off \xf8@ec2sdfho fxgoff \xf8.txt', file_info={'src_last_modified_millis': '1476856801728'}, progress_listener=<b2.sync.report.SyncFileReporter object at 0x02893490>, content_type=None, min_part_size=None)
2016-10-20 08:49:38,354	6288	16372	b2.account_info.upload_url_pool	DEBUG	calling take_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a')
2016-10-20 08:49:38,369	6288	16360	b2.bucket	DEBUG	calling upload(self=Bucket<66e2b44b5258d0be507d041a,jeffreys-computer,allPrivate>, upload_source=<b2.upload_source.UploadSourceLocalFile object at 0x02893770>, file_name=u'qwedsf2grty.txt', file_info={'src_last_modified_millis': '1476856784603'}, progress_listener=<b2.sync.report.SyncFileReporter object at 0x028939B0>, content_type=None, min_part_size=None)
2016-10-20 08:49:38,369	6288	12328	b2.account_info.upload_url_pool	DEBUG	calling take_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a')
2016-10-20 08:49:38,369	6288	16368	b2.account_info.upload_url_pool	DEBUG	calling take_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a')
2016-10-20 08:49:40,401	6288	16372	b2.account_info.upload_url_pool	DEBUG	calling put_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a') (hidden args: upload_url, upload_auth_token)
2016-10-20 08:49:40,401	6288	16356	b2.sync.action	ERROR	an exception occurred in a sync action
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 40, in run
    self.do_action(bucket, reporter)
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 77, in do_action
    reporter.print_completion('upload ' + self.relative_name)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 81, in print_completion
    self._print_line(message, True)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 130, in _print_line
    self.stdout.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 29: ordinal not in range(128)
2016-10-20 08:49:40,854	6288	12328	b2.account_info.upload_url_pool	DEBUG	calling put_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a') (hidden args: upload_url, upload_auth_token)
2016-10-20 08:49:40,854	6288	16364	b2.sync.action	ERROR	an exception occurred in a sync action
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 40, in run
    self.do_action(bucket, reporter)
  File "c:\python27\lib\site-packages\b2\sync\action.py", line 77, in do_action
    reporter.print_completion('upload ' + self.relative_name)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 81, in print_completion
    self._print_line(message, True)
  File "c:\python27\lib\site-packages\b2\sync\report.py", line 130, in _print_line
    self.stdout.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 17: ordinal not in range(128)
2016-10-20 08:49:46,697	6288	16368	b2.account_info.upload_url_pool	DEBUG	calling put_bucket_upload_url(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C02CF0>, bucket_id=u'66e2b44b5258d0be507d041a') (hidden args: upload_url, upload_auth_token)
2016-10-20 08:49:46,760	6288	15532	b2.console_tool	ERROR	ConsoleTool command error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 887, in run_command
    return command.run(args)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 691, in run
    max_workers=max_workers
  File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 221, in sync_folders
    raise CommandError('sync is incomplete')
CommandError: sync is incomplete
2016-10-20 08:49:46,760	6288	15532	b2.console_tool	INFO	\\ ========================================  exit=1  ======================================== //
`

**Comment by clintinthecode** [comment]
Backup 2: same 3 files still exist unchanged, 2 of them have non ascii characters in the filename which caused the crash on Backup 1, whereas running a second time it doesnt crash, but also doesnt upload them...

``2016-10-20 08:52:18,197	16364	15804	b2.console_tool	INFO	// ========================================  0.6.8   ======================================== \\
2016-10-20 08:52:18,197	16364	15804	b2.console_tool	DEBUG	platform is Windows-7-6.1.7601-SP1
2016-10-20 08:52:18,197	16364	15804	b2.console_tool	DEBUG	Python version is CPython 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
2016-10-20 08:52:18,197	16364	15804	b2.console_tool	DEBUG	locale is ('en_AU', 'cp1252')
2016-10-20 08:52:18,197	16364	15804	b2.console_tool	DEBUG	filesystem encoding is mbcs
2016-10-20 08:52:18,197	16364	15804	b2.console_tool	INFO	starting command [b2.console_tool.Sync] with arguments: [u'C:\\Python27\\Scripts\\b2-script.py', u'sync', u'--replaceNewer', u'--debugLogs', u'C:\\Users\\Clint\\Desktop\\BRiN', u'b2://jeffreys-computer']
2016-10-20 08:52:18,197	16364	15804	b2.api	DEBUG	calling set_thread_pool_size(self=<b2.api.B2Api object at 0x01C2C170>, max_workers=10)
2016-10-20 08:52:18,197	16364	15804	b2.api	DEBUG	calling list_buckets(self=<b2.api.B2Api object at 0x01C2C170>)
2016-10-20 08:52:19,697	16364	15804	b2.account_info.sqlite_account_info	DEBUG	calling refresh_entire_bucket_name_cache(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x01C1FCD0>) (hidden args: name_id_iterable)
2016-10-20 08:52:19,713	16364	15804	b2.sync.sync	DEBUG	calling sync_folders(source_folder=LocalFolder(C:\Users\Clint\Desktop\BRiN), dest_folder=<b2.sync.folder.B2Folder object at 0x027E5D90>, args=Arguments({'compareVersions': None, 'debugLogs': True, 'delete': False, 'destination': u'b2://jeffreys-computer', 'excludeRegex': [], 'includeRegex': [], 'keepDays': None, 'logConfig': None, 'noProgress': False, 'replaceNewer': True, 'skipNewer': False, 'source': u'C:\\Users\\Clint\\Desktop\\BRiN', 'threads': None}), now_millis=1476917539714L, stdout=<open file '<stdout>', mode 'w' at 0x012CD078>, no_progress=False, max_workers=10)
2016-10-20 08:52:19,713	16364	15804	b2.bucket	DEBUG	calling ls(self=Bucket<66e2b44b5258d0be507d041a,jeffreys-computer,allPrivate>, folder_to_list='', show_versions=True, recursive=True, fetch_count=1000, max_entries=None)
2016-10-20 08:52:20,167	16364	15804	b2.console_tool	INFO	\\ ========================================  exit=0  ======================================== //

**Comment by ppolewicz** [comment]
It would seem that the first sync was actually a success (otherwise `put_bucket_upload_url` would not be called)... After the file was uploaded, however, b2 CLI tried to print a console message, but that message contained a file name which could not be printed on the given terminal (due to how it was configured). That is why during the second sync all files matched on both sides and sync had nothing to do, so it completed successfully.

I think what happened here is expected behavior (though #260 is a different story). @clintinthecode if you agree, please close this issue.

**Comment by clintinthecode** [comment]
Ahhh I see you are correct. I checked in the bucket yesterday and was only one file there, however i forgot to do a hard refresh to check for new files. today its showing the files (the website doesnt do too well for displaying recently uploaded files, i often need to do a hard refresh or log out and log back in to view new files, but thats a different topic)
