### ISSUE TITLE
Can't able to login via terminal. 

### ISSUE THREAD

**Issue by sureshpeters** [Backblaze/B2_Command_Line_Tool#271]
I'm using mac terminal to log into the b2 cloud. The command I used for the authorization is, 

```
b2 authorize_account [<accountId>]
```

That authorization command gives me this error

```
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.6.8', 'console_scripts', 'b2')()
  File "/Library/Python/2.7/site-packages/b2/console_tool.py", line 996, in main
    exit_status = ct.run_command(decoded_argv)
  File "/Library/Python/2.7/site-packages/b2/console_tool.py", line 884, in run_command
    self._setup_logging(args, command, argv)
  File "/Library/Python/2.7/site-packages/b2/console_tool.py", line 969, in _setup_logging
    logger.debug('locale is %s', locale.getdefaultlocale())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

Can anyone help me in this? 
Thanks

**Comment by ppolewicz** [comment]
It would seem that your terminal is configured in a way which is not supported by python. I suspect you have `export LC_ALL=UTF-8` somewhere in `.bashrc` or `.bash_profile`?
