### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-107: ordinal not in range(128)

### ISSUE THREAD

**Issue by ender9441** [Backblaze/B2_Command_Line_Tool#272]
```
[22:02 root@us0101anf005 ~]$ cat /etc/redhat-release
CentOS release 6.5 (Final)
[22:07 root@us0101anf005 ~]$ python --version
Python 2.6.6
```

I installed b2 like this...

```
git clone https://github.com/Backblaze/B2_Command_Line_Tool.git
cd B2_Command_Line_Tool
python setup.py install
```

I get errors uploading a simple file...

```
b2 upload_file dbops-mysql-backup test.txt test.txt
```

If the file is empty, it will upload...

```
URL by file name: https://f001.backblazeb2.com/file/dbops-mysql-backup/test.txt
URL by fileId: https://f001.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=4_z92fc1393117294535d6d0b16_f11219b30b955ac46_d20161026_m220157_c001_v0001032_t0041
{
"action": "upload",
"fileId": "4_z92fc1393117294535d6d0b16_f11219b30b955ac46_d20161026_m220157_c001_v0001032_t0041",
"fileName": "test.txt",
"size": 0,
"uploadTimestamp": 1477519317000
}
```

...but if I put any data in the file, it will error. The file is uploaded, but this error is displayed.  The entire contents of the file is "ben"...

```
Traceback (most recent call last):
File "/usr/bin/b2", line 9, in <module>
load_entry_point('b2==0.6.9', 'console_scripts', 'b2')()
File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 996, in main
File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 887, in run_command
File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 814, in run
File "/usr/lib/python2.6/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
return function(*wrapee_args, **wrapee_kwargs)
File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 292, in upload_local_file
File "/usr/lib/python2.6/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
return function(*wrapee_args, **wrapee_kwargs)
File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 340, in upload
File "/usr/lib/python2.6/site-packages/futures-3.0.5-py2.6.egg/concurrent/futures/_base.py", line 405, in result
return self.__get_result()
File "/usr/lib/python2.6/site-packages/futures-3.0.5-py2.6.egg/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "build/bdist.linux-x86_64/egg/b2/bucket.py", line 367, in _upload_small_file
File "build/bdist.linux-x86_64/egg/b2/progress.py", line 98, in close
File "build/bdist.linux-x86_64/egg/tqdm/_tqdm.py", line 894, in close
File "build/bdist.linux-x86_64/egg/tqdm/_tqdm.py", line 117, in print_status
File "build/bdist.linux-x86_64/egg/tqdm/_tqdm.py", line 110, in fp_write
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-107: ordinal not in range(128)
```

**Comment by ppolewicz** [comment]
Which version of tqdm do you have?

Could you please add the `--debugLogs` flag and share the log?

**Comment by ppolewicz** [comment]
I think I know what it is, but lets wait for the logs.

**Comment by ender9441** [comment]
[04:32 root@us0101anf005 ~]$ tqdm --version
4.8.4


[b2_cli.txt](https://github.com/Backblaze/B2_Command_Line_Tool/files/557573/b2_cli.txt)

**Comment by ppolewicz** [comment]
Does the absolute path to the file which you upload contain any weird characters?

**Comment by ender9441** [comment]
The file is in /root/

**Comment by ppolewicz** [comment]
I don't know why this happens yet, but I think you could try `--noProgress` as a workaround. Please keep an eye on this thread, we need to investigate it and fix it.

**Comment by ender9441** [comment]
--noProgess is working.  Thanks.

I'll watch for the fix.

**Comment by bwbeach** [comment]
@nilayp has reproduced the problem in a VM that we can experiment in.  

    [brianb@localhost ~]$ tqdm --version
    4.9.0
    [brianb@localhost ~]$ echo $LANG
    en_US.UTF-8

The backtrace is similar:

      File "/usr/lib/python2.6/site-packages/tqdm/_tqdm.py", line 195, in print_status
        fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
      File "/usr/lib/python2.6/site-packages/tqdm/_tqdm.py", line 188, in fp_write
        fp.write(_unicode(s))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u258e' in position 20: ordinal not in range(128)

A similar error is produced by doing this:

```
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print u'\u8175'
腵
>>> import sys
>>> sys.stdout.write(u'\u8175')  # I think this error is expected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u8175' in position 0: ordinal not in range(128)
>>> u'\u8175'.encode('utf-8')
'\xe8\x85\xb5'
>>> sys.stdout.write(u'\u8175'.encode('utf-8') + '\n')
腵
>>> 
```

I need to think about this.  I keep getting confused by I/O in Python.

**Comment by bwbeach** [comment]
I'm going to claim that tqdm doesn't work on 2.6 because it's trying to write a unicode to stderr.

On my macbook, this is what happens in Python 2.7:

```
(p27)stone:~ brianb$ echo $LANG
en_US.UTF-8
(p27)stone:~ brianb$ python
Python 2.7.12 (default, Aug  8 2016, 10:53:11) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> sys.stdout.encoding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sys' is not defined
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
>>> sys.stdout.write(u'\u8175\n')
腵
```

And this is what happens on Python 2.6:

```
(p26)stone:~ brianb$ python
Python 2.6.9 (unknown, Mar  7 2016, 10:48:33) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'UTF-8'
>>> sys.stdout.write(u'\u8175\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u8175' in position 0: ordinal not in range(128)
```

The tqdm code in the close method is clearly trying to write a unicode object.  This code remains in the master branch of `tqdm/tqdm`:

```
        def fp_write(s):
            fp.write(_unicode(s))
            fp_flush()
```

**Comment by bwbeach** [comment]
https://github.com/tqdm/tqdm/issues/127

**Comment by ppolewicz** [comment]
Did this work properly on 2.6 with an older version of tqdm? Can you identify which version started failing, so that we can set up dependencies properly and imply `--noProgress` if a bad version and 2.6 is detected?

**Comment by bwbeach** [comment]
I don't know that this ever worked on 2.6.

**Comment by ppolewicz** [comment]
Then we could just imply `--noProgress` if python version is 2.6. It is weird though, that nobody reported it earlier...

**Comment by bwbeach** [comment]
Or fall back to the simple non-tqdm progress reporting.
