### ISSUE TITLE
Initial setup Unable to authorize account

### ISSUE THREAD

**Issue by snoby** [Backblaze/B2_Command_Line_Tool#313]
Hi,
BackBlaze support has sent me here to report this error.  I'm attempting just to setup the B2_Command_Line_Tool, however I'm getting an unknown error.

```
snoby@heavy:~/backblaz3$ b2 authorize_account 5c94xxxxx7bd
Using https://api.backblazeb2.com
Backblaze application key:
ERROR: unable to authorize account: Unknown error: AttributeError("'Extensions' object has no attribute 'get_extension_for_class'",)
```

I installed the app via pip install on ubuntu 15.10

**Comment by ppolewicz** [comment]
Please run `pip freeze` and show us the result. It looks like one of our dependencies has become incompatible.

Please also run the failing command with `--debugLogs` flag and share the resulting b2_cli.log file. Hopefully it will show the full stacktrace and pinpoint the fault.

**Comment by snoby** [comment]
Pip Freeze:
```
snoby@heavy:~$ sudo pip freeze
ansible==2.2.0.0
arrow==0.10.0
b2==0.7.0
beautifulsoup4==4.3.2
cffi==1.1.2
cfscrape==1.6.8
characteristic==14.3.0
chardet==2.3.0
Cheetah==2.4.4
colorama==0.3.3
configobj==5.0.6
cryptography==1.0.1
dnspython==1.12.0
enum34==1.0.4
funcsigs==1.0.2
futures==3.0.5
html5lib==0.999
idna==2.0
iniparse==0.4
iotop==0.6
ipaddress==1.0.14
Js2Py==0.41
Landscape-Client==14.12
libvirt-python==1.2.15
logfury==0.1.2
lxml==3.4.4
mercurial==3.4
ndg-httpsclient==0.4.0
PAM==0.4.2
ply==3.7
putlocker==1.3
pyasn1==0.1.8
pyasn1-modules==0.0.7
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.1
pyjsparser==2.4.5
pyliblzma==0.5.3
pyOpenSSL==0.15.1
pyserial==2.7
pysqlite==1.0.1
python-apt==1.0.1+ubuntu0.1
python-dateutil==2.6.0
pytz==2016.10
requests==2.12.4
rpm-python==4.12.0.1
service-identity==14.0.0
six==1.10.0
tqdm==4.11.0
Twisted-Core==15.2.1
tzlocal==1.3
update==0.4.4
urlgrabber==3.9.1
urllib3==1.11
urwid==1.2.1
vboxapi==1.0
yum-metadata-parser==1.1.4
zope.interface==4.1.2
```
logs:
I was not able to enable "debugLogs"
```
snoby@heavy:~$ b2 --debugLogs=1  authorize_account 5c94xxxxx7bd  001ba0a3318xxxxxxxxxxxxx275fa89aac57a
This program provides command-line access to the B2 service.

Usages:

    b2 authorize-account [<accountId>] [<applicationKey>]
    b2 cancel-all-unfinished-large-files <bucketName>
    b2 cancel-large-file <fileId>
    b2 clear-account
    b2 create-bucket [--bucketInfo <json>] [--lifecycleRules <json>] <bucketName> [allPublic | allPrivate]
    b2 delete-bucket <bucketName>
    b2 delete-file-version [<fileName>] <fileId>
    b2 download-file-by-id [--noProgress] <fileId> <localFileName>
    b2 download-file-by-name [--noProgress] <bucketName> <fileName> <localFileName>
    b2 get-account-info
    b2 get-bucket <bucketName>
    b2 get-download-auth [--prefix <fileNamePrefix>] [--duration <durationInSeconds>] <bucketName>
    b2 get-file-info <fileId>
    b2 help [commandName]
    b2 hide-file <bucketName> <fileName>
    b2 list-buckets
    b2 list-file-names <bucketName> [<startFileName>] [<maxToShow>]
    b2 list-file-versions <bucketName> [<startFileName>] [<startFileId>] [<maxToShow>]
    b2 list-parts <largeFileId>
    b2 list-unfinished-large-files <bucketName>
    b2 ls [--long] [--versions] <bucketName> [<folderName>]
    b2 make-url <fileId>
    b2 sync [--delete] [--keepDays N] [--skipNewer] [--replaceNewer] \
        [--compareVersions <option>] [--threads N] [--noProgress] \
        [--excludeRegex <regex> [--includeRegex <regex>]] [--dryRun] \
        <source> <destination>
    b2 update-bucket [--bucketInfo <json>] [--lifecycleRules <json>] <bucketName> [allPublic | allPrivate]
    b2 upload-file [--sha1 <sha1sum>] [--contentType <contentType>] \
        [--info <key>=<value>]* [--minPartSize N] \
        [--noProgress] [--threads N] <bucketName> <localFilePath> <b2FileName>
    b2 version
```
snoby@heavy:~$ b2 version
b2 command line tool, version 0.7.0

**Comment by snoby** [comment]
Also I tried to use rclone with the B2 cloud service and it works fine... So nothing wrong with the creds or token key.

**Comment by svonohr** [comment]
> I was not able to enable "debugLogs"

Try: `b2 authorize_account --debugLogs [<accountId>] [<applicationKey>]`

**Comment by snoby** [comment]
Ah there we go:
```
2017-01-17 20:10:05,543 25264   140128248293120 b2.console_tool INFO    // ========================================  0.7.0   ======================================== \\
2017-01-17 20:10:05,544 25264   140128248293120 b2.console_tool DEBUG   platform is Linux-4.2.0-42-generic-x86_64-with-Ubuntu-15.10-wily
2017-01-17 20:10:05,544 25264   140128248293120 b2.console_tool DEBUG   Python version is CPython 2.7.10 (default, Oct 14 2015, 16:09:02)  [GCC 5.2.1 20151010]
2017-01-17 20:10:05,544 25264   140128248293120 b2.console_tool DEBUG   locale is ('en_US', 'UTF-8')
2017-01-17 20:10:05,544 25264   140128248293120 b2.console_tool DEBUG   filesystem encoding is UTF-8
2017-01-17 20:10:05,544 25264   140128248293120 b2.console_tool INFO    starting command [b2.console_tool.AuthorizeAccount] (arguments hidden)
2017-01-17 20:10:05,545 25264   140128248293120 b2.api  DEBUG   calling authorize_account(self=<b2.api.B2Api object at 0x7f7221931710>, realm='production') (hidden args: account_id, application_key)
2017-01-17 20:10:05,545 25264   140128248293120 b2.account_info.sqlite_account_info     ERROR   _get_account_info_or_raise encountered a problem while trying to retrieve "account_id"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/account_info/sqlite_account_info.py", line 214, in _get_account_info_or_raise
    value = cursor.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2017-01-17 20:10:05,546 25264   140128248293120 b2.account_info.sqlite_account_info     DEBUG   calling refresh_entire_bucket_name_cache(self=<b2.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7f7224372cd0>) (hidden args: name_id_iterable)
2017-01-17 20:10:05,871 25264   140128248293120 b2.b2http       ERROR   _translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 47, in _translate_errors
    response = fcn()
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 255, in do_post
    response = self.session.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
2017-01-17 20:10:05,879 25264   140128248293120 b2.console_tool ERROR   ConsoleTool account authorization error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 219, in run
    self.api.authorize_account(realm, args.accountId, args.applicationKey)
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/api.py", line 124, in authorize_account
    response = self.raw_api.authorize_account(realm_url, account_id, application_key)
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 139, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 135, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 286, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 259, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 103, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 83, in _translate_errors
    raise UnknownError(repr(e))
UnknownError: Unknown error: AttributeError("'Extensions' object has no attribute 'get_extension_for_class'",)
2017-01-17 20:10:05,882 25264   140128248293120 b2.console_tool INFO    \\ ========================================  exit=1  ======================================== //
snoby@heavy:~$
```

**Comment by ppolewicz** [comment]
https://github.com/kennethreitz/requests/issues/3710

Please run `pip install --upgrade cryptography`

**Comment by dtruel** [comment]
I have this problem too.  running that command did not fix it.

**Comment by ppolewicz** [comment]
@dtruel run `pip freeze` and show us the results please

**Comment by retorquere** [comment]
I've also tried `curl https://api.backblazeb2.com/b2api/v2/b2_authorize_account -u "ACCOUNT_ID:APPLICATION_KEY"` as per https://www.backblaze.com/b2/docs/b2_authorize_account.html and I'm getting

```
{
  "code": "unauthorized",
  "message": "",
  "status": 401
}
```

**Comment by ppolewicz** [comment]
@retorquere it is clear from your second message that the issue is not CLI-specific. You should contact b2 support.

**Comment by dtruel** [comment]
@ppolewicz I have determined that my issue is also not CLI-specific. It's weird.
