### ISSUE TITLE
CLI Sync errors

### ISSUE THREAD

**Issue by KaiThoelen** [Backblaze/B2_Command_Line_Tool#331]
Hi all,
after i finished my first sync to Cloud after 3 weeks, i have now errors while syncing new files to the Cloud.

The following lines occurs after a few seconds when i start my CLI Command
```
C:\Program Files\Python36\Scripts>b2.exe sync --excludeRegex DfsrPrivate --threads 10 --keepDays 30 --replaceNewer \\?\D:\DFS\Daten b2://Nuernberg01/Daten

ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\b2-script.py", line 11, in <module>
    load_entry_point('b2==0.7.0', 'console_scripts', 'b2')()
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 1104, in main
    exit_status = ct.run_command(decoded_argv)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError
```
I have no Idea what to do?

**Comment by KaiThoelen** [comment]
Command is, using Extension \\?\ for long path
b2.exe sync --excludeRegex DfsrPrivate --threads 10 --keepDays 30 --replaceNewer \\?\D:\DFS\Daten b2://Nuernberg01/Daten

using --excludeRegex DfsrPrivate, because we sync also via DFS to local backup server

**Comment by ppolewicz** [comment]
@bwbeach https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/b2/sync/policy.py#L254 looks like a server-side issue

**Comment by weed-** [comment]
Exactly the same issue here, sync update has completely stopped. Any solutions?

My command line:
`b2 sync --excludeRegex DfsrPrivate --threads 5 --keepDays 10 --replaceNewer "\\?\D:\here-is-a-very-long-path\folder" "b2://BUCKETNAME/here-is-a-very-long-path/folder"`

My error:
```
ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\b2-script.py", line 11, in <module>
    load_entry_point('b2==0.7.0', 'console_scripts', 'b2')()
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 1104, in main
    exit_status = ct.run_command(decoded_argv)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError
```

**Comment by bwbeach** [comment]
Sorry for the delay.  My son is visiting this week, and we've been doing a lot of hiking.

Yep.  Looks like a server-side problem.  I'll work on tracking it down today.

If anybody is willing to share a bucketId, that could help track down the issue.  (Thanks in advance.)

**Comment by KaiThoelen** [comment]
update and try again, without succes

C:\Program Files\Python36\Scripts>pip install b2
Requirement already satisfied: b2 in c:\program files\python36\lib\site-packages
Requirement already satisfied: arrow>=0.8.0 in c:\program files\python36\lib\site-packages (from b2)
Requirement already satisfied: logfury>=0.1.2 in c:\program files\python36\lib\site-packages (from b2)
Requirement already satisfied: requests>=2.9.1 in c:\program files\python36\lib\site-packages (from b2)
Requirement already satisfied: six>=1.10 in c:\program files\python36\lib\site-packages (from b2)
Requirement already satisfied: tqdm>=4.5.0 in c:\program files\python36\lib\site-packages (from b2)
Requirement already satisfied: python-dateutil in c:\program files\python36\lib\site-packages (from arrow>=0.8.0->b2)
Requirement already satisfied: funcsigs in c:\program files\python36\lib\site-packages (from logfury>=0.1.2->b2)

C:\Program Files\Python36\Scripts>b2 sync --excludeRegex DfsrPrivate --threads 5 --keepDays 30 --replaceNewer \\?\D:\DFS\Daten b2://Nuernberg01/Daten

ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\b2-script.py", line 11, in <module>
    load_entry_point('b2==0.7.0', 'console_scripts', 'b2')()
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 1104, in main
    exit_status = ct.run_command(decoded_argv)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 992, in run_command
    return command.run(args)
  File "c:\program files\python36\lib\site-packages\b2\console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "c:\program files\python36\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 150, in make_folder_sync_actions
    sync_type, source_file, dest_file, source_folder, dest_folder, args, now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\sync.py", line 106, in make_file_sync_actions
    for action in policy.get_all_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 104, in get_all_actions
    for action in self._get_hide_delete_actions():
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 177, in _get_hide_delete_actions
    self._keepDays, self._now_millis
  File "c:\program files\python36\lib\site-packages\b2\sync\policy.py", line 254, in make_b2_keep_days_actions
    assert prev_age_days is None or prev_age_days <= age_days
AssertionError

**Comment by ppolewicz** [comment]
@KaiThoelen `pip install -U b2`

**Comment by KaiThoelen** [comment]
well done, upload starts again. Many thanks for you help

upgrade to python v3.61
upgrade b2 with option -U above

**Comment by weed-** [comment]
Works for me, too. Thanks Paweł!
