### ISSUE TITLE
Missing characters when syncing root

### ISSUE THREAD

**Issue by BobVul** [Backblaze/B2_Command_Line_Tool#334]
With an attempt at syncing root, e.g. `b2 sync / b2://foo/bar`, a character is missing in the path resulting in errors such as:

```
OSError: [Errno 2] No such file or directory: '/in/bash'
```

Which somehow found `/in/bash` instead of `/bin/bash`.

I believe this is because the attempt at calculating prefix length in [folder.py:79](https://github.com/Backblaze/B2_Command_Line_Tool/blob/0308d37e5cc92765064118b38abccd35351bfd11/b2/sync/folder.py#L79) fails to take into account the root path `/`, where there is no _trailing_ slash as such.

A quick fix might be to special-case root, but to be honest the whole prefix calculation looks pretty fragile.

**Comment by ppolewicz** [comment]
I see that you have analysed it pretty well already. Would you take a shot at suggesting a fix for this issue?

We encourage outside contributors to perform changes on our codebase. Many such changes have been merged already. In order to make it easier to contribute, core developers of this project:

* provide guidance (through the issue reporting system)
* provide tool assisted code review (through the Pull Request system)
* maintain a set of integration tests (run with a production cloud)
* maintain a set of (well over a hundred) unit tests
* automatically run unit tests on 14 versions of python (including osx, Jython and pypy)
* format the code automatically using [yapf](https://github.com/google/yapf)
* use static code analysis to find subtle/potential issues with maintainability
* maintain other Continous Integration tools (coverage tracker)

**Comment by Elusive138** [comment]
If we can make the assumption that this is only for slash-only paths (i.e. root and paths that collapse down to root), a basic fix might be to replace that line with:

```
prefix_len = len(self.root)
path_chars = set(self.root)
if len(path_chars) > 0 and path_chars != set('/'):
    prefix_len += 1 # when path contains more than just `/`, include trailing '/' in prefix length, see issue #334
```

But I'm not sure just how *safe* such a change would be, therefore I'm a bit hesitant with this.

For the time being, I think I'll be looking at rclone - I don't really have time to worry about B2 CLI reliability right now.


Just for completeness, here's the full stack trace

```
# b2 sync --dryRun / b2://foo/bar
ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 992, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 136, in make_folder_sync_actions
    dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions, inclusions):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 74, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 48, in _filter_folder
    for f in folder.all_files(reporter):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 81, in all_files
    yield self._make_file(relative_path)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 166, in _make_file
    mod_time = int(round(os.path.getmtime(full_path) * 1000))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/in/bash'
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.7.2', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1104, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 992, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 781, in run
    dry_run=args.dryRun,
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 251, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 136, in make_folder_sync_actions
    dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions, inclusions):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 74, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 48, in _filter_folder
    for f in folder.all_files(reporter):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 81, in all_files
    yield self._make_file(relative_path)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 166, in _make_file
    mod_time = int(round(os.path.getmtime(full_path) * 1000))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/in/bash'
```
