### ISSUE TITLE
Filename causes failure?

### ISSUE THREAD

**Issue by glennbugreporting** [Backblaze/B2_Command_Line_Tool#365]
First time using b2 at the command line, and received this error at the end of what I believe was a successful sync. I did the export LANG suggestion and ran sync again and same results.

WARNING: /usr/www/80211n/im could not be accessed (broken symlink?)                
WARNING: /usr/www/bw-archives/mt4 could not be accessed (broken symlink?)
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 1009, in run_command
    return command.run(args)
  File "build/bdist.linux-x86_64/egg/b2/console_tool.py", line 798, in run
    dry_run=args.dryRun,
  File "/usr/lib/python2.7/site-packages/logfury-0.1.2-py2.7.egg/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 250, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 135, in make_folder_sync_actions
    dest_file) in zip_folders(source_folder, dest_folder, reporter, exclusions, inclusions):
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 82, in zip_folders
    current_a = next_or_none(iter_a)
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "build/bdist.linux-x86_64/egg/b2/sync/sync.py", line 48, in _filter_folder
    for f in folder.all_files(reporter):
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 80, in all_files
    for relative_path in self._walk_relative_paths(prefix_len, self.root, reporter):
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 142, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 142, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 142, in _walk_relative_paths
    for rp in self._walk_relative_paths(prefix_len, full_path, reporter):
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 116, in _walk_relative_paths
    name = self._handle_non_unicode_file_name(name)
  File "build/bdist.linux-x86_64/egg/b2/sync/folder.py", line 162, in _handle_non_unicode_file_name
    raise EnvironmentEncodingError(repr(name), sys.getfilesystemencoding())
EnvironmentEncodingError: file name 'a_head_style_Glenn\xd4sMachines.gif' cannot be decoded with system encoding (UTF-8).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8
ERROR: file name 'a_head_style_Glenn\xd4sMachines.gif' cannot be decoded with system encoding (UTF-8).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8

**Comment by svonohr** [comment]
The `export LANG=en_US.UTF-8` was just an example of how to change the encoding that b2 is going to use for reading your filenames. On linux filenames have no standard enconding and are just a sequence of bytes.

Your filename contains the byte 0xD4 which is the start of a valid UTF8 sequence, but it needs to be followed by a byte which has the upper bit set. So your filename appears not to be a valid UTF8 encoded string. Your filename might be something like ISO 8859-1 where 0xD4 represents a Ô, but this also seems wrong. 

You should check how you ended up with this file and what the correct encoding for this filename is. For use with b2 you need to make sure that all files that you are going to sync use the same encoding.

**Comment by glennbugreporting** [comment]
Ah! That makes perfect sense. These are some old archived files that aren’t in use and have probably transferred over multiple platforms across 15 years or more, causing a UTF encoding error along the way. I'll fix the file names individually.
