### ISSUE TITLE
When attempting to mount error occurs

### ISSUE THREAD

**Issue by jeremybrown82** [Backblaze/B2_Command_Line_Tool#409]
Running clean install of ubuntu 14.04 and followed instructions exactly.

jeremybrown82@s125553:/etc/b2fuse$ python /etc/b2fuse/b2fuse.py /mnt/b2fuse-mount
```pytb
Traceback (most recent call last):
File "/etc/b2fuse/b2fuse.py", line 32, in 
    from b2fuse_main import B2Fuse
File "/etc/b2fuse/b2fuse_main.py", line 37, in 
    from b2.api import B2Api
File "/usr/local/lib/python2.7/dist-packages/b2/api.py", line 15, in 
    from .b2http import B2Http
File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 13, in 
    import arrow
File "/usr/local/lib/python2.7/dist-packages/arrow/init.py", line 3, in 
    from .arrow import Arrow
File "/usr/local/lib/python2.7/dist-packages/arrow/arrow.py", line 19, in 
    from arrow import util, locales, parser, formatter
File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 12, in 
    from backports.functools_lru_cache import lru_cache # pragma: no cover
ImportError: No module named backports.functools_lru_cache
```

**Comment by ppolewicz** [comment]
you are using a buggy version of `arrow`. Try `pip install -U arrow` to fix it.

**Comment by bwbeach** [comment]
Closing.  Please re-open if suggested fix does not work.
