### ISSUE TITLE
ValueError syncing from remote to local

### ISSUE THREAD

**Issue by snorrelo** [Backblaze/B2_Command_Line_Tool#51]
I was just testing syncing from b2 to local filesystem and got an ValueError:
ValueError: unknown url type

```
host1:B2_Command_Line_Tool user1$ git pull -v
From https://github.com/Backblaze/B2_Command_Line_Tool
 = [up to date]      master     -> origin/master
Already up-to-date.
host1:B2_Command_Line_Tool user1$ ./b2 version
b2 command line tool, version 0.3.11
host1:B2_Command_Line_Tool user1$ ./b2 create_bucket testtemp allPrivate
040e479d4f5c932b5f26011c
host1:B2_Command_Line_Tool user1$ ./b2 sync ./tmp-upload/ b2:testtemp/test/
+ test1.bin
./tmp-upload/test1.bin
     32%
    DONE.
+ test10.bin
./tmp-upload/test10.bin
     5%
     18%
     40%
     48%
     61%
     76%
     90%
     96%
    DONE.
+ test5.bin
./tmp-upload/test5.bin
     10%
     26%
     37%
     59%
     84%
    DONE.
host1:B2_Command_Line_Tool user1$ ./b2 sync b2:testtemp/test/ ./tmp-download/
+ test1.bin
Traceback (most recent call last):
  File "./b2", line 1904, in <module>
    main()
  File "./b2", line 1886, in main
    ct.sync(args)
  File "./b2", line 1818, in sync
    authorization=True,
  File "./b2", line 1436, in download_file_by_id_helper
    headers_received_cb=headers_received_cb,
  File "./b2", line 994, in download_file_from_url
    with OpenUrl(url, None, request_headers) as response:
  File "./b2", line 1228, in __enter__
    self.file = urllib2.urlopen(request)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 4_z040e479d4f5c932b5f26011c_f1122fbae0a47607a_d20160130_m112948_c001_v0001018_t0041

```

**Comment by bwbeach** [comment]
Well, this is embarrassing.  We don't have any tests from syncing from B2 to local.  I have written one, and it fails in exactly the way you report here.

Next step: fix it.

Thanks for the report!
