### ISSUE TITLE
Sync files with containing umlauts in filename?

### ISSUE THREAD

**Issue by tynie** [Backblaze/B2_Command_Line_Tool#516]
Hi

is there any soloution to handle filenames with umlauts?

Foldername is for example: Abschlussprüfung

Getting this error:

```pytb
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1388, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 210, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 117, in make_folder_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 65, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 96, in all_files
    for file_object in self._walk_relative_paths(self.root, '', reporter, policies_manager):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 157, in _walk_relative_paths
    name = self._handle_non_unicode_file_name(name)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 216, in _handle_non_unicode_file_name
    raise EnvironmentEncodingError(repr(name), sys.getfilesystemencoding())
EnvironmentEncodingError: file name 'Abschlusspr\xc3\xbcfung' cannot be decoded with system encoding (ANSI_X3.4-1968).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8
ERROR: file name 'Abschlusspr\xc3\xbcfung' cannot be decoded with system encoding (ANSI_X3.4-1968).```

**Comment by svonohr** [comment]
Did you see the explanation at the end of the message?

> EnvironmentEncodingError: file name 'Abschlusspr\xc3\xbcfung' cannot be decoded with system encoding (ANSI_X3.4-1968).
> We think this is an environment error which you should workaround by
> setting your system encoding properly, for example like this:
> export LANG=en_US.UTF-8

Indeed the error shows 'ü' encoded as '\xc3\xbc' which is UTF8.

**Comment by tynie** [comment]
Okay my fault... Didn´t saw that. Thank you!

**Comment by ppolewicz** [comment]
What could we do to make it more obvious for the users in future?

**Comment by tynie** [comment]
I already set my locales:

root@mynextcloud: locale -a
C
C.UTF-8
de_DE.utf8
en_US.utf8
POSIX

And my problem with "Abschlussprüfung" was solved but now i got this. It´s the same problem isn´t it?

```ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1388, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 210, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 117, in make_folder_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 65, in zip_folders
    current_a = next_or_none(iter_a)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 96, in all_files
    for file_object in self._walk_relative_paths(self.root, '', reporter, policies_manager):
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 189, in _walk_relative_paths
    local_path, b2_path, reporter, policies_manager
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 157, in _walk_relative_paths
    name = self._handle_non_unicode_file_name(name)
  File "/usr/local/lib/python2.7/dist-packages/b2/sync/folder.py", line 216, in _handle_non_unicode_file_name
    raise EnvironmentEncodingError(repr(name), sys.getfilesystemencoding())
EnvironmentEncodingError: file name 'OneNote-Notizb\xfccher' cannot be decoded with system encoding (UTF-8).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8
ERROR: file name 'OneNote-Notizb\xfccher' cannot be decoded with system encoding (UTF-8).
We think this is an environment error which you should workaround by
setting your system encoding properly, for example like this:
export LANG=en_US.UTF-8
Nextcloud is in maintenance mode - no apps have been loaded

Maintenance mode disabled
Fri Sep 28 08:14:41 UTC 2018
Finished
```

**Comment by svonohr** [comment]
It looks like you have different filename encodings on your filesystem. Your first example was encoded using UTF8 and your second example is probably ISO 8859-1. For B2 CLI to work properly all filenames must be encoded using the same encoding. Tools like `convmv` can help changing the encoding.
