### ISSUE TITLE
'Connection aborted.', BadStatusLine("''",)

### ISSUE THREAD

**Issue by sphen13** [Backblaze/B2_Command_Line_Tool#526]
Recently (the last 2 weeks) I have been having various API calls fail at different locations intermittently.  The view of the error from calling the b2 command line tool is shown below.  Not sure why this would be occurring or how/if the error should be handled.

```
INFO:b2.console_tool:// ========================================  1.3.6   ======================================== \\
DEBUG:b2.console_tool:platform is Darwin-16.7.0-x86_64-i386-64bit
DEBUG:b2.console_tool:Python version is CPython 2.7.10 (default, Feb  7 2017, 00:08:15)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
DEBUG:b2.console_tool:locale is ('en_US', 'UTF-8')
DEBUG:b2.console_tool:filesystem encoding is utf-8
INFO:b2.console_tool:starting command [b2.console_tool.AuthorizeAccount] (arguments hidden)
Using https://api.backblazeb2.com
DEBUG:b2.api:calling authorize_account(self=<b2.api.B2Api object at 0x10d8b8110>, realm='production') (hidden args: account_id_or_key_id, application_key)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.backblazeb2.com:443
ERROR:b2.console_tool:ConsoleTool account authorization error
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/b2/console_tool.py", line 258, in run
    self.api.authorize_account(realm, args.accountId, args.applicationKey)
  File "/Library/Python/2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/Library/Python/2.7/site-packages/b2/api.py", line 126, in authorize_account
    response = self.raw_api.authorize_account(realm_url, account_id_or_key_id, application_key)
  File "/Library/Python/2.7/site-packages/b2/raw_api.py", line 163, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/Library/Python/2.7/site-packages/b2/raw_api.py", line 159, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/Library/Python/2.7/site-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/Library/Python/2.7/site-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/Library/Python/2.7/site-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/Library/Python/2.7/site-packages/b2/b2http.py", line 79, in _translate_errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))
ERROR: unable to authorize account: Connection error: ('Connection aborted.', BadStatusLine("''",))
INFO:b2.console_tool:\\ ========================================  exit=1  ======================================== //
```

**Comment by ppolewicz** [comment]
Please collect a network trace. There is an instruction on how to do that in #330 (I think we should one day write it up on a markdown page so that it is easier to follow...).

**Comment by sphen13** [comment]
thanks - doing that - the trick is duplicating this intermittent issue!  of course the one machine i could count on to do this and has not been able to authorize for days is working now :/

**Comment by bwbeach** [comment]
The Backblaze servers had trouble with an updated library handling TLS, which probably caused this issue.  Let us know if it happens again.

**Comment by sphen13** [comment]
Thank you Brian. Guess I should reach out here first since my long back and forth with support was less than helpful. Thanks.
