### ISSUE TITLE
ERROR:b2.console_tool:ConsoleTool command error

### ISSUE THREAD

**Issue by GlitterCakes** [Backblaze/B2_Command_Line_Tool#527]
Ok seriously why do I get this error just about every time when I sync. It doesn't seem to matter what computer I run this on and don't try and tell me it's my internet it's not I've had this problem in other locations on different servers as well. Please don't suggest simply "re-running" the program that is not a solution to the problem.

I have now close to 20tb worth of data I need stored securely and if the software the company provides me with itself doesn't even work then I will be using a different company to store my data.

```
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 50, in _translate_errors
    response = fcn()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 271, in do_post
    response = self.session.post(url, headers=headers, data=data)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\console_tool.py", line 1388, in run_command
    return command.run(args)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\sync\sync.py", line 210, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\sync\sync.py", line 117, in make_folder_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\sync\sync.py", line 76, in zip_folders
    current_b = next_or_none(iter_b)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\sync\sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\sync\folder.py", line 237, in all_files
    self.folder_name, show_versions=True, recursive=True, fetch_count=1000
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\bucket.py", line 228, in ls
    self.id_, start_file_name, start_file_id, fetch_count
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\raw_api.py", line 333, in list_file_versions
    maxFileCount=max_file_count
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\raw_api.py", line 159, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\b2\b2http.py", line 79, in _translate_errors
    raise B2ConnectionError(str(e0))
b2.exception.B2ConnectionError: Connection error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR: Connection error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by ppolewicz** [comment]
Please run sync with `--debugLogs` (which will produce `b2_cli.log`, which we need to see to understand what is going on) and also collect a network trace. There is an instruction on how to do that in [#330](https://github.com/Backblaze/B2_Command_Line_Tool/issues/330#issuecomment-285205977).

It may be something on the infrastructure of b2 and not an issue with b2 CLI itself, or it might be environmental, or it might be an issue with BGP.

**Comment by GlitterCakes** [comment]
Sorry I can't be bothered to do all that. This app is crap, I've switched to rclone and it works great.

**Comment by bwbeach** [comment]
I'm sorry you weren't able to get the app working, but happy that you found one that you like!
