### ISSUE TITLE
Sync access denied for hidden read only windows files

### ISSUE THREAD

**Issue by grire974** [Backblaze/B2_Command_Line_Tool#530]
OS: Windows Server 2012 r2
Python 2.7

Steps to reproduce:
1) In an administrative command prompt (having already authorized the b2 command line tool) run this command:
b2 sync --replaceNewer F:\ b2://your-bucket-name

After scanning and uploading many files, b2 throws a fatal error and freezes
```pytb
ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1388, in run_com
mand
    return command.run(args)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in w
rapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 210, in sync_folder
s
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 117, in make_folder
_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 65, in zip_folders
    current_a = next_or_none(iter_a)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 36, in next_or_none

    return six.advance_iterator(iterator)
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 96, in all_files
    for file_object in self._walk_relative_paths(self.root, '', reporter, polici
es_manager):
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 152, in _walk_rel
ative_paths
    for name in os.listdir(local_dir):
WindowsError: [Error 5] Access is denied: u'\\\\?\\F:\\Current\\tba_projects\\.T
emporaryItems\\folders.501\\Cleanup At Startup\\.BAH.YMiBF\\Approved Logo\\*.*'
Traceback (most recent call last):
  File "C:\Python27\Scripts\b2-script.py", line 11, in <module>
    load_entry_point('b2==1.3.6', 'console_scripts', 'b2')()
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1512, in main
    exit_status = ct.run_command(decoded_argv)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1388, in run_com
mand
    return command.run(args)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "c:\python27\lib\site-packages\logfury\v0_1\trace_call.py", line 84, in w
rapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 210, in sync_folder
s
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 117, in make_folder
_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 65, in zip_folders
    current_a = next_or_none(iter_a)
  File "c:\python27\lib\site-packages\b2\sync\sync.py", line 36, in next_or_none

    return six.advance_iterator(iterator)
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 96, in all_files
    for file_object in self._walk_relative_paths(self.root, '', reporter, polici
es_manager):
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 189, in _walk_rel
ative_paths
    local_path, b2_path, reporter, policies_manager
  File "c:\python27\lib\site-packages\b2\sync\folder.py", line 152, in _walk_rel
ative_paths
    for name in os.listdir(local_dir):
WindowsError: [Error 5] Access is denied: u'\\\\?\\F:\\Current\\tba_projects\\.T
emporaryItems\\folders.501\\Cleanup At Startup\\.BAH.YMiBF\\Approved Logo\\*.*'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\python27\lib\site-packages\concurrent\futures\thread.py", line 47, in
 _python_exit
    t.join(sys.maxint)
  File "c:\python27\lib\threading.py", line 951, in join
    self.__block.wait(delay)
  File "c:\python27\lib\threading.py", line 359, in wait
    _sleep(delay)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 76, in keyboard_
interrupt_handler
    raise KeyboardInterrupt()
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "c:\python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\python27\lib\site-packages\concurrent\futures\thread.py", line 47, in
 _python_exit
    t.join(sys.maxint)
  File "c:\python27\lib\threading.py", line 951, in join
    self.__block.wait(delay)
  File "c:\python27\lib\threading.py", line 359, in wait
    _sleep(delay)
  File "c:\python27\lib\site-packages\b2\console_tool.py", line 76, in keyboard_
interrupt_handler
    raise KeyboardInterrupt()
KeyboardInterrupt
```

The folder in question is a hidden cache folder created by an app using the source drive.
The folder has windows permissions hidden, and read-only.  The administrator, and all domain users have 'Full Control' security permission for this folder.

**Comment by ppolewicz** [comment]
Which version of b2 cli did you use?

**Comment by grire974** [comment]
1.3.6

**Comment by bwbeach** [comment]
We'll need to clean up how errors are reported!

Do you expect those hidden folders to get synced, or would you like to exclude them?

The `--excludeDirRegex` option can be used to exclude directories whose names start with `.`.  The names matched are the ones for B2, not the local names, so the path separator is `/`, not `\`.

This regex will exclude directory paths that start with `.` or that include `/.` somewhere.  It's works on my Mac, and I think it should work for Windows as well:

```
b2 sync --excludeDirRegex '^[.].*|.*/[.].*' . b2://<bucketName>/<path>
```

**Comment by grire974** [comment]
Thanks for looking into it; yes I'm aware of the exclude regex option, just wanted to report this so it was on the radar.  Yes I think a flag to proceed with the sync if an error is thrown could be good, or some error handling similar. The folder that's throwing the exception I don't care about uploading; however there will be some readonly /hidden folders that will need uploading (e.g. .git, .svn, .htaccess etc...)

**Comment by grire974** [comment]
although I did still get the error with: 
b2 sync --replaceNewer --excludeDirRegex '^([.]){1}(TemporaryItems){1}' F:\ b2://bucket-name

I think my regex is correct if I want to exclude dirs called '.TemporaryItems' right?

If so, then the excludeDirRegex workaround might not work in this case.

**Comment by ppolewicz** [comment]
It's the operating system that reports a permission error to python. I know it seems like the program should have access to the given file and should be able to read it, but it is clear that your operating system (for reasons which are unclear) thinks otherwise and forbids access.

**Comment by grire974** [comment]
ok.. am happy to provide more info if you have any pointed questions.  b2 is my first choice for a backup solution provider & I'd love to get something working for periodic remote offsite backup.  We have about 5TB at the moment, millions of files, can't think of another way in the short term to get our stuff online and have it frequently updated..  Seems like the command line b2 sync command is at an impasse for me at the moment though unless you have any other ideas..?  I don't want to exclude all hidden dirs (in the long term at least) for reasons stated above; just the ones that are throwing errors.

**Comment by bwbeach** [comment]
@grire974 - Would you be interested extending the tool to add a `--skipPermissionErrors` option?  We have a friendly group of people working on the project, and would be happy to collaborate with you.

This option would solve your problem, but it would also be dangerous.  It could easily lead to skipping files that should be backed up.

Another choice would be to teach it to read a file containing a list of directories to skip, with on option like `--dirsToSkipFile`.  Then you could explicitly list the folders you don't want to back up, and it would not miss folders that should be backed up.

**Comment by grire974** [comment]
either would be a step up for me for sure.. I agree regarding --skipPermissionErros, however in conjunction with a log file to keep track of files that were skipped it could be safer.  The problem with --dirsToSkipFile is that it requires first knowing what dirs are going to create problems, which on a shared company network drive (our network file server is actually build on BackBlaze's open source hardware architecture provided by 45drives.com) could be very difficult to keep a dirsToSkip file up to date..  My personal preference would be a skipPermissionsErrors option combined with a log file location (an agreed upon default location is fine for me, or I guess it could be another flag?)  Thanks for your help!

**Comment by bwbeach** [comment]
How about `--permissionErrorsToFile`?  You could specify the file, and the tool could write the file paths, one per line, that had permission problems.  

I like having to provide a file, because it makes it clear that you should do something with the result to ensure that your backup worked.

**Comment by grire974** [comment]
Perfect!

**Comment by bwbeach** [comment]
Next question: Would you like to take a stab at implementing it?  We won't get to it right away.

**Comment by grire974** [comment]
Am definitely willing to help test any pre-release builds too if anyone wants to contact me with a branch to download.

**Comment by mjurbanski-reef** [comment]
The `b2` v4 behavior is as follows:
* All files with permission errors are skipped over with printed warning, not preventing accessible files from being synchronized
* All errors and warnings are printed once again at the end of the sync, so user can see them (otherwise they would be lost in sea of progress messages)
* If any errors or warnings were produced during sync, the `b2 sync` status code will be set to 1 instead of 0. This means that while all files without these errors were synchronized, there will still some (the ones with permission errors) that were not.
