### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by realgeek** [Backblaze/B2_Command_Line_Tool#545]
I've just finished doing pip3 install -U b2fuse.

```
$ b2fuse --version
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 7, in <module>
    from b2fuse.b2fuse import main
 File "/usr/local/lib/python3.5/dist-packages/b2fuse/b2fuse.py", line 32, in <module>
    from b2fuse_main import B2Fuse
ImportError: No module named 'b2fuse_main'
```

This is happening on more than one linux machine of mine.

**Comment by realgeek** [comment]
Sorry I'm in the wrong repo.
