### ISSUE TITLE
bs sync sometimes does not retry on BadStatusLine when it should have

### ISSUE THREAD

**Issue by martin-c** [Backblaze/B2_Command_Line_Tool#562]
Running this command on my SmartOS server:
`(.python_env) [clemons@files /import]$ b2 sync --keepDays 180 --replaceNewer /import/photos b2://mimas-lan-photos`

results in the following error:
```
B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))
ERROR: Connection error: ('Connection aborted.', BadStatusLine("''",))
```
This looks like a duplicate of issue #435, except b2 client is running on dedicated hardware in a data center with 100MB wired connection (data center is located in Germany).
Is there a workaround for this problem?

Full stacktrace:
```
upload family/2012/04/21/MVI_7116.THM
upload family/2012/04/21/MVI_7115.THM
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/console_tool.py", line 1399, in run_command
    return command.run(args)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/console_tool.py", line 1181, in run
    allow_empty_source=allow_empty_source
  File "/home/clemons/.python_env/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/sync/sync.py", line 210, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/sync/sync.py", line 117, in make_folder_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/sync/sync.py", line 76, in zip_folders
    current_b = next_or_none(iter_b)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/sync/folder.py", line 241, in all_files
    self.folder_name, show_versions=True, recursive=True, fetch_count=1000
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/bucket.py", line 228, in ls
    self.id_, start_file_name, start_file_id, fetch_count
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/raw_api.py", line 336, in list_file_versions
    maxFileCount=max_file_count
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/raw_api.py", line 162, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/home/clemons/.python_env/lib/python2.7/site-packages/b2/b2http.py", line 79, in _translate_errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))
ERROR: Connection error: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by ppolewicz** [comment]
This time the failure took place during listing of bucket contents.

@martin-c does it happen frequently, or did it just happen once? It looks like a transient network error that should resolve on its own fairly quickly.

**Comment by TechKat** [comment]
@ppolewicz This is happening to me too, and is quite frustrating when you're trying to sync around 10mil+ files totaling 1.3TB. When the sync fails, starting again just leads to the client re-scanning the entire directory again.

`ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 1399, in run_command
    return command.run(args)
  File "/usr/lib/python2.7/site-packages/b2/console_tool.py", line 1181, in run
    allow_empty_source=allow_empty_source
  File "/usr/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/lib/python2.7/site-packages/b2/sync/sync.py", line 210, in sync_folders
    source_folder, dest_folder, args, now_millis, reporter, policies_manager
  File "/usr/lib/python2.7/site-packages/b2/sync/sync.py", line 117, in make_folder_sync_actions
    source_folder, dest_folder, reporter, policies_manager
  File "/usr/lib/python2.7/site-packages/b2/sync/sync.py", line 76, in zip_folders
    current_b = next_or_none(iter_b)
  File "/usr/lib/python2.7/site-packages/b2/sync/sync.py", line 36, in next_or_none
    return six.advance_iterator(iterator)
  File "/usr/lib/python2.7/site-packages/b2/sync/folder.py", line 241, in all_files
    self.folder_name, show_versions=True, recursive=True, fetch_count=1000
  File "/usr/lib/python2.7/site-packages/b2/bucket.py", line 228, in ls
    self.id_, start_file_name, start_file_id, fetch_count
  File "/usr/lib/python2.7/site-packages/b2/session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/b2/raw_api.py", line 336, in list_file_versions
    maxFileCount=max_file_count
  File "/usr/lib/python2.7/site-packages/b2/raw_api.py", line 162, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/usr/lib/python2.7/site-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/usr/lib/python2.7/site-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/usr/lib/python2.7/site-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/lib/python2.7/site-packages/b2/b2http.py", line 79, in _translate_errors
    raise B2ConnectionError(str(e0))
B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",))
ERROR: Connection error: ('Connection aborted.', BadStatusLine("''",))`

**Comment by ppolewicz** [comment]
The good news is that the file transfer operations start while the the listing is running, so you don't actually wait for the whole thing to rescan to begin transfers.

The... other news, shall we say, is that I found a bug which sometimes decreases the number of retry attempts to zero. It's bad that there is a bug, but now that I've located it, I can fix it (next week?).

@TechKat @martin-c thank you for the stacktraces. If you have not posted them, I would not have found that issue.

**Comment by stamster** [comment]
> This looks like a duplicate of issue #435, except b2 client is running on dedicated hardware in a data center with 100MB wired connection (data center is located in Germany).
> Is there a workaround for this problem?

What difference does it make running b2 (or any other CLI tool) on "dedicated hardware" vs. any other way (VM/container/you name it)?

We're also having the same intermittent issue with both dedicated server(s) and those which are running on ESXi. So it really does not make any difference, it is intermittent/sporadic. We have APAC, Americas and Europe servers - so they all behave in a same manner. 
 
Excerpt from today backup to B2:
`Attempt 1 failed. B2ConnectionError: Connection error: ('Connection aborted.', BadStatusLine("''",)) `

The good news is, b2 client manages to re-try one or more times and which yields a success. My wild guess is load balancing at Backblaze end fails, thus re-try succedes.

**Comment by ppolewicz** [comment]
If a retry solves the problem, I think we are fine. B2 is a low-cost cloud, I'd rather accept an occasional retry than have an expensive cloud storage provider (that being said, the retry policy of b2sdk/CLI could be better).

**Comment by ppolewicz** [comment]
And to answer your question, @stamster, some hypervisors have really, really bad network drivers.

**Comment by stamster** [comment]
Yeah, my impression also - for now retry does the job. :+1: 

And for hypervisors - sure, but that's also possible with dedicated servers as well, crappy chip, bad driver etc. But that's out of the question here, we assume everyone has their networking and server parts done right - and validated with other external services. For instance, our ESXi hypervisors are using a para-virtualized network driver, whilst physical adapter is limited to 1 Gbit/s full duplex towards the Internet and we have no issues with other services we're using, only B2.

**Comment by ppolewicz** [comment]
@stamster I just asked because I have observed very similar issues when using VirtualBox "NAT" driver recently, thought maybe there is a small chance that it is what is triggering your problem (metadata operations retry issue notwithstanding)

**Comment by stamster** [comment]
Today I have the following in backup logs:

```
Attempt 1 failed. MaxRetriesExceeded: FAILED to upload after 5 tries. Encountered exceptions: Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
```

:thinking:

**Comment by ppolewicz** [comment]
This is being resolved by https://github.com/Backblaze/b2-sdk-python/pull/22
