### ISSUE TITLE
Downloading zero-length files fails

### ISSUE THREAD

**Issue by k2l8m11n2** [Backblaze/B2_Command_Line_Tool#566]
```
Traceback (most recent call last):
  File "/home/alice/.local/bin/b2", line 11, in <module>
    load_entry_point('b2==1.3.8', 'console_scripts', 'b2')()
  File "/home/alice/.local/lib/python2.7/site-packages/b2/console_tool.py", line 1523, in main
    exit_status = ct.run_command(decoded_argv)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/console_tool.py", line 1399, in run_command
    return command.run(args)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/console_tool.py", line 532, in run
    bucket.download_file_by_name(args.b2FileName, download_dest, progress_listener)
  File "/home/alice/.local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/bucket.py", line 168, in download_file_by_name
    url, download_dest, progress_listener, range_
  File "/home/alice/.local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/transferer/transferer.py", line 108, in download_file_from_url
    file, response, metadata, self.session
  File "/home/alice/.local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/transferer/simple.py", line 24, in download
    actual_size = self._get_remote_range(response, metadata).size()
  File "/home/alice/.local/lib/python2.7/site-packages/b2/transferer/abstract.py", line 51, in _get_remote_range
    return Range(0, metadata.content_length - 1)
  File "/home/alice/.local/lib/python2.7/site-packages/b2/transferer/range.py", line 18, in __init__
    assert 0 <= start <= end
AssertionError
```

**Comment by ppolewicz** [comment]
Fixed in https://github.com/Backblaze/b2-sdk-python/pull/13
