### ISSUE TITLE
Errors with tqdm>=3.8.0

### ISSUE THREAD

**Issue by skeetio** [Backblaze/B2_Command_Line_Tool#59]
Using tqdm for the progress bar seems to be generating errors with the latest version available on pypi (3.8.0) as well as the latest stable version from github (4.0.0).  Seems to occur on both upload_file and sync operations.  Did not occur when used version 3.4.0 of tqdm.

[Traceback](https://gist.github.com/skeetio/7b7b81fef755bc9092f7)

**Comment by ppolewicz** [comment]
Are you trying to upload an empty file?

**Comment by skeetio** [comment]
No, 98k of data generated from /dev/random into a test file.  For what its worth, issue also presented itself when uploading a 43M zip file

**Comment by ppolewicz** [comment]
I understand. Thank you for your report. I will try to investigate it during this weekend.

In order to prevent a disruption to your workflow, please disable tqdm or use the old version of tqdm temporarily.

**Comment by nilayp** [comment]
I'm seeing the same error. Here's the stack trace:

`Traceback (most recent call last):
  File "/usr/local/bin/b2", line 9, in <module>
    load_entry_point('b2==0.4.0', 'console_scripts', 'b2')()
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 1930, in main
    ct.upload_file(args)
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 1661, in upload_file
    quiet=quiet,
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 588, in upload_file
    response = post_file(upload_url, headers, local_file, progress_bar=not quiet,)
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 1403, in post_file
    with OpenUrl(url, data_file, headers) as response_file:
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 1272, in __enter__
    self.file = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 867, in send
    datablock = data.read(blocksize)
  File "/Library/Python/2.7/site-packages/b2/b2.py", line 1385, in read
    self.update(len(data))
  File "/Library/Python/2.7/site-packages/tqdm/_tqdm.py", line 534, in update
    raise ValueError("n ({0}) cannot be less than 1".format(n))
ValueError: n (0) cannot be less than 1`

**Comment by ppolewicz** [comment]
with tqdm 3.7.1 it works correctly

**Comment by ppolewicz** [comment]
https://github.com/tqdm/tqdm/commit/1928a7ec44cc53e8dc9e24d8f1f6f1fe48a48193

**Comment by felixbuenemann** [comment]
@bwbeach This is a critical bug I just ran into as well, you should really do a new release.

**Comment by bwbeach** [comment]
We usually release on Thursday.  I could move that ahead and do it today.  Didn't release last week because I wanted more testing of Python 3, but @ppolewicz added Python 3 testing, so I think it's ready.

**Comment by ppolewicz** [comment]
For python 2 and 3 we have the same tests

**Comment by felixbuenemann** [comment]
@bwbeach Great, I upgraded with pip from github for now, but any new user installing b2 and following the advice to install tqdm will encounter this problem.
