### ISSUE TITLE
"b2 sync" fails even with minimal options.

### ISSUE THREAD

**Issue by AnirudhaS** [Backblaze/B2_Command_Line_Tool#593]
I am attempting to sync a local folder to the bucket.

**sync results in "unable to create directory"**

```
$: b2 version
b2 command line tool, version 1.4.0
$: b2 sync /Users/ani/folder_1/ bs://bucket/
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 11, in <module>
    load_entry_point('b2==1.4.0', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1486, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1361, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1184, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/sync.py", line 222, in sync_folders
    dest_folder.ensure_present()
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/folder.py", line 141, in ensure_present
    raise Exception('unable to create directory %s' % (self.root,))
Exception: unable to create directory /Users/ani/folder_1/bs:/bucket/
```

**sync with --dryRun results in "neither folder is a b2 folder"**
```
$: b2 sync --dryRun /Users/ani/folder_1/ bs://bucket/
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 11, in <module>
    load_entry_point('b2==1.4.0', 'console_scripts', 'b2')()
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1486, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1361, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1184, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/sync.py", line 259, in sync_folders
    raise ValueError('neither folder is a b2 folder')
ValueError: neither folder is a b2 folder
```
This sync is pretty basic, without any regex options, either I am missing something or this is an actual issue.

I have been able to `list-file-names`, `list-buckets`, and `upload`.

I even attempted this on a freshly created VPS, if there might've been some versioning screw up.

**Comment by certainmagic** [comment]
in your example, you wrote "bs://bucket/".  does it work better if you write "b2://bucket/", with a "b2" instead of a "bs"? or was that just a typo in your example?
