### ISSUE TITLE
sync fails with "sha1 checksum mismatch -- bad data"

### ISSUE THREAD

**Issue by highfalutin** [Backblaze/B2_Command_Line_Tool#594]
I am trying to download a directory from b2 to a local disk on my Mac (10.14.6) using the `sync` command (b2 clt version 1.4.0). 

The sync fails; sometimes files are created with the extension "b2.sync.tmp"; sometimes they are zero bytes and sometimes they contain some data; sometimes no files are transferred at all.

My command:

````
b2 sync --replaceNewer b2://mybucket/s7-dec-2017/external /Volumes/HD/s7-dec-2017/external
````

The following error is shown for each attempted file:

````
ERROR:b2sdk.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/action.py", line 49, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/action.py", line 247, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/bucket.py", line 302, in download_file_by_name
    url, download_dest, progress_listener, range_
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/transferer/transferer.py", line 115, in download_file_from_url
    range_, bytes_read, actual_sha1, metadata
  File "/usr/local/lib/python2.7/site-packages/b2sdk/transferer/transferer.py", line 129, in _validate_download
    actual=actual_sha1,
ChecksumMismatch: sha1 checksum mismatch -- bad data
b2_download(s7-dec-2017/external/VIDEO0109.mp4, xxxxxxxxxx_redacted_file_id_xxxxxxxxxxxxxxxxxxxxx, /Volumes/HD/s7-dec-2017/external/VIDEO0109.mp4, 1561041018000): ChecksumMismatch() sha1 checksum mismatch -- bad data
````

And after a few of those errors, this final error appears:

````
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1361, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/site-packages/b2/console_tool.py", line 1184, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python2.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python2.7/site-packages/b2sdk/sync/sync.py", line 273, in sync_folders
    raise CommandError('sync is incomplete')
CommandError: sync is incomplete
ERROR: sync is incomplete
````

I did not experience these errors when syncing from a local directory to b2.

**Comment by ppolewicz** [comment]
TBH this looks like a hardware error, most likely memory, possibly upon reading. I think you should run a memtest.

Please confirm. Are you attempting to sync some small files?

**Comment by highfalutin** [comment]
The files range from 0b to 1.4Gb.

**Comment by ppolewicz** [comment]
Please confirm that memtest ran on source (which uploaded) and destination (which downloads) passes. Other customers are not reporting such issues, bad ram does happen (I've found a bad brick myself once or twice), so it looks like an environmental problem.
