### ISSUE TITLE
sqlite3.OperationalError: unable to open database file  (Windows 10)

### ISSUE THREAD

**Issue by mblais** [Backblaze/B2_Command_Line_Tool#596]
(Windows 10 x64 ver 10.0.18362)
I always get this error from `b2`.  Clean Python install, and I have also tried with only miniconda installed (no difference).

```
>python --version
Python 3.7.4

>b2
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\b2.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\b2\console_tool.py", line 1481, in main
    info = SqliteAccountInfo()
  File "c:\programdata\miniconda3\lib\site-packages\b2sdk\account_info\sqlite_account_info.py", line 52, in __init__
    self._validate_database()
  File "c:\programdata\miniconda3\lib\site-packages\b2sdk\account_info\sqlite_account_info.py", line 64, in _validate_database
    self._create_database(last_upgrade_to_run)
  File "c:\programdata\miniconda3\lib\site-packages\b2sdk\account_info\sqlite_account_info.py", line 126, in _create_database
    conn = self._connect()
  File "c:\programdata\miniconda3\lib\site-packages\b2sdk\account_info\sqlite_account_info.py", line 118, in _connect
    return sqlite3.connect(self.filename, isolation_level='EXCLUSIVE')
sqlite3.OperationalError: unable to open database file
```
Here's the installation:
```
(base) C:\Users\Matt>pip install --upgrade b2
Collecting b2
  Using cached https://files.pythonhosted.org/packages/90/b6/71ec542b76ea5a282dd2c2fb6f8427d90e3397e5db59593510667f14f236/b2-1.4.0.tar.gz
Collecting b2sdk<0.2.0,>=0.1.6 (from b2)
  Using cached https://files.pythonhosted.org/packages/ea/2e/bd06b7250d936b8cf502d44c789e90cb4837dd9c9242ed88e9a2bc30bb05/b2sdk-0.1.8.tar.gz
Requirement already satisfied, skipping upgrade: six>=1.10 in c:\programdata\miniconda3\lib\site-packages (from b2) (1.12.0)
Requirement already satisfied, skipping upgrade: tqdm>=4.5.0 in c:\programdata\miniconda3\lib\site-packages (from b2) (4.32.1)
Collecting arrow<0.13.1,>=0.8.0 (from b2sdk<0.2.0,>=0.1.6->b2)
  Using cached https://files.pythonhosted.org/packages/5d/c7/468bb95a10fb8ddb5f3f80e1aef06b78f64d6e5df958c39672f80581381f/arrow-0.13.0.tar.gz
Collecting logfury>=0.1.2 (from b2sdk<0.2.0,>=0.1.6->b2)
  Using cached https://files.pythonhosted.org/packages/55/71/c70df1ef41721b554c91982ebde423a5cf594261aa5132e39ade9196fa3b/logfury-0.1.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests>=2.9.1 in c:\programdata\miniconda3\lib\site-packages (from b2sdk<0.2.0,>=0.1.6->b2) (2.22.0)
Requirement already satisfied, skipping upgrade: setuptools in c:\programdata\miniconda3\lib\site-packages (from b2sdk<0.2.0,>=0.1.6->b2) (41.0.1)
Collecting python-dateutil (from arrow<0.13.1,>=0.8.0->b2sdk<0.2.0,>=0.1.6->b2)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting funcsigs (from logfury>=0.1.2->b2sdk<0.2.0,>=0.1.6->b2)
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\programdata\miniconda3\lib\site-packages (from requests>=2.9.1->b2sdk<0.2.0,>=0.1.6->b2) (2019.6.16)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\programdata\miniconda3\lib\site-packages (from requests>=2.9.1->b2sdk<0.2.0,>=0.1.6->b2) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\programdata\miniconda3\lib\site-packages (from requests>=2.9.1->b2sdk<0.2.0,>=0.1.6->b2) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\miniconda3\lib\site-packages (from requests>=2.9.1->b2sdk<0.2.0,>=0.1.6->b2) (1.24.2)
Building wheels for collected packages: b2, b2sdk, arrow
  Building wheel for b2 (setup.py) ... done
  Stored in directory: C:\Users\Matt\AppData\Local\pip\Cache\wheels\cd\10\35\2e308a35e697646c97fbd94907cd516b8a8ed1a4824a3d66e4
  Building wheel for b2sdk (setup.py) ... done
  Stored in directory: C:\Users\Matt\AppData\Local\pip\Cache\wheels\76\97\23\8ed305eb1c80e4b7d4e507155037cdcde012edf78fffe39d12
  Building wheel for arrow (setup.py) ... done
  Stored in directory: C:\Users\Matt\AppData\Local\pip\Cache\wheels\1e\d5\30\cace6155de216c74f70b1b866ce6ec2c9bbc60be88073a1fcd
Successfully built b2 b2sdk arrow
Installing collected packages: python-dateutil, arrow, funcsigs, logfury, b2sdk, b2
Successfully installed arrow-0.13.0 b2-1.4.0 b2sdk-0.1.8 funcsigs-1.0.2 logfury-0.1.2 python-dateutil-2.8.0
```

**Comment by ppolewicz** [comment]
Is your windows user non-standard somehow, like maybe it has restricted permissions to access data in the home directory or something like that?

A workaround on Windows _might be_ to run:
```batch
SET B2_ACCOUNT_INFO=C:\Users\Matt\AppData\Local\.b2_account_info.sqlite
```
in the terminal before running any b2 commands. I haven't tested it on Windows, but it should work.

**Comment by mblais** [comment]
Apparently the culprit is that I have the `HOME` environment variable set to an invalid location.

`b2` is working when I correct that issue 😊

It might be useful to log the mysql db file path in the event that it cannot be opened.

**Comment by mblais** [comment]
Error is resolved now - I had my HOME env var set to an invalid location.

Thanks for your help!
