### ISSUE TITLE
b2 sync error when file is hidden

### ISSUE THREAD

**Issue by Nyxtorm** [Backblaze/B2_Command_Line_Tool#605]
Hello,

When I'm trying to sync a bucket's folder after I have hidden a file into it, it's impossible to resync :

* Step 1 -- First sync with no files hidden :

```
# b2 sync --delete --replaceNewer 'b2://test-b2-sync-hidden/test_b2sync/' '/volumes/data/shares/public/test_b2sync/'

dnload test2.pdf.zipx
dnload test4.pdf.zipx
dnload test1.pdf.zipx
dnload test5.pdf.zipx
dnload test3.pdf.zipx
```
===> ALL IS OK, sync completed without error

* Step 2 -- Manual hide file (same result with SyncBack Pro deletion sync)
```
#  b2 hide-file test-b2-sync-hidden 'test_b2sync/test1.pdf.zipx'

{
  "action": "hide",
  "fileId": "4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031",
  "fileName": "test_b2sync/test1.pdf.zipx",
  "size": 0,
  "uploadTimestamp": 1576518197000
}
```

Control :
```
# b2 ls --long --versions test-b2-sync-hidden 'test_b2sync/'

4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031    hide  2019-12-16  17:43:17          0  test_b2sync/test1.pdf.zipx
4_zd3b6cc26b5f305fb6cf30211_f100af957a9d18411_d20191216_m173840_c001_v0001043_t0006  upload  2019-12-16  17:38:40      16295  test_b2sync/test1.pdf.zipx
4_zd3b6cc26b5f305fb6cf30211_f100af957a9d18415_d20191216_m173900_c001_v0001043_t0006  upload  2019-12-16  17:39:00      16295  test_b2sync/test2.pdf.zipx
4_zd3b6cc26b5f305fb6cf30211_f100af957a9d18417_d20191216_m173902_c001_v0001043_t0006  upload  2019-12-16  17:39:02      16295  test_b2sync/test3.pdf.zipx
4_zd3b6cc26b5f305fb6cf30211_f100af957a9d1841b_d20191216_m173923_c001_v0001043_t0006  upload  2019-12-16  17:39:23      16295  test_b2sync/test4.pdf.zipx
4_zd3b6cc26b5f305fb6cf30211_f100af957a9d1841d_d20191216_m173925_c001_v0001043_t0006  upload  2019-12-16  17:39:25      16295  test_b2sync/test5.pdf.zipx
```

===> ALL IS OK, last version of test_b2sync/test1.pdf.zipx is tagged "hide"

* Step 3 -- Try a new sync with --delete :

```
# b2 sync --delete --replaceNewer 'b2://test-b2-sync-hidden/test_b2sync/' '/volumes/data/shares/public/test_b2sync/'

ERROR:b2sdk.sync.action:an exception occurred in a sync action                                                                                                                                                                     [10/11265]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/sync/action.py", line 49, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/sync/action.py", line 247, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/bucket.py", line 259, in download_file_by_name
    url, download_dest, progress_listener, range_
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/transferer/transferer.py", line 80, in download_file_from_url
    range_=range_,
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/raw_api.py", line 274, in download_file_from_url
    return self.b2_http.get_content(url, request_headers)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/b2http.py", line 376, in get_content
    response = _translate_and_retry(do_get, try_count, None)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/b2http.py", line 122, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/b2http.py", line 63, in _translate_errors
    post_params,
b2sdk.exception.FileNotPresent: File not present: None
b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000): FileNotPresent(None) File not present: N
one
ERROR:b2.console_tool:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 47, in sync_folders
    super(Synchronizer, self).sync_folders(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/sync/sync.py", line 233, in sync_folders
    raise IncompleteSync('sync is incomplete')
b2sdk.sync.exception.IncompleteSync: Incomplete sync: sync is incomplete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2-1.4.3-py3.7.egg/b2/console_tool.py", line 1483, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.7/dist-packages/b2-1.4.3-py3.7.egg/b2/console_tool.py", line 1313, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 195, in sync_folders
    synchronizer.sync_folders(source_folder, dest_folder, now_millis, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 51, in sync_folders
    raise CommandError(e.message)
AttributeError: 'IncompleteSync' object has no attribute 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 47, in sync_folders
    super(Synchronizer, self).sync_folders(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/sync/sync.py", line 233, in sync_folders
    raise IncompleteSync('sync is incomplete')
b2sdk.sync.exception.IncompleteSync: Incomplete sync: sync is incomplete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/b2", line 11, in <module>
    load_entry_point('b2==1.4.3', 'console_scripts', 'b2')()
  File "/usr/local/lib/python3.7/dist-packages/b2-1.4.3-py3.7.egg/b2/console_tool.py", line 1625, in main
  File "/usr/local/lib/python3.7/dist-packages/b2-1.4.3-py3.7.egg/b2/console_tool.py", line 1483, in run_command
  File "/usr/local/lib/python3.7/dist-packages/b2-1.4.3-py3.7.egg/b2/console_tool.py", line 1313, in run
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 195, in sync_folders
    synchronizer.sync_folders(source_folder, dest_folder, now_millis, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2sdk/v0/sync.py", line 51, in sync_folders
    raise CommandError(e.message)
AttributeError: 'IncompleteSync' object has no attribute 'message'
```

===> NOT OK, error when b2 is tring to sync my hidden file

If I manually delete the file in bucket, problem is solved, but I lose my file history and 
it's impossible to apply this workaround if there are thousands of files.

########################################################

* b2 command line tool, version 1.4.3
* Python 3.7.3
* Debian Buster 10.2

########################################################

Sorry for my bad English.

Regards,

**Comment by ppolewicz** [comment]
@Nyxtorm please try to run `pip install b2==1.3.6` and reproduce it then, I suspect it might be a regression. Using the older version is the easiest way to resume your operation, while we look into fixing this bug.

**Comment by ppolewicz** [comment]
`AttributeError: 'IncompleteSync' object has no attribute 'message'` is one bug, we need to fix that, but there is another issue of some sort that passes `None` where it should not be passed. Needs further looking into.

**Comment by Nyxtorm** [comment]
@ppolewicz Hello,

Thanks for your help.

There is the same problem with version 1.3.6. 
I tried with version 1.2.0 too.

Regards,

**Comment by Nyxtorm** [comment]
* With 1.3.6 :
```
# b2 version

b2 command line tool, version 1.3.6

# b2 sync --delete --replaceNewer 'b2://test-b2-sync-hidden/test_b2sync/' '/volumes/data/shares/public/test_b2sync/'

ERROR:b2.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 42, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 143, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/bucket.py", line 168, in download_file_by_name
    url, download_dest, progress_listener, range_
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/transferer.py", line 45, in download_file_from_url
    range_=range_,
  File "/usr/local/lib/python3.7/dist-packages/b2/session.py", line 39, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/raw_api.py", line 248, in download_file_from_url
    return self.b2_http.get_content(url, request_headers)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 337, in get_content
    response = _translate_and_retry(do_get, try_count, None)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.FileNotPresent: File not present:
b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000): FileNotPresent() File not present:
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 1388, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 1170, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/sync.py", line 220, in sync_folders
    raise CommandError('sync is incomplete')
b2.exception.CommandError: sync is incomplete
ERROR: sync is incomplete
```

* With 1.2.0 :

```
# b2 version

b2 command line tool, version 1.2.0

# b2 sync --delete --replaceNewer 'b2://test-b2-sync-hidden/test_b2sync/' '/volumes/data/shares/public/test_b2sync/'

ERROR:b2.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 42, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 143, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/bucket.py", line 166, in download_file_by_name
    range_=range_,
  File "/usr/local/lib/python3.7/dist-packages/b2/session.py", line 38, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/raw_api.py", line 210, in download_file_by_name
    url, account_auth_token_or_none, download_dest, range_=range_
  File "/usr/local/lib/python3.7/dist-packages/b2/raw_api.py", line 236, in _download_file_from_url
    with self.b2_http.get_content(url, request_headers) as response:
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 337, in get_content
    response = _translate_and_retry(do_get, try_count, None)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.FileNotPresent: File not present:
b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000): FileNotPresent() File not present:
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 1138, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 921, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/sync.py", line 220, in sync_folders
    raise CommandError('sync is incomplete')
b2.exception.CommandError: sync is incomplete
ERROR: sync is incomplete
```

**Comment by ppolewicz** [comment]
All right, that really does look like a bug (and an old one at that!)

@Nyxtorm if I can ask you to help us investigate it further, output of a failing run with `--verbose` would be helpful, as well as a minimal example script in shell to reproduce it (as far as I understand it is enough to sync a directory with two files, remove one file, sync up again and then sync down - is that correct?)

**Comment by Nyxtorm** [comment]
Here is the full output for the same synchronization command with `--verbose` option :

```
INFO:b2.console_tool:// ========================================  1.2.0   ======================================== \\
DEBUG:b2.console_tool:platform is Linux-5.3.0-0.bpo.2-amd64-x86_64-with-debian-10.2
DEBUG:b2.console_tool:Python version is CPython 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.3.0]
DEBUG:b2.console_tool:locale is ('en_US', 'UTF-8')
DEBUG:b2.console_tool:filesystem encoding is utf-8
INFO:b2.console_tool:starting command [b2.console_tool.Sync] with arguments: ['/usr/local/bin/b2', 'sync', '--verbose', '--delete', '--replaceNewer', 'b2://test-b2-sync-hidden/test_b2sync/', '/volumes/data/shares/public/test_b2sync/']
DEBUG:b2.api:calling B2Api.set_thread_pool_size(self=<b2.api.B2Api object at 0x7f4615c9ec50>, max_workers=10)
DEBUG:b2.sync.sync:calling sync_folders(source_folder=<b2.sync.folder.B2Folder object at 0x7f4615c9efd0>, dest_folder=LocalFolder(/volumes/data/shares/public/test_b2sync), args=Arguments({'allowEmptySource': False, 'compareThreshold': None, 'compareVersions': None, 'debugLogs': False, 'delete': True, 'destination': '/volumes/data/shares/public/test_b2sync/', 'dryRun': False, 'excludeDirRegex': [], 'excludeRegex': [], 'includeRegex': [], 'keepDays': None, 'logConfig': None, 'noProgress': False, 'replaceNewer': True, 'skipNewer': False, 'source': 'b2://test-b2-sync-hidden/test_b2sync/', 'threads': None, 'verbose': True}), now_millis=1576540905040, stdout=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>, no_progress=False, max_workers=10, policies_manager=<b2.sync.scan_policies.ScanPoliciesManager object at 0x7f4615c3d7b8>, dry_run=False, allow_empty_source=False)
 count: 0 files   compare: 0 files   updated: 0 files   0 B   0 B/s
DEBUG:b2.bucket:calling Bucket.ls(self=Bucket<d3b6cc26b5f305fb6cf30211,test-b2-sync-hidden,None>, folder_to_list='test_b2sync', show_versions=True, recursive=True, fetch_count=1000, max_entries=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v1/b2_list_file_versions HTTP/1.1" 200 3998
 compare: 1/5 files   updated: 0 files   0 B   0 B/s               
DEBUG:b2.sync.policy:File test1.pdf.zipx: source time 1576518197000, dest time 1576517839000, diff 358000, threshold 0, diff > threshold True
DEBUG:root:scheduling action b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000) on bucket Bucket<d3b6cc26b5f305fb6cf30211,test-b2-sync-hidden,None>
DEBUG:b2.bucket:calling Bucket.download_file_by_name(self=Bucket<d3b6cc26b5f305fb6cf30211,test-b2-sync-hidden,None>, file_name='test_b2sync/test1.pdf.zipx', download_dest=<b2.download_dest.DownloadDestLocalFile object at 0x7f4615c6f2b0>, progress_listener=<b2.sync.report.SyncFileReporter object at 0x7f4615c6f278>, range_=None)
DEBUG:b2.sync.policy:File test2.pdf.zipx: source time 1576517839000, dest time 1576517839000, diff 0, threshold 0, diff > threshold False
DEBUG:b2.sync.policy:File test3.pdf.zipx: source time 1576517839000, dest time 1576517839000, diff 0, threshold 0, diff > threshold False
DEBUG:b2.sync.policy:File test4.pdf.zipx: source time 1576517839000, dest time 1576517839000, diff 0, threshold 0, diff > threshold False
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f001.backblazeb2.com:443
DEBUG:b2.sync.policy:File test5.pdf.zipx: source time 1576517839000, dest time 1576517839000, diff 0, threshold 0, diff > threshold False
DEBUG:urllib3.connectionpool:https://f001.backblazeb2.com:443 "GET /file/test-b2-sync-hidden/test_b2sync/test1.pdf.zipx HTTP/1.1" 404 132
ERROR:b2.sync.action:an exception occurred in a sync action
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 42, in run
    self.do_action(bucket, reporter)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/action.py", line 143, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/bucket.py", line 166, in download_file_by_name
    range_=range_,
  File "/usr/local/lib/python3.7/dist-packages/b2/session.py", line 38, in wrapper
    return f(api_url, account_auth_token, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/raw_api.py", line 210, in download_file_by_name
    url, account_auth_token_or_none, download_dest, range_=range_
  File "/usr/local/lib/python3.7/dist-packages/b2/raw_api.py", line 236, in _download_file_from_url
    with self.b2_http.get_content(url, request_headers) as response:
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 337, in get_content
    response = _translate_and_retry(do_get, try_count, None)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/usr/local/lib/python3.7/dist-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.FileNotPresent: File not present: 
b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000): FileNotPresent() File not present: 
 compare: 5/5 files   updated: 0/1 files   0 / 0 B   0 B/s
                                                          
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 1138, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.7/dist-packages/b2/console_tool.py", line 921, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python3.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/b2/sync/sync.py", line 220, in sync_folders
    raise CommandError('sync is incomplete')
b2.exception.CommandError: sync is incomplete
ERROR: sync is incomplete
INFO:b2.console_tool:\\ ========================================  exit=1  ======================================== //
```

With a new bucket and only 2 test files into it, make a first synchronization in any local folder, then tag a file as "hidden", and make a new synchronization to reproduce the issue.


Regards,

**Comment by ppolewicz** [comment]
```
DEBUG:b2.sync.policy:File test1.pdf.zipx: source time 1576518197000, dest time 1576517839000, diff 358000, threshold 0, diff > threshold True
DEBUG:root:scheduling action b2_download(test_b2sync/test1.pdf.zipx, 4_zd3b6cc26b5f305fb6cf30211_f109d149266e13445_d20191216_m174317_c001_v0001131_t0031, /volumes/data/shares/public/test_b2sync/test1.pdf.zipx, 1576518197000) on bucket Bucket<d3b6cc26b5f305fb6cf30211,test-b2-sync-hidden,None>
```
it looks like the policy manager thinks it is a good idea to retrieve a file that is hidden on the server. This operation then fails. The policy manager should not have made that choice.
