### ISSUE TITLE
How to sync large files with cli tools

### ISSUE THREAD

**Issue by kozicpetar** [Backblaze/B2_Command_Line_Tool#639]
Hi,

I can't find anywhere how can I sync large files.
With b2 sync large files failed and sync process failed.

I can list large files and remove but sync process failed with errors:

```
ERROR:b2sdk.b2http:_translate_errors has intercepted an unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 55, in _translate_errors
    response = fcn()
  File "/usr/local/lib/python2.7/dist-packages/b2sdk/b2http.py", line 304, in do_post
    data.seek(0)
  File "/usr/local/lib/python2.7/dist-packages/b2sdk/stream/wrapper.py", line 37, in seek
    return self.stream.seek(pos, whence)
  File "/usr/local/lib/python2.7/dist-packages/b2sdk/stream/range.py", line 45, in seek
    self.relative_pos = abs_pos - self.offset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
ERROR:b2.console_tool:ConsoleTool command error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1490, in run_command
    return command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1291, in run
    reporter=reporter,
  File "/usr/local/lib/python2.7/dist-packages/b2sdk/sync/sync.py", line 234, in sync_folders
    raise IncompleteSync('sync is incomplete')
```

OS: Ubuntu 19.10

Thank you.

**Comment by ppolewicz** [comment]
Hi

you've found a bug! We'll fix it tomorow. It seems to only affect python 2.7 users, so if you uninstall b2cli and install it from pip3, it should work.
