### ISSUE TITLE
b2sdk.exception.InvalidAuthToken: Invalid authorization token. Server said:  (bad_auth_token)

### ISSUE THREAD

**Issue by hvignesh18197** [Backblaze/B2_Command_Line_Tool#645]
C:\WINDOWS\system32> b2 authorize_account
Using https://api.backblazeb2.com
Backblaze application key ID: ****************
Backblaze application key:
ConsoleTool account authorization error
Traceback (most recent call last):
  File "b2\console_tool.py", line 315, in run
  File "lib\site-packages\logfury\v0_1\trace_call.py", line 84, in wrapper
  File "lib\site-packages\b2sdk\api.py", line 159, in authorize_account
  File "lib\site-packages\b2sdk\session.py", line 112, in authorize_account
  File "lib\site-packages\b2sdk\raw_api.py", line 306, in authorize_account
  File "lib\site-packages\b2sdk\raw_api.py", line 302, in _post_json
  File "lib\site-packages\b2sdk\b2http.py", line 345, in post_json_return_json
  File "lib\site-packages\b2sdk\b2http.py", line 311, in post_content_return_json
  File "lib\site-packages\b2sdk\b2http.py", line 123, in _translate_and_retry
  File "lib\site-packages\b2sdk\b2http.py", line 59, in _translate_errors
b2sdk.exception.InvalidAuthToken: Invalid authorization token. Server said:  (bad_auth_token)
ERROR: unable to authorize account: Invalid authorization token. Server said:  (bad_auth_token)

**Comment by ppolewicz** [comment]
`application key ID` / `application key` pair you have provided was incorrect. @mlech-reef could we please get a nicer error message in the CLI for this particular case?

**Comment by hvignesh18197** [comment]
> 
> 
> `application key ID` / `application key` pair you have provided was incorrect. @mlech-reef could we please get a nicer error message in the CLI for this particular case?

I have tried many times, it was perfectly right. But the same error

**Comment by ppolewicz** [comment]
@hvignesh18197 cay you say what happened? You no longer have a problem with this?

**Comment by stephane-klein** [comment]
@hvignesh18197 same error for me, what are your mistake ?
