### ISSUE TITLE
ConsoleTool unexpected exception  re.error: nothing to repeat at position 0

### ISSUE THREAD

**Issue by dmd** [Backblaze/B2_Command_Line_Tool#647]
The b2 cli app crashes for me.

What I'm trying to do is sync ONLY files in a directory that have the string '101' in their filename.

```
$ b2 sync --keepDays 30 --excludeRegex '*' --includeRegex '*101*' --dryRun /mnt/bigboy/dump b2://devhost-vzdump/dump
ConsoleTool unexpected exception
Traceback (most recent call last):
  File "b2/console_tool.py", line 1500, in run_command
  File "b2/console_tool.py", line 1282, in run
  File "b2/console_tool.py", line 1306, in get_policies_manager_from_args
  File "site-packages/b2sdk/sync/scan_policies.py", line 146, in __init__
  File "site-packages/b2sdk/sync/scan_policies.py", line 29, in __init__
  File "site-packages/b2sdk/sync/scan_policies.py", line 29, in <listcomp>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/re.py", line 250, in compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/re.py", line 302, in _compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_compile.py", line 764, in compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 948, in parse
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 443, in _parse_sub
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 668, in _parse
re.error: nothing to repeat at position 0
Traceback (most recent call last):
  File "b2/console_tool.py", line 1628, in <module>
  File "b2/console_tool.py", line 1613, in main
  File "b2/console_tool.py", line 1500, in run_command
  File "b2/console_tool.py", line 1282, in run
  File "b2/console_tool.py", line 1306, in get_policies_manager_from_args
  File "site-packages/b2sdk/sync/scan_policies.py", line 146, in __init__
  File "site-packages/b2sdk/sync/scan_policies.py", line 29, in __init__
  File "site-packages/b2sdk/sync/scan_policies.py", line 29, in <listcomp>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/re.py", line 250, in compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/re.py", line 302, in _compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_compile.py", line 764, in compile
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 948, in parse
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 443, in _parse_sub
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/sre_parse.py", line 668, in _parse
re.error: nothing to repeat at position 0
```

**Comment by ppolewicz** [comment]
Hey

You should use `.*101.*` because it is a regex, not a glob expression.


Best regards
Pawel

pt., 24 lip 2020, 20:30 użytkownik Daniel M. Drucker <
notifications@github.com> napisał:

**Comment by dmd** [comment]
Ah!

**Comment by dmd** [comment]
(Though probably "crashing" is the wrong thing to do here.)

**Comment by ppolewicz** [comment]
@mlech-reef could we please have a meaningful error message here instead of a stack trace? 🙏

**Comment by mlech-reef** [comment]
Will do

**Comment by mlech-reef** [comment]
Done in Backblaze/b2-sdk-python#225
