### ISSUE TITLE
getting error no module named six

### ISSUE THREAD

**Issue by YaPaY** [Backblaze/B2_Command_Line_Tool#648]
b2
Traceback (most recent call last):
  File "/usr/local/bin/b2", line 6, in <module>
    from b2.console_tool import main
  File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 25, in <module>
    import six
ImportError: No module named six

any idea?

**Comment by ppolewicz** [comment]
`sudo pip install six` to fix it.

how did you install b2 cli?
