### ISSUE TITLE
Some files are not syncing correctly

### ISSUE THREAD

**Issue by leopalazzi** [Backblaze/B2_Command_Line_Tool#681]
Hi,

When launching the sync command I have issue with some files :  

```
Traceback (most recent call last):
File "c:\users\leo.palazzi\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "c:\users\leo.palazzi\appdata\local\programs\python\python38\lib\site-packages\b2sdk\transfer\inbound\downloader\parallel.py", line 313, in run
for to_write in response.iter_content(chunk_size=self.chunk_size):
File "c:\users\leo.palazzi\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 752, in generate
raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)", ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
```

I have Python3.8 and latest B2 command line tool.

Thank you.

**Comment by ppolewicz** [comment]
Hey,

this is a problem with your network connection to the B2 cloud, not a bug in the code, but the error message could be better. I'm leaving this issue open so that someone can come and improve the error reporting, but I'm afraid that it won't help with your unstable network.

**Comment by mjurbanski-reef** [comment]
We have since improved error handling, but please reopen if you see this ugly traceback again in current version.
