### ISSUE TITLE
Cannot download large files with SSE-B2 encryption

### ISSUE THREAD

**Issue by redraskal** [Backblaze/B2_Command_Line_Tool#702]
I have a bucket with encrypted files (SSE-B2) and I noticed that every file over around 1GB fails to download.

I have attempted to download files through b2 download-file-by-id and through b2 sync. I also tried different amounts of threads on b2 sync from 1-16.

The error:
```
ERROR:b2sdk.sync.action:an exception occurred in a sync action  278 MB   3.90 MB/s
Traceback (most recent call last):
  File "b2sdk/sync/action.py", line 48, in run
  File "b2sdk/sync/action.py", line 269, in do_action
  File "logfury/v0_1/trace_call.py", line 84, in wrapper
  File "b2sdk/bucket.py", line 167, in download_file_by_id
  File "logfury/v0_1/trace_call.py", line 84, in wrapper
  File "b2sdk/api.py", line 245, in download_file_by_id
  File "logfury/v0_1/trace_call.py", line 84, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 128, in download_file_from_url
  File "b2sdk/transfer/inbound/download_manager.py", line 137, in _validate_download
b2sdk.exception.TruncatedOutput: only 0 of 2489007970 bytes read
```

The debug log:
```
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(0, 311125995), Range(0, 311125995))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(311125996, 622251991), Range(311125996, 622251991))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(622251992, 933377987), Range(622251992, 933377987))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(933377988, 1244503983), Range(933377988, 1244503983))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(1244503984, 1555629979), Range(1244503984, 1555629979))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(1555629980, 1866755976), Range(1555629980, 1866755976))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(1866755977, 2177881973), Range(1866755977, 2177881973))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:created part to download: PartToDownload(Range(2177881974, 2489007970), Range(2177881974, 2489007970))
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(311125996, 622251991) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(622251992, 933377987) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 4, bytes read already: 0. Getting range Range(0, 311125995) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(933377988, 1244503983) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(1244503984, 1555629979) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(1555629980, 1866755976) now.
DEBUG:urllib3.connectionpool:Resetting dropped connection: f001.backblazeb2.com
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(1866755977, 2177881973) now.
DEBUG:b2sdk.transfer.inbound.downloader.parallel:download attempts remaining: 5, bytes read already: 0. Getting range Range(2177881974, 2489007970) now.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (5): f001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (6): f001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (7): f001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (8): f001.backblazeb2.com:443
```

Some things to note:
- This was tested on multiple internet connections from 50Mbps to gigabit (different locations in the US)
- Cannot download through the S3 api
- Cannot stream the files through rclone
- Trying to stream the files through HTTP throws a content length mismatch error

**Comment by ppolewicz** [comment]
TBH if you are unable to download the file through S3 api, it looks like a temporary issue with the server, not with the client. Can you confirm it is still occuring?

**Comment by redraskal** [comment]
> TBH if you are unable to download the file through S3 api, it looks like a temporary issue with the server, not with the client. Can you confirm it is still occuring?

Correct, the issue is still occurring.

**Comment by ppolewicz** [comment]
Faced this myself when working on SSE-C. Escalated to Backblaze.

**Comment by lucymhdavies** [comment]
Oh, good to know it's not just me then.

Traceback looks to be referencing the same lines of code:

```
ERROR:b2sdk.sync.action:an exception occurred in a sync action  12 B/s
Traceback (most recent call last):
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/sync/action.py", line 48, in run
    self.do_action(bucket, reporter)
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/sync/action.py", line 269, in do_action
    bucket.download_file_by_id(
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/bucket.py", line 167, in download_file_by_id
    return self.api.download_file_by_id(
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/api.py", line 245, in download_file_by_id
    return self.services.download_manager.download_file_from_url(
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/transfer/inbound/download_manager.py", line 128, in download_file_from_url
    self._validate_download(
  File "/Users/strawb/Library/Python/3.8/lib/python/site-packages/b2sdk/transfer/inbound/download_manager.py", line 137, in _validate_download
    raise TruncatedOutput(bytes_read, metadata.content_length)
b2sdk.exception.TruncatedOutput: only 0 of 244398080 bytes read
```



In my case, if it makes a difference, this is the version installed with `pip` on darwin/arm64

```
$ b2 version
b2 command line tool, version 2.3.0
```

**Comment by ppolewicz** [comment]
Seems to happen only with large files with SSE-B2, non-encrypted large files are not affected, small files are not affected.

**Comment by redraskal** [comment]
> Seems to happen only with large files with SSE-B2, non-encrypted large files are not affected, small files are not affected.

Yep, that is correct from my findings. Seems to occur with SSE-B2 encrypted files maybe over 1GB?

**Comment by ppolewicz** [comment]
actually current version of b2 cli has a `--minPartSize` option, I think if you set it to 5GB then uploads will be slower but will use "small file upload" and that will work well (though I imagine server is going to fix this any moment now)

**Comment by redraskal** [comment]
Weird thing was I had no issues uploading, only downloading. I uploaded TBs of data, no errors

**Comment by johnlcox** [comment]
A fix has been deployed to the servers. You should be able to download these files now.

**Comment by redraskal** [comment]
SSE-B2 seems to be fixed on my end!

**Comment by ppolewicz** [comment]
it works for me too
