### ISSUE TITLE
Ubuntu dependences?

### ISSUE THREAD

**Issue by leonardoborlot** [Backblaze/B2_Command_Line_Tool#766]
Hi guys

Im trying to use the last version prom b2 CLI on Ubuntu 20:04. 

When I try to execute this b2-linux, I recive an error and this is the return.

```
Traceback (most recent call last):
  File "b2/console_tool.py", line 2448, in <module>
  File "b2/console_tool.py", line 2433, in main
  File "b2/console_tool.py", line 2224, in run_command
  File "argparse.py", line 1820, in parse_args
  File "argparse.py", line 1853, in parse_known_args
  File "argparse.py", line 2090, in _parse_known_args
  File "b2/arg_parser.py", line 80, in error
  File "argparse.py", line 2550, in print_help
  File "argparse.py", line 2556, in _print_message
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 1084: ordinal not in range(128)
[478] Failed to execute script 'console_tool' due to unhandled exception!

```

Theres any dependence or mandatory package then I need to install?

**Comment by leonardoborlot** [comment]
The Version 2.0.2 works very well. Bu the verion 3 don´t.

**Comment by ppolewicz** [comment]
oh. Can you please run the current version with `--verbose` parameter? It should output some diagnostic information that would help debugging this issue.

**Comment by mlech-reef** [comment]
@leonardoborlot check #755

**Comment by mlech-reef** [comment]
> The Version 2.0.2 works very well. Bu the verion 3 don´t.

Probably somewhere between these versions, someone have used UTF-8 characters in the main description.
