### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by joejanz** [Backblaze/B2_Command_Line_Tool#779]
I'm getting a RecursionError when I try to sync. Worked in the past, I don't remember when the last time it was that it worked, possibly a month or two ago. Python has been updated since then. I was getting the same error on a previous version of the b2 command line tool, before updating to the current 3.2.1.

Verbose output below (I removed two file names and 416 lines with file names):

```
[joe@papageno src]$ b2 sync --verbose --excludeAllSymlinks --skipNewer ~/photo/ b2://joe-photo/
INFO:b2.console_tool:// ========================================  3.2.1   ======================================== \\
DEBUG:b2.console_tool:platform is Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
DEBUG:b2.console_tool:Python version is CPython 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
DEBUG:b2.console_tool:b2sdk version is 1.14.1
DEBUG:b2.console_tool:locale is ('en_CA', 'UTF-8')
DEBUG:b2.console_tool:filesystem encoding is utf-8
INFO:b2.console_tool:starting command [b2.console_tool.Sync] with arguments: ['/home/joe/.local/bin/b2', 'sync', '--verbose', '--excludeAllSymlinks', '--skipNewer', '/home/joe/photo/', 'b2://joe-photo/']
DEBUG:b2sdk.transfer.outbound.upload_manager:calling UploadManager.set_thread_pool_size(self=<b2sdk.transfer.outbound.upload_manager.UploadManager object at 0x7f0429fc2230>, max_workers=10)
DEBUG:b2sdk.api:calling B2Api.check_bucket_name_restrictions(self=<b2sdk.v2.api.B2Api object at 0x7f042b6fe6e0>, bucket_name='joe-photo')
DEBUG:b2sdk.v2.api:calling Bucket(api=<b2sdk.v2.api.B2Api object at 0x7f042b6fe6e0>, id_='7d4c5f4ba6d905056906081a', name='joe-photo', type_=None, bucket_info=None, cors_rules=None, lifecycle_rules=None, revision=None, bucket_dict=None, options_set=None, default_server_side_encryption=<EncryptionSetting(EncryptionMode.UNKNOWN, None, None)>, default_retention=BucketRetentionSetting('unknown', None), is_file_lock_enabled=None)
DEBUG:b2sdk.api:calling Bucket(api=<b2sdk.v2.api.B2Api object at 0x7f042b6fe6e0>, id_='7d4c5f4ba6d905056906081a', name='joe-photo', type_=None, bucket_info=None, cors_rules=None, lifecycle_rules=None, revision=None, bucket_dict=None, options_set=None, default_server_side_encryption=<EncryptionSetting(EncryptionMode.UNKNOWN, None, None)>, default_retention=BucketRetentionSetting('unknown', None), is_file_lock_enabled=None)
DEBUG:b2sdk.bucket:calling Bucket.ls(self=Bucket<7d4c5f4ba6d905056906081a,joe-photo,None>, folder_to_list='', latest_only=False, recursive=True, fetch_count=10000)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api001.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://api001.backblazeb2.com:443 "POST /b2api/v2/b2_list_file_versions HTTP/1.1" 200 8969916
DEBUG:b2sdk.sync.policy:File [xxxx]: source time 1445115009085, dest time 1445115009085, diff 0, threshold 0, diff > threshold False
```
[ommitted 416 similar lines]
```
DEBUG:b2sdk.sync.policy:File [xxxx]: source time 1178596004000, dest time 1178596004000, diff 0, threshold 0, diff > threshold False
ERROR:b2.console_tool:ConsoleTool unexpected exception               
Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.10/site-packages/b2/console_tool.py", line 2235, in run_command
    return command.run(args)
  File "/home/joe/.local/lib/python3.10/site-packages/b2/console_tool.py", line 1871, in run
    synchronizer.sync_folders(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 249, in sync_folders
    for action in self._make_folder_sync_actions(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 298, in _make_folder_sync_actions
    for source_path, dest_path in zip_folders(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 76, in zip_folders
    current_a = next_or_none(iter_a)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 33, in next_or_none
    return next(iterator)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 131, in all_files
    yield from self._walk_relative_paths(self.root, '', reporter, policies_manager)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  [Previous line repeated 983 more times]
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 232, in _walk_relative_paths
    if policies_manager.should_exclude_local_directory(relative_file_path):
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/scan_policies.py", line 228, in should_exclude_local_directory
    return self._exclude_dir_set.matches(dir_path)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/scan_policies.py", line 47, in matches
    return any(c.match(s) is not None for c in self._compiled_list)
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/joe/.local/bin/b2", line 8, in <module>
    sys.exit(main())
  File "/home/joe/.local/lib/python3.10/site-packages/b2/console_tool.py", line 2433, in main
    exit_status = ct.run_command(sys.argv)
  File "/home/joe/.local/lib/python3.10/site-packages/b2/console_tool.py", line 2235, in run_command
    return command.run(args)
  File "/home/joe/.local/lib/python3.10/site-packages/b2/console_tool.py", line 1871, in run
    synchronizer.sync_folders(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 249, in sync_folders
    for action in self._make_folder_sync_actions(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 298, in _make_folder_sync_actions
    for source_path, dest_path in zip_folders(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 76, in zip_folders
    current_a = next_or_none(iter_a)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/sync.py", line 33, in next_or_none
    return next(iterator)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 131, in all_files
    yield from self._walk_relative_paths(self.root, '', reporter, policies_manager)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 243, in _walk_relative_paths
    for subdir_file in self._walk_relative_paths(
  [Previous line repeated 983 more times]
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/folder.py", line 232, in _walk_relative_paths
    if policies_manager.should_exclude_local_directory(relative_file_path):
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/scan_policies.py", line 228, in should_exclude_local_directory
    return self._exclude_dir_set.matches(dir_path)
  File "/home/joe/.local/lib/python3.10/site-packages/b2sdk/sync/scan_policies.py", line 47, in matches
    return any(c.match(s) is not None for c in self._compiled_list)
RecursionError: maximum recursion depth exceeded`
```

**Comment by ppolewicz** [comment]
It seems that you have a symlink that points to its ancestor or some other
loopy scenario. There should be a sync switch to skip symlinks, you may
want to try that.

**Comment by joejanz** [comment]
If you mean `--excludeAllSymlinks`, I do always include that.

**Comment by joejanz** [comment]
Doesn't hang, but that did bring to my attention a very deeply nested series of subfolders (about 1200 deep), and after deleting that, the problem I was having with the b2 command went away.

Thanks for your help!
