### ISSUE TITLE
ERROR: Incomplete sync: sync is incomplete ( Already failed: 500 internal_error incident id 730b04157be6-adbb001b0523ff77)

### ISSUE THREAD

**Issue by predkambrij** [Backblaze/B2_Command_Line_Tool#832]
Hello.

I'm getting errors when uploading to backblaze. The following is in the logs. Is there anything I can do to get it work?

Software version:

    # b2 version
    b2 command line tool, version 3.1.0

Logs:

    updated: 0/1 files   927 / 928 MB   861 kB/s ^M
    compare: 1/1 files   updated: 0/1 files   927 / 928 MB   862 kB/s ^M
    compare: 1/1 files   updated: 0/1 files   928 / 928 MB   862 kB/s ^M
    compare: 1/1 files   updated: 0/1 files   928 / 928 MB   862 kB/s ^M
    compare: 1/1 files   updated: 0/1 files   928 / 928 MB   862 kB/s ^M
    compare: 1/1 files   updated: 1/1 files   928 / 928 MB   862 kB/s ^M

    ERROR:b2sdk.sync.action:an exception occurred in a sync action
    Traceback (most recent call last):
      File "b2sdk/sync/action.py", line 49, in run
      File "b2sdk/sync/action.py", line 140, in do_action
      File "logfury/_logfury/trace_call.py", line 86, in wrapper
      File "b2sdk/bucket.py", line 528, in upload
      File "logfury/_logfury/trace_call.py", line 86, in wrapper
      File "b2sdk/bucket.py", line 578, in create_file
      File "b2sdk/bucket.py", line 662, in _create_file
      File "logfury/_logfury/trace_call.py", line 86, in wrapper
      File "b2sdk/transfer/emerge/emerger.py", line 71, in emerge
      File "b2sdk/transfer/emerge/executor.py", line 72, in execute_emerge_plan
      File "b2sdk/transfer/emerge/executor.py", line 217, in execute_plan
      File "b2sdk/transfer/emerge/executor.py", line 217, in <listcomp>
      File "b2sdk/utils/__init__.py", line 38, in interruptible_get_result
      File "concurrent/futures/_base.py", line 445, in result
      File "concurrent/futures/_base.py", line 390, in __get_result
      File "concurrent/futures/thread.py", line 52, in run
      File "b2sdk/transfer/outbound/upload_manager.py", line 168, in _upload_part
    b2sdk.exception.AlreadyFailed: Already failed: 500 internal_error incident id 730b04157be6-adbb001b0523ff77
    b2_upload(/opt/backuptmp/tmp/datafile.gz.gpg, autobackup/BackupProd4/datafile.gz.gpg, 1665104760873): AlreadyFailed('500 internal_error incident id 730b04157be6-adbb001b0523ff77') Already failed: 500 internal_error incident id 730b04157be6-adbb001b0523ff77

     compare: 1/1 files   updated: 1/1 files   928 / 928 MB   862 kB/s^M                                                                  ^M

    ERROR: Incomplete sync: sync is incomplete
    command /usr/local/bin/b2 sync /opt/backuptmp/tmp b2://42dbs-bw/autobackup/BackupProd4 failed with 1

Best regards,
Alojzij

**Comment by ppolewicz** [comment]
Hey,

this is a temporary server-side issue which, sadly, lasted for longer than patience of cli version 3.1.0. I do recommend an upgrade - the new version is more patient and thus more likely to successfully complete an upload even if the server has a hiccup.
