### ISSUE TITLE
Exception in sync action...

### ISSUE THREAD

**Issue by mgajda** [Backblaze/B2_Command_Line_Tool#854]
For many files I get the following exception:
```
ERROR:b2.sync.action:an exception occurred in a sync actionkB/s
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/b2/sync/action.py", line 42, in run
    self.do_action(bucket, reporter)
  File "/usr/lib/python3/dist-packages/b2/sync/action.py", line 143, in do_action
    bucket.download_file_by_name(self.b2_file_name, download_dest, SyncFileReporter(reporter))
  File "/usr/lib/python3/dist-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/lib/python3/dist-packages/b2/bucket.py", line 167, in download_file_by_name
    return self.api.transferer.download_file_from_url(
  File "/usr/lib/python3/dist-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/lib/python3/dist-packages/b2/transferer/transferer.py", line 107, in download_file_from_url
    bytes_read, actual_sha1 = strategy.download(
  File "/usr/lib/python3/dist-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/lib/python3/dist-packages/b2/transferer/simple.py", line 24, in download
    actual_size = self._get_remote_range(response, metadata).size()
  File "/usr/lib/python3/dist-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/lib/python3/dist-packages/b2/transferer/abstract.py", line 51, in _get_remote_range
    return Range(0, metadata.content_length - 1)
  File "/usr/lib/python3/dist-packages/b2/transferer/range.py", line 18, in __init__
    assert 0 <= start <= end
AssertionError
```

The version information:
```
$ apt policy backblaze-b2
backblaze-b2:
  Installed: 1.3.8-5
  Candidate: 1.3.8-5
  Version table:
 *** 1.3.8-5 500
        500 http://pl.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://pl.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status
$ backblaze-b2 version
b2 command line tool, version 1.3.8
```

**Comment by ppolewicz** [comment]
This version is very, very old. Please try to use something more modern - there is a good chance that we've fixed whatever this bug was years ago.

We are trying to work with Debian to get a newer version on their platform but it's a dependency hell.

**Comment by robinp** [comment]
Same with Ubuntu stock. Workaround based on pythonic install instructions:

```
mkdir b2; cd b2; apt install virtualenv; virtualenv .; ./bin/pip3 install b2[full]; ./bin/b2 sync …
```

**Comment by mjurbanski-reef** [comment]
Let us know if issue appears again
