### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 1325: ordinal not in range(128)

### ISSUE THREAD

**Issue by Churator** [Backblaze/B2_Command_Line_Tool#914]
Trying to use b2 cli, but getting this error (Installed via wget to the b2-linux from github)

my locale:
# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

And full error
# ./b2
Traceback (most recent call last):
  File "b2/console_tool.py", line 3545, in <module>
  File "b2/console_tool.py", line 3530, in main
  File "b2/console_tool.py", line 3370, in run_command
  File "argparse.py", line 1869, in parse_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2142, in _parse_known_args
  File "b2/arg_parser.py", line 87, in error
  File "argparse.py", line 2601, in print_help
  File "argparse.py", line 2607, in _print_message
UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 1325: ordinal not in range(128)

**Comment by Churator** [comment]
I've figured out it caused when using lxc-attach in Proxmox. directly connecting to the ssh console solves it.
