### ISSUE TITLE
Error when resuming upload

### ISSUE THREAD

**Issue by joelachankeng** [Backblaze/B2_Command_Line_Tool#934]
My PC froze while uploading a file and I had to restart. 
When I tried to resume the upload, I got an error. 

The file is 1TB.

```
Z:\>b2 list-unfinished-large-files JA-NAS-backup
4_z1eb9849803f3493382ba0e16_f216cbd573d9e0c98_d20231021_m082606_c005_v0501013_t0010_u01697876766961 backup.10.15.2023.rar application/x-rar-compressed large_file_sha1=b6cea07a0650318de671fc3b9cfc941d8fd21249 src_last_modified_millis=1697424777477

Z:\>b2 list-parts 4_z1eb9849803f3493382ba0e16_f216cbd573d9e0c98_d20231021_m082606_c005_v0501013_t0010_u01697876766961
    1  164926745  5e732550c1317f59ecee40d0d09fd278cd233152
    2  164926745  4e7268b53cb00b783bff034ab19a5bf24bd9f53e
    3  164926745  e7f3569e2df315eaa1188116b3af889ebe730485
    4  164926745  c0529074d6e4151462e3a3e4344b31fcca191ea3
    5  164926745  0b6b72f29f30147f6d94d2ed0c96ae458a702a6e
    6  164926745  824a78d5eae549afe2d1849182053e800b7fa63d
    7  164926745  3cfdb7dce08523434587276266cf285519230abc
    8  164926745  3aac08772e5caba0923a2d4fba6d0bea9b963889
    9  164926745  67eb6707172460a35e3ddf625a545e1cf9eea80d
   10  164926745  95160d724aeb035366abbe36f63993e4c5011d69
   11  164926745  644fed7f0a062f50138df8a3da1eca271ebf790c
   12  164926745  00ab29d4641eeee63cc3944152d37971a87584d8
   13  164926745  66e73d8aee742638e65ed3ab3e9b5ad3376b5e80
   14  164926745  dce7f9fd37c7d4241df1d28b6dbadf42def83f28
   15  164926745  7a65c3985895fdbaac3ec8170281ed2f3bec7ebf
   16  164926745  e27072ea75370748713dd4cd270d2b7b4374a3e9
   17  164926745  441a38f89865292056e0fe1570803e30717a4b67
   18  164926745  412b0b083614bb977b95cabf634f29a5e72c2b1f
   19  164926745  ebb3bfa0c80ae41b5a4153b9b1df652d432fe98d
   20  164926745  844920f5d764f46e46a72970065e8949737c417b
   21  164926745  991663daccf3ff4bf242e2caa4034d1452c7cfc2
   22  164926745  a8a95ac22a91c868bd0d3598302f81900f74822c
   23  164926745  f5e3c224e7b46c9b8a6c8364362ac3c6317a9d7d
   24  164926745  1941728d6b490ea8f82b9f255834837cc95db5cc
   25  164926745  90d8f115f4ddc3f3e2c1c5bcc62bcd10c072f39a
   26  164926745  663dad29f3a61efd7acb0bcb7d1a130a879e9ed4
   27  164926745  6d3f9a3d12231d269c77fc84f7a38731f5637a26
   28  164926745  fd9be57c4db80988c6548da6527257594c8c6368
   29  164926745  d0c525ef695587b0d729bcd1585da8e382e259e9
   30  164926745  9b20effee38f6be40773dfc1c68462af16b1f890
   31  164926745  1d73328cd285145001b5f45874a340e62ee907da
   32  164926745  9827fac1965033d3d344e233627fc22c0ca7095b
   33  164926745  3ba48aeb7f3aa7d533c6d6f7a37a852e19a01d9c
   34  164926745  8f13fc172d78f482ecccbd67e136eeda6f8fca2b
   35  164926745  aecdea9d9b6938c5597ae2002db2c6de0d197e2b
   36  164926745  689000e76c8370f123fd644087a2cd63dfae3d31
   37  164926745  c1a666882a51e2e522c46f21118a57bc630de178
   38  164926745  a070f7d69b8dd714fcd796ada678c1899fadeff3
   39  164926745  f58657b61775b01029459da60a459818579b974d
   40  164926745  5490feb87d549f8cadbcd6210980fbcec82bd3b6
   41  164926745  26f3371e5fa32f098967c394d44ccb0fd709385e
   42  164926745  e34acfce1ac79ed56f1910da2c0ab05b6761d7ff
   43  164926745  2778a2a1ffda907d37a24e2270efb6c946c6c1ad
   44  164926745  918e17ba66e8b096ef6b7cdda83883ebeb03d8ed
   45  164926745  5404703b888101cc90e9c5bac8c1906cf86db340
   46  164926745  1067e8eea4f234a5cb86b0c23cf770899c276ea2
   47  164926745  b75aee74aeac5563cf63fd5a0392f5f8ab826fbb
   48  164926745  1044a3ef6103fcb57765c030980f5b4ef99a2257
   49  164926745  fcf4e1092a8c45dcb72a8ebdf117c1330265fb26
   50  164926745  0ce47cac0a4674b2364e053ed99e0705dbd5846c
   51  164926745  2c0edcc489f3b6edf74b2f390d712441f9444e73
   52  164926745  9084c6ea1d401a8fd7129fdb1937be734530752b
   53  164926745  63d80d144108af4504491f38b09b0f1be73628cf
   54  164926745  efe433ed98788d4844a88f2b34a09636433beda5
   55  164926745  a20284567af46ce69af78201f54fae999de6d0a8
   56  164926745  6cf6e82d81899afad3f7c7242c7aeacfc15cac96
   57  164926745  03e68110b2f5f890d6260743c25a7fcd825562a9
   58  164926745  26947a156b8b00dd8da3bc4b778e39524529bcad
   59  164926745  bb0191d4a6629cf971513c8616698f9567f2bf5d
   60  164926745  e637e94db622efe244418047a321ce3cc5ff02c1
   61  164926745  f65063cb15b4a23d0c34a719ee312fb46d94c941
   62  164926745  6c382b153f9cf0513014aff0956a8b7a8d9a6d07
   63  164926745  4328d93fa7e7e9b0eba13e6ffab0ee41990ff6d5
   64  164926745  ac504072236fba18dc49d1188116ff61f9bd822c
   65  164926745  d848fabf1ca9e6a9bd4ce530d73c50de738c3d88
   66  164926745  21b6f7afde773be25458691d188c9f266b650625
   67  164926745  e8d093a28f0b43837fecb04a8ec8d810d2e8ebaa
   68  164926745  8985762c962ec7d20cc37bbcd62159217a5740d2
   69  164926745  0605a818d23a311ea55f934ff62c3a5432e4020c
   70  164926745  95c313cd3c496152fec9f34fc727e3198bfa5535
   71  164926745  da766a46e62d9bb77fcb58d7bb7f8827c1ce21cc
   72  164926745  38bbfe10a65961ddd431c4e479cca2d7eda7bd3e
   73  164926745  a9f080135ac17bf152962236b23afe5032d275d2
   74  164926745  ace670e5a5502e513acd11e4252a02aa342f0f34
   75  164926745  212989d191806e92228150b26904030afe946f25
   76  164926745  b038f66981444a751e9bfe00414c01f3c9f7dee3
   77  164926745  1387158dd7d73de9262a5f776b093746f06a37c3
   78  164926745  e26c0c898b418c3d927865ddb2b24ff7227d757e
   79  164926745  4f15ef8b5cc944aed6271388e15f8ffbb021f1ad
   80  164926745  123558712fc6c2ee838c6d5e84d374af73596ff7
   81  164926745  3ea81b05856153a721415eecabc92a51885159b2
   82  164926745  68d19f52613a37c93947acf5edf727c675fb06fb
   83  164926745  d7f5a92a09be4ba884b815c68d66d192b12e786f
   84  164926745  36b3d14142438720dfd43e30760a3cbf9202d654
   85  164926745  95cd6bc03afe93fbf0e30a63ee380e160c5ede71
   86  164926745  c6f7930a5a40791fbc60543c7c4e1ca75f7551e0
   87  164926745  3eb6f0227343d3f6d98d7767a846e42245f4126c
   88  164926745  bfe671492a2ae8dc7a04b55b7fbc74f5299a62f4
   89  164926745  fb7d79a851d6b6249389f3c6c83022dda5543e38
   90  164926745  21683fac74d0e879980b70878ce9aef20fbc652e
   91  164926745  6b644a8945bdae76d0af756bb72856685bd36aa7
   92  164926745  a3b3200170621c3f6cb9918e668639db578643de
   93  164926745  04d5b21e652a25eac55442a8a3057dcf6edf4bde
   94  164926745  7391df39d1d2edec8eb386a96663eda241afe1ad
   95  164926745  8ef054f08657f549cdc12fe22f2e97fdd7e81702
   96  164926745  2dd2d92c09ff399fff6ca6c828956c7de531236e
   97  164926745  4c5a35afb7235bfd5551a5c4dbcf8c411bd2437f
   98  164926745  610bbbd630da88f141a82e1c35df9cc11a9f20c7
   99  164926745  19de0ab991aca21d72722ba301960c2510f5ed09
  100  164926745  6f854b15b35cdab9960529dc12489487816fa2e2
  101  164926745  226cff6207171e18f6827dde3a8ff7db1d2d83cd
  102  164926745  6b08b57435f71226c60a85df2db193b107329745
  103  164926745  0d601d0c3edf08fec9f0cb248fcc3cb4ea9df67c
  104  164926745  b7deb93890205b112fd849e6808e16875f949c04
  105  164926745  3afc13d86149ad371d48ee89a2b14ce9e537d0a7
  106  164926745  cc471a5143c57e86121f86977f7efdae2c469c26
  107  164926745  8977b859e6079ac6079961c1b5d06fc22ac1a52c
  108  164926745  06c2228f1db073ca94575722f9bdd8b75b63aab6
  109  164926745  71935afb416062613287ad027fbf2451daef1bab
  110  164926745  1ddc93d1df6f38d53841da3666f8f917c79293b0
  111  164926745  cde9fa8f7a640628522323bbca310b583d2437cd
  112  164926745  5cd7d48398c555790ede8b0127c23b6865fdf5a3
  113  164926745  1257ca105e21e05390be454eb12abde7ae6c53ed
  114  164926745  e48e039c211673cddb2c10655d3aaf24d9471ccc
  115  164926745  6887e4515211a597abefaf85642ebfbf965569b5
  116  164926745  9eabde333698446bfc0095455f932029cf877c77
  117  164926745  77307b8e7fa0fc2927c6d980ef62e41061a1e095
  118  164926745  0d88e8faff904124d75935476657bfa5269e1057
  119  164926745  7492a2189df1a4b9c9afd7ca36fad259805eca67
  120  164926745  cc8780959e69ae2832b8f6c27cf46cb24a7c0e52
  121  164926745  e392a1f9386e0193b46115593c56a37075f4e559
  122  164926745  fc79ffed586970c096e43a2d27b0846167a2cbcc
  123  164926745  09b1a79ffd4eda66fae26fc93a8937eab1a432a1
  124  164926745  a34d6c5a5946890477e7b1419cff74c1762b807e
  125  164926745  73e1b0c7ddb7451f517e4b126a0c8839b01ceb7b
  126  164926745  06413b5ef0a096c5514921c79d187824b1c298df
  127  164926745  1a68c1b1e7b38cc78ed813e01b0b6873bda4b392
  128  164926745  7c5f3ea94ea8c2c10b338ef076683d1e54d8656b
  129  164926745  4608b888c25de59b737fb0b02d864f1fc53398c3
  130  164926745  ff81b7e3a70222c7ced37afb023fa377bfe36940
  131  164926745  e4db29e373f5f54bf66fc80f925b41e9ce8adc2d
  132  164926745  6180b426b4613e4d6c05a443737aa6d0db045242
  133  164926745  6f7595c8a48f732c0f1a06bd722ff145787c4fa3
  134  164926745  98c4d3da05e166eb70373290a9952c4b3c4d57e7
  135  164926745  9e7e40ee439e3d8e7799c4eadef29add623e3501
  136  164926745  b73b468c4f072ea8b198b355bc08f8ced5fe8789
  137  164926745  83b8932bc2480d2de51e0ddf329f8cc54eaaf3de
  138  164926745  2aa128e65f4fe4b51fc5c0ff8b854b5b5fdfa9cb
  139  164926745  2a5fb0df78eeef5a2e155eac9fa0ee99977b4c8d
  140  164926745  c8ea6048ca99be2793b5be2109f1923f3f09116c
  141  164926745  27cd932af33d6d0154744c58e381fa61b9a0495d
  142  164926745  a1fd7b77f8217bde0e5dc22c8e30ae1d02f80199
  143  164926745  b510427e5a0a0b584ba3a96a93b7a5ab0820e9e0
  144  164926745  bec4036339288e9d13b5d3b1ecc8c988b0b3a5ab
  145  164926745  209e673beedf71a879431e4783da82362dc4cf44
  146  164926745  c988c244f322107b9dcbe7bfd97880a4d9a9fa39
  147  164926745  fd3ee608bfb790679897fd61c8925d0bf5e21c2e
  148  164926745  446d4e66d7c68b29150a5b4f5ef4c73e7d4dc7d5
  149  164926745  ae09f007dd62bb38f20aa6e5e78418a9ff6a1220
  150  164926745  60acf9d2d0d64c065224dde662e51a8a7a67ffdc
  151  164926745  3a067f792e87188df3a51e5103ebd8deafaca7fd
  152  164926745  6e3958f9086e18582b99bb206ec2f5ca54ba3974
  153  164926745  b7435c24efcd1d8841d67f8b7c02e26708e62065
  154  164926745  bfd2ab05579f67f3c16b699bd926fb1494b4e033
  155  164926745  3f9f928379263f01644d55c038b267f498c6502c
  156  164926745  6c3b6e09b38d77dee51513811e66c05139794dbe
  157  164926745  6af7a0505bc5fc78158b0ee33787e3ad10c3e4d7
  158  164926745  adf958fb275a6a7965fc05ea3610dc1f1571213c
  159  164926745  af300a5441da8ef0b8bc8aebbb46fc58acb423fe
  160  164926745  007b301d3f14b97bd07074a6be9ed15beabca740
  161  164926745  d1fcbd7d8bb09bd4c4ca9e7f6386cec3cd2de03e
  162  164926745  01a70b5bf0fbafa8a0cc454d9734ffcf8831d8be
  163  164926745  9316f707beb425c50b512c590183cd4cc09b194a
  164  164926745  5d17c8271e425eebe07696036424e4f2a642130f
  165  164926745  c09a20ac0dd07d3a7e322c1cd8bc0bcd14599d15
  166  164926745  e46f8c671a0b8a4642fee214b5e3d36e6acf2d93
  167  164926745  86cad0bb0029fb8ca02cdd067e7877681da40e02
  168  164926745  51787c287d88f3660774979701d3a8f3796fb45d
  169  164926745  2d55acc7406a0a7d9832c1d14c387b78aa0081c8
  170  164926745  84dc75c60535703d3c6ac8e97d193f2301b1f05c
  171  164926745  fc2a177c0bf842ae16b727fe286646c42349a721
  172  164926745  67736f6a503a2fa11e0e8ae397bfb6ecd92d372a
  173  164926745  9b00b8c3b6852f9b9fa630cbc0f1264f24f7ee25
  174  164926745  982c81735cadbd2db6b163d9dc7379923846f9a0
  175  164926745  99223e8e1469bad94ca897cba1d78acedb810f44
  176  164926745  6a3a594b430065677c8b9cdf0293833c2b0c3b25
  177  164926745  6c4b20595e674db76969bcc90ed8ea2bd7bb4acd
  178  164926745  23ae84944714a638a7ee177533a237dc8db6559d
  179  164926745  86beddbb3df518939d1d3f1f524f36e05b5839da
  180  164926745  d03b01681ae6ed9d8933634f9259875a7c65e4fd
  181  164926745  86f66e18f98ac210b38de23b8fb0fc39f0f6427c
  182  164926745  98b2d533dfb4143920cbaa8a17d2a9a440397947
  183  164926745  7453f7c645ecc17c8688d36b68539d121f35d569
  184  164926745  bab5690db7501115acefda78e24a9b0b74c76770
  185  164926745  b5788eba0c585d25acdce9308581355a4f613902
  186  164926745  80a4ae8f08f76c47fb335bf83bfc1395ebcf1489
  187  164926745  6c901023a019bbe7d0dbe3844ced526b46267d0f
  188  164926745  497a5b716de893d173509951b75a26bb3da95d44
  189  164926745  368af361e72e1e3bf22208f5d711b14c23a1b2f2
  190  164926745  20a89b56bbc03feb1ad9544bfa9ebdcfceb8df00
  191  164926745  a2e9a22239f34dcd89c096b4f617c2712481c607
  192  164926745  f70569cdec90b26603ebb4f539ca6c036b6e741d
  193  164926745  37c89a96a29eb4777c8c5c0319fdaeedfa359e6c
  194  164926745  18ce8a9d549ece3fa7cb88f76834839f69a49e20
  195  164926745  28463b211659aceb0c9f9165d52af4a4c9de1b46
  196  164926745  cd32e7741575640bcf8a6d3c8a3faace59386947
  197  164926745  881e8cf65891550e90f8d1e8debf6b0e511e1158
  198  164926745  6d9d3ce29d865add943dbbef79e307f68fde15b5
  199  164926745  6edce933e603f54dd54fb12779532a60b109f45f
  200  164926745  46dd789474c16aeac3321444ee774cb28eb99477
  201  164926745  2d1bed2fc2e7ecbe47622c8922edd5db36e9d4f4
  202  164926745  5c48ca9b2e1fd19bb7fdbf2749c2eda1507eccbb
  203  164926745  1d509838a0161b78fc990264a054def4ccd8238e
  204  164926745  d4d06c0a7eea9688bdcf51e0494f0051a78e40b1
  205  164926745  4087c2d4d7375630ca53aa12d82384a7b0912a5a
  206  164926745  f69250c81cb014b36ee90f499abc3d2b1344a606
  207  164926745  59ed42aabb6335ef879bd6595c4520e753d98d2d
  208  164926745  8d33910f63c118c3fa0d4c44ce3aba8299c78bb3
  209  164926745  d43aef0d2cbef67e0b3fb0a0429e08d68172db69
  210  164926745  06081e132827e291349f4cbdd0d67d585448af69
  211  164926745  62c6bb87da2a8f2983aa3d02f6d958b2a9608812
  212  164926745  9c634ae8474741b465be7408ed622b79a0f8b3e8
  213  164926745  6faf2701da5f28b54bb742c8d0f073e9fd5aa131
  214  164926745  bf1cdcddf3235fcba48af10c9aa63bd3df33fffd

Z:\>b2 upload-file --info src_last_modified_millis=1697424777477 --minPartSize 164926745 JA-NAS-backup backup.10.15.2023.rar backup.10.15.2023.rar
Traceback (most recent call last):
  File "b2\console_tool.py", line 2937, in execute_operation
  File "b2\console_tool.py", line 2877, in get_input_stream
UploadFileMixin.NotAnInputStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "b2\console_tool.py", line 3904, in <module>
  File "b2\console_tool.py", line 3889, in main
  File "b2\console_tool.py", line 3772, in run_command
  File "b2\console_tool.py", line 2813, in run
  File "b2\console_tool.py", line 2939, in execute_operation
  File "logfury\_logfury\trace_call.py", line 86, in wrapper
  File "b2sdk\version_utils.py", line 116, in wrapper
  File "b2sdk\v2\bucket.py", line 83, in upload_local_file
  File "logfury\_logfury\trace_call.py", line 86, in wrapper
  File "b2sdk\bucket.py", line 592, in upload_local_file
  File "logfury\_logfury\trace_call.py", line 86, in wrapper
  File "b2sdk\bucket.py", line 1018, in concatenate
  File "logfury\_logfury\trace_call.py", line 86, in wrapper
  File "b2sdk\bucket.py", line 842, in create_file
  File "b2sdk\bucket.py", line 953, in _create_file
  File "logfury\_logfury\trace_call.py", line 86, in wrapper
  File "b2sdk\transfer\emerge\emerger.py", line 177, in emerge
  File "b2sdk\transfer\emerge\emerger.py", line 93, in _emerge
  File "b2sdk\transfer\emerge\emerger.py", line 336, in get_emerge_planner
  File "b2sdk\transfer\emerge\planner\planner.py", line 118, in from_account_info
  File "b2sdk\transfer\emerge\planner\planner.py", line 97, in __init__
AssertionError
[11176] Failed to execute script 'console_tool' due to unhandled exception!
```

How do I resume the upload?

**Comment by jsuchan-reef** [comment]
Hi,
thanks for the report.
This approach should generally work, but the error happened because the value of `--minPartSize` you specified is too big (164MB), exceeding the values of "recommended part size", which is 100 MB.

We'll improve the behaviour to make it more obvious what went wrong.

**Comment by jsuchan-reef** [comment]
the behaviour is improved in the latest version of b2sdk (1.28.0)

**Comment by mjurbanski-reef** [comment]
The more sensible error has been implemented in b2sdk 1.28.0 and thus, `b2` CLI 3.14.0 .
