### ISSUE TITLE
Issue with b2 sync :: KeyError: 'content-length'

### ISSUE THREAD

**Issue by wmr-trevor** [Backblaze/B2_Command_Line_Tool#984]
I am recently getting this issue when running a b2 sync. Specifically when syncing from b2:// to local machine and it seems to only effect html files.

What I've tried:
- I was able to download this exact file from the browser with no issues.
- I've updated the client that is downloading the files
- I tried re-running the sync to b2:// with `--compareVersions size`

```
ERROR:b2sdk.sync.action:an exception occurred in a sync actionfiles   11.4 GB   6.21 MB/s
Traceback (most recent call last):
  File "b2sdk/sync/action.py", line 54, in run
  File "b2sdk/sync/action.py", line 325, in do_action
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 254, in download_file_by_id
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/api.py", line 294, in download_file_by_id
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
b2_download(quotes/{QUOTE_ID}/emails/{EMAIL_ID}/email.html, {RANDOM_STRING__LENGTH_99}, /mnt/storage/uploads/quotes/{QUOTE_ID}/emails/{EMAIL_ID}/email.html, 1681398331627): KeyError('content-length') 'content-length'
```

**Comment by ppolewicz** [comment]
Hey @wmr-trevor, thank you for the bug report.

How did you upload the files? Was the upload done by B2 CLI or was it through S3 interface or something?

**Comment by wmr-trevor** [comment]
The files are uploaded with
`b2 sync --profile uploads $LOCAL_UPLOAD_DIR b2://wmr-app-uploads/`
and downloaded with
`b2 sync --profile uploads --downloadThreads 30 --skipNewer b2://wmr-app-uploads/ /mnt/storage/uploads/`

We have a setup that our production server syncs the uploads to b2 as a backup and staging servers download to validate that the backups are functional.

**Comment by wmr-trevor** [comment]
Another thing I did just try is running the `b2 download-file` command. Fails in a similar way.

I replaced the {QUOTE_ID} and {EMAIL_ID} values to make it easier to read.
```shell
b2 download-file --profile uploads b2://wmr-app-uploads/quotes/{QUOTE_ID}/emails/{EMAIL_ID}/email.html ./email.html
Traceback (most recent call last):
  File "b2/console_tool.py", line 4163, in <module>
  File "b2/console_tool.py", line 4148, in main
  File "b2/console_tool.py", line 4050, in run_command
  File "b2/console_tool.py", line 835, in run
  File "b2/console_tool.py", line 1685, in _run
  File "functools.py", line 946, in _method
  File "b2/_utils/uri.py", line 134, in _
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 281, in download_file_by_name
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
[1196968] Failed to execute script 'console_tool' due to unhandled exception!
```

**Comment by ppolewicz** [comment]
Could you please run that `b2 download-file` command again but add `--verbose` to get more diagnostic info? It could really help with debugging the issue you are facing.

**Comment by wmr-trevor** [comment]
Certainly. Just let me know if you need anything else.

```shell
b2 download-file --profile uploads --verbose b2://wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html ./email.html
INFO:__main__:// ========================================  3.15.0  ======================================== \\
DEBUG:__main__:platform is Linux-5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.36
DEBUG:__main__:Python version is CPython 3.12.0 (main, Nov 29 2023, 03:12:07) [GCC 12.2.0]
DEBUG:__main__:b2sdk version is 1.28.0
DEBUG:__main__:locale is ('C', 'UTF-8')
DEBUG:__main__:filesystem encoding is utf-8
DEBUG:b2sdk.account_info.sqlite_account_info:calling SqliteAccountInfo._get_user_account_info_path(cls=<class 'b2sdk.account_info.sqlite_account_info.SqliteAccountInfo'>, file_name=None, profile='uploads')
DEBUG:b2sdk.account_info.sqlite_account_info:calling SqliteAccountInfo._get_xdg_config_path(cls=<class 'b2sdk.account_info.sqlite_account_info.SqliteAccountInfo'>)
DEBUG:b2sdk.account_info.sqlite_account_info:SqliteAccountInfo file path to use: /home/trevor/.config/b2/db-uploads.sqlite
DEBUG:b2sdk.account_info.upload_url_pool:calling UploadUrlPool()
DEBUG:b2sdk.account_info.upload_url_pool:calling UploadUrlPool()
DEBUG:b2sdk.account_info.upload_url_pool:calling UploadUrlPool()
DEBUG:b2sdk.account_info.upload_url_pool:calling UploadUrlPool()
DEBUG:b2sdk.v2.api:calling B2Session(account_info=<b2sdk.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7fe44338b5f0>, cache=<b2sdk.cache.AuthInfoCache object at 0x7fe44338a300>, api_config=<b2sdk.api_config.B2HttpApiConfig object at 0x7fe443388f80>)
DEBUG:b2sdk.api:calling B2Session(account_info=<b2sdk.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7fe44338b5f0>, cache=<b2sdk.cache.AuthInfoCache object at 0x7fe44338a300>, api_config=<b2sdk.api_config.B2HttpApiConfig object at 0x7fe443388f80>)
DEBUG:b2sdk.v2.api:calling FileVersionFactory(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>)
DEBUG:b2sdk.v2.bucket:calling FileVersionFactory(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>)
DEBUG:b2sdk.api:calling FileVersionFactory(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>)
DEBUG:b2sdk.api:calling DownloadVersionFactory(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>)
DEBUG:b2sdk.v2.api:calling Services(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>, max_upload_workers=10, max_copy_workers=10, max_download_workers=None, save_to_buffer_size=None, check_download_hash=True, max_download_streams_per_file=None)
DEBUG:b2sdk.api:calling Services(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>, max_upload_workers=10, max_copy_workers=10, max_download_workers=None, save_to_buffer_size=None, check_download_hash=True, max_download_streams_per_file=None)
DEBUG:b2sdk.v2.transfer:calling LazyThreadPool(max_workers=10, kwargs=<class 'inspect._empty'>)
DEBUG:b2sdk.transfer.inbound.downloader.abstract:calling ThreadPoolExecutor(max_workers=10, thread_name_prefix='', initializer=None, initargs=())
DEBUG:b2sdk.utils.thread_pool:calling ThreadPoolExecutor(max_workers=10, thread_name_prefix='', initializer=None, initargs=())
DEBUG:b2sdk.v2.transfer:calling LazyThreadPool(max_workers=None, kwargs=<class 'inspect._empty'>)
DEBUG:b2sdk.transfer.inbound.download_manager:calling ParallelDownloader(min_part_size=104857600, max_streams=None, kwargs={'min_chunk_size': 8192, 'max_chunk_size': 1048576, 'align_factor': None, 'thread_pool': <b2sdk.v2.transfer.LazyThreadPool object at 0x7fe4433a9c10>, 'check_hash': True})
DEBUG:b2sdk.transfer.inbound.download_manager:calling AbstractDownloader(thread_pool=<b2sdk.v2.transfer.LazyThreadPool object at 0x7fe4433a9c10>, force_chunk_size=None, min_chunk_size=8192, max_chunk_size=1048576, align_factor=None, check_hash=True, kwargs=<class 'inspect._empty'>)
INFO:__main__:starting command [__main__.DownloadFile] with arguments: ['/tmp/staticx-IKMLoG/b2', 'download-file', '--profile', 'uploads', '--verbose', 'b2://wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html', './email.html']
DEBUG:b2sdk.v2.transfer:calling ThreadPoolMixin.set_thread_pool_size(self=<b2sdk.v2.transfer.DownloadManager object at 0x7fe4433a93d0>, max_workers=10)
DEBUG:b2sdk.api:calling B2Api.check_bucket_name_restrictions(self=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>, bucket_name='wmr-app-uploads')
DEBUG:b2sdk.v2.api:calling Bucket(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>, id_='f7458e74f1a6816d8115081a', name='wmr-app-uploads', type_=None, bucket_info=None, cors_rules=None, lifecycle_rules=None, revision=None, bucket_dict=None, options_set=None, default_server_side_encryption=<EncryptionSetting(EncryptionMode.UNKNOWN, None, None)>, default_retention=BucketRetentionSetting('unknown', None), is_file_lock_enabled=None, replication=None)
DEBUG:b2sdk.api:calling Bucket(api=<b2sdk.v2.api.B2Api object at 0x7fe44338a360>, id_='f7458e74f1a6816d8115081a', name='wmr-app-uploads', type_=None, bucket_info=None, cors_rules=None, lifecycle_rules=None, revision=None, bucket_dict=None, options_set=None, default_server_side_encryption=<EncryptionSetting(EncryptionMode.UNKNOWN, None, None)>, default_retention=BucketRetentionSetting('unknown', None), is_file_lock_enabled=None, replication=None)
DEBUG:b2sdk.bucket:calling Bucket.download_file_by_name(self=Bucket<f7458e74f1a6816d8115081a,wmr-app-uploads,None>, file_name='quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html', progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x7fe443ced910>, range_=None, encryption=None)
DEBUG:b2sdk.transfer.inbound.download_manager:calling DownloadManager.download_file_from_url(self=<b2sdk.v2.transfer.DownloadManager object at 0x7fe4433a93d0>, url='https://f004.backblazeb2.com/file/wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html', progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x7fe443ced910>, range_=None, encryption=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f004.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://f004.backblazeb2.com:443 "GET /file/wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html HTTP/1.1" 401 68
DEBUG:b2sdk.exception:calling interpret_b2_error(status=401, code='expired_auth_token', message='', response_headers={'Server': 'nginx', 'Date': 'Tue, 16 Jan 2024 17:48:24 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '68', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Strict-Transport-Security': 'max-age=63072000'}, post_params=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://api.backblazeb2.com:443 "POST /b2api/v2/b2_authorize_account HTTP/1.1" 200 706
DEBUG:b2sdk.account_info.abstract:calling AbstractAccountInfo.is_same_account(self=<b2sdk.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7fe44338b5f0>, account_id='75e4161d158a', realm='production')
DEBUG:b2sdk.account_info.abstract:calling AbstractAccountInfo.set_auth_data(self=<b2sdk.account_info.sqlite_account_info.SqliteAccountInfo object at 0x7fe44338b5f0>, api_url='https://api004.backblazeb2.com', download_url='https://f004.backblazeb2.com', recommended_part_size=100000000, absolute_minimum_part_size=5000000, realm='production', s3_api_url='https://s3.us-west-004.backblazeb2.com') (hidden args: account_id, auth_token, application_key, allowed, application_key_id)
DEBUG:b2sdk.account_info.abstract:calling AbstractAccountInfo.allowed_is_valid(cls=<class 'b2sdk.account_info.sqlite_account_info.SqliteAccountInfo'>, allowed={'bucketId': 'f7458e74f1a6816d8115081a', 'bucketName': 'wmr-app-uploads', 'capabilities': ['listFiles', 'shareFiles', 'readBuckets', 'readFiles', 'readBucketReplications', 'listAllBucketNames', 'readBucketEncryption', 'listBuckets'], 'namePrefix': None})
DEBUG:b2sdk.account_info.abstract:calling AbstractAccountInfo.allowed_is_valid(cls=<class 'b2sdk.account_info.sqlite_account_info.SqliteAccountInfo'>, allowed={'bucketId': 'f7458e74f1a6816d8115081a', 'bucketName': 'wmr-app-uploads', 'capabilities': ['listFiles', 'shareFiles', 'readBuckets', 'readFiles', 'readBucketReplications', 'listAllBucketNames', 'readBucketEncryption', 'listBuckets'], 'namePrefix': None})
DEBUG:urllib3.connectionpool:https://f004.backblazeb2.com:443 "GET /file/wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html HTTP/1.1" 200 None
ERROR:__main__:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "b2/console_tool.py", line 4050, in run_command
  File "b2/console_tool.py", line 835, in run
  File "b2/console_tool.py", line 1685, in _run
  File "functools.py", line 946, in _method
  File "b2/_utils/uri.py", line 134, in _
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 281, in download_file_by_name
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
Traceback (most recent call last):
  File "b2/console_tool.py", line 4163, in <module>
  File "b2/console_tool.py", line 4148, in main
  File "b2/console_tool.py", line 4050, in run_command
  File "b2/console_tool.py", line 835, in run
  File "b2/console_tool.py", line 1685, in _run
  File "functools.py", line 946, in _method
  File "b2/_utils/uri.py", line 134, in _
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 281, in download_file_by_name
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
[1371265] Failed to execute script 'console_tool' due to unhandled exception!
```

**Comment by ppolewicz** [comment]
This does not look good at all!

Now please run `export B2_DEBUG_HTTP=1` and then run the same command with --verbose again BUT do not paste the entire output here, because it will contain full headers and some of them can be read by some other user here and used to compromise your accoint.

We are looking for a part that starts with "GET /file/wmr-app-uploads/quotes/2027-414/emails/60e3c8f7-45d4-f9b4-3904-3d481dc59755/email.html HTTP/1.1" which will be followed by client headers, which should then be followed by server-side headers, which should contain lines which look like these:
```
Content-Length
Content-Type
X-Bz-File-Id
X-Bz-File-Name
X-Bz-Content-Sha1
X-Bz-Upload-Timestamp
```
followed by `:` and then by an appropriate value. Now what it looks like is that either the server didn't send `Content-Length` at all, or it sent something weird inside or something - hard to say. That's why we are looking at the logs :)

If you could please post the response headers, triple-checking that there are no authorization tokens anywhere in the output, this would accelerate the progress on addressing this issue by a lot!

**Comment by simion** [comment]
We're having the exact same issue with b2sdk python, and only for filenames ending with `.html`.
Switching to a `.txt` extension works.

Traceback:

```
   file_details = self.bucket.download_file_by_name(name, download_dest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/b2sdk/v1/bucket.py", line 138, in download_file_by_name
    downloaded_file = super().download_file_by_name(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/b2sdk/bucket.py", line 281, in download_file_by_name
    return self.api.services.download_manager.download_file_from_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/logfury/_logfury/trace_call.py", line 86, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
    download_version = self.services.api.download_version_factory.from_response_headers(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/b2sdk/file_version.py", line 616, in from_response_headers
    size = content_length = int(headers['Content-Length'])
                                ~~~~~~~^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-length'
```

here are some variables from `file_version.py", line 616, in from_response_headers`:
``` python
# file info
{'uploaded_ts': '1705481348.175359', 'compression': 'lz4'}
# headers
{'Server': 'nginx', 'Date': 'Wed, 17 Jan 2024 08:55:08 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'x-bz-file-name': 'merchants/0/0419/4042/4194042.html', 'x-bz-file-id': '4_z58ec7d7c2801162c7f260010_f1037624e5db54f99_d20240117_m084908_c003_v0312023_t0004_u01705481348450', 'x-bz-content-sha1': 'a9007678626931f945b034f32d980126d12bd3ee', 'X-Bz-Upload-Timestamp': '1705481348450', 'x-bz-info-uploaded_ts': '1705481348.175359', 'x-bz-info-compression': 'lz4', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Strict-Transport-Security': 'max-age=63072000', 'Content-Encoding': 'gzip'}
```

Tried with b2sdk.v1 and b2sdk.v2, same error.


I've also tried to download this file via Cyberduck (it used b2 api, not s3) and it fails: 
![image](https://github.com/Backblaze/B2_Command_Line_Tool/assets/2630797/758d25d4-adb6-4e41-834d-c1eb351d47d1)

This looks like a major outage for all `.html` files no matter what client we're using.

**Comment by wmr-trevor** [comment]
Ok. So this morning I set up a new bucket and uploaded a test html file. Still the same issue. I have made this bucket public so hopefully you can try this out yourself. 

I also didn't find the exact information that you were looking for. Either I'm missing something, or I'm totally not getting the result we hoped.

```shell
DEBUG:b2sdk.bucket:calling Bucket.download_file_by_name(self=Bucket<47159ef48186117d81d5081a,testing-html-downloads,None>, file_name='test-1.html', progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x7f63d39a4e60>, range_=None, encryption=None)
DEBUG:b2sdk.transfer.inbound.download_manager:calling DownloadManager.download_file_from_url(self=<b2sdk.v2.transfer.DownloadManager object at 0x7f63d3a446e0>, url='https://f004.backblazeb2.com/file/testing-html-downloads/test-1.html', progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x7f63d39a4e60>, range_=None, encryption=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f004.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://f004.backblazeb2.com:443 "GET /file/testing-html-downloads/test-1.html HTTP/1.1" 200 None
ERROR:__main__:ConsoleTool unexpected exception
Traceback (most recent call last):
  File "b2/console_tool.py", line 4050, in run_command
  File "b2/console_tool.py", line 835, in run
  File "b2/console_tool.py", line 1685, in _run
  File "functools.py", line 946, in _method
  File "b2/_utils/uri.py", line 134, in _
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 281, in download_file_by_name
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
Traceback (most recent call last):
  File "b2/console_tool.py", line 4163, in <module>
  File "b2/console_tool.py", line 4148, in main
  File "b2/console_tool.py", line 4050, in run_command
  File "b2/console_tool.py", line 835, in run
  File "b2/console_tool.py", line 1685, in _run
  File "functools.py", line 946, in _method
  File "b2/_utils/uri.py", line 134, in _
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/bucket.py", line 281, in download_file_by_name
  File "logfury/_logfury/trace_call.py", line 86, in wrapper
  File "b2sdk/transfer/inbound/download_manager.py", line 98, in download_file_from_url
  File "b2sdk/file_version.py", line 616, in from_response_headers
  File "requests/structures.py", line 52, in __getitem__
KeyError: 'content-length'
[2172296] Failed to execute script 'console_tool' due to unhandled exception!
```

**Comment by wmr-trevor** [comment]
Forgot to add this part. Did the same thing with test-2.txt and got a different result.

```shell
DEBUG:b2sdk.transfer.inbound.download_manager:calling DownloadManager.download_file_from_url(self=<b2sdk.v2.transfer.DownloadManager object at 0x7f80c7dbd8b0>, url='https://f004.backblazeb2.com/file/testing-html-downloads/test-2.txt', progress_listener=<b2sdk.progress.TqdmProgressListener object at 0x7f80c7dbcfe0>, range_=None, encryption=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f004.backblazeb2.com:443
DEBUG:urllib3.connectionpool:https://f004.backblazeb2.com:443 "GET /file/testing-html-downloads/test-2.txt HTTP/1.1" 200 11
File name:           test-2.txt
File id:             4_z47159ef48186117d81d5081a_f105419f8bd9d1061_d20240117_m140128_c004_v0402016_t0044_u01705500088202
File size:           11
Content type:        text/plain
Content sha1:        6c1a60f4494cd6f0dd7792e1ae0c5cfea3faa497
Encryption:          none
Retention:           none
Legal hold:          <unset>
INFO src_last_modified_millis: 1705500084253
Checksum matches
```

To make it easier to debug, I don't mind sending application keys to the test bucket that I created. But I imagine you should be able to replicate it pretty easily.

**Comment by ppolewicz** [comment]
It looks like now it works, I was able to reproduce it for a brief moment, but I no longer can.

**Comment by wmr-trevor** [comment]
Yes. Looks like it is working now. The sync this morning downloaded all of the missing html files without any issues. For my part we can consider this issue resolved then.
